//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 920.3.0.0.0
//
#ifndef NRPBDeviceCollectionHistoryEntry_h
#define NRPBDeviceCollectionHistoryEntry_h
@import Foundation;

#include "PBCodable.h"
#include "NRPBDeviceCollectionDiff.h"
#include "NSCopying-Protocol.h"

@interface NRPBDeviceCollectionHistoryEntry : PBCodable<NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 date; unsigned int x :1 index; } _has;
}

@property (nonatomic) BOOL hasIndex;
@property (nonatomic) long long index;
@property (nonatomic) BOOL hasDate;
@property (nonatomic) double date;
@property (readonly, nonatomic) BOOL hasDiff;
@property (retain, nonatomic) NRPBDeviceCollectionDiff *diff;

/* instance methods */
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* NRPBDeviceCollectionHistoryEntry_h */
