//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.0.0.0.0
//
#ifndef FCHeadlineFeatureArticleTypeNonFlint_h
#define FCHeadlineFeatureArticleTypeNonFlint_h
@import Foundation;

#include "FCPersonalizationFeature.h"

@interface FCHeadlineFeatureArticleTypeNonFlint : FCPersonalizationFeature
/* class methods */
+ (id)articleTypeNonFlintFeature;

/* instance methods */
- (id)init;
@end

#endif /* FCHeadlineFeatureArticleTypeNonFlint_h */
