//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.0.0.0.0
//
#ifndef FCKeyValueStoreMigrating_Protocol_h
#define FCKeyValueStoreMigrating_Protocol_h
@import Foundation;

@protocol FCKeyValueStoreMigrating <NSObject>
/* instance methods */
- (BOOL)keyValueStore:(id)store canMigrateFromVersion:(unsigned long long)version;
- (id)keyValueStore:(id)store migrateObject:(id)object forKey:(id)key fromVersion:(unsigned long long)version;
@end

#endif /* FCKeyValueStoreMigrating_Protocol_h */
