//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.0.0.0.0
//
#ifndef FCPrivateChannelMembershipController_h
#define FCPrivateChannelMembershipController_h
@import Foundation;

#include "FCPrivateDataController.h"
#include "FCAppActivityObserving-Protocol.h"
#include "FCMTWriterLock.h"

@class NSDictionary, NSMutableSet, NSString;

@interface FCPrivateChannelMembershipController : FCPrivateDataController<FCAppActivityObserving> {
  /* instance variables */
  NSDictionary *_membershipsByChannelID;
  NSMutableSet *_membershipReferences;
  FCMTWriterLock *_membershipsLock;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)requiresPushNotificationSupport;
+ (BOOL)requiresBatchedSync;
+ (BOOL)requiresHighPriorityFirstSync;
+ (id)backingRecordZoneIDs;
+ (id)backingRecordIDs;
+ (id)localStoreFilename;
+ (unsigned long long)localStoreVersion;
+ (id)commandStoreFileName;
+ (long long)commandQueueUrgency;
+ (id)commandsToMergeLocalDataToCloud:(id)cloud privateDataDirectory:(id)directory;
+ (id)desiredKeys;

/* instance methods */
- (id)initWithContext:(id)context pushNotificationCenter:(id)center storeDirectory:(id)directory;
- (void)dealloc;
- (BOOL)isMemberOfChannelID:(id)id;
- (BOOL)isAllowedToSeeDraftsForChannelID:(id)id;
- (id)feedDescriptorForDraftFeedForChannel:(id)channel;
- (void)isAllowedToSeeArticleID:(id)id completionBlock:(id /* block */)block;
- (void)isAllowedToSeeIssueID:(id)id completionBlock:(id /* block */)block;
- (BOOL)hasMemberships;
- (id)membershipChannelIDs;
- (void)loadLocalCachesFromStore;
- (void)handleSyncWithChangedRecords:(id)records deletedRecordNames:(id)names;
- (id)allKnownRecordNamesWithinRecordZoneWithID:(id)id;
- (void)addObserver:(id)observer;
- (void)removeObserver:(id)observer;
- (void)activityObservingApplicationWindowDidBecomeForeground;
@end

#endif /* FCPrivateChannelMembershipController_h */
