//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 75.3.6.0.1
//
#ifndef _TtC24IntelligencePlatformCore14EventLogWriter_h
#define _TtC24IntelligencePlatformCore14EventLogWriter_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface IntelligencePlatformCore.EventLogWriter : Swift._SwiftObject { // (Swift)
  /* instance variables */
   encoder;
   decoder;
   policies;
   storage;
   bufferedWriter;
}

@end

#endif /* _TtC24IntelligencePlatformCore14EventLogWriter_h */
