//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 75.3.6.0.1
//
#ifndef _TtCC24IntelligencePlatformCoreP33_AD948141065DF512D4334E10387519D417OneShotSingletons11GuardedData_h
#define _TtCC24IntelligencePlatformCoreP33_AD948141065DF512D4334E10387519D417OneShotSingletons11GuardedData_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface IntelligencePlatformCore.(OneShotSingletons in _AD948141065DF512D4334E10387519D4).GuardedData : Swift._SwiftObject { // (Swift)
  /* instance variables */
   instances;
}

@end

#endif /* _TtCC24IntelligencePlatformCoreP33_AD948141065DF512D4334E10387519D417OneShotSingletons11GuardedData_h */
