//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPCAssistantCommandInternal_h
#define MPCAssistantCommandInternal_h
@import Foundation;

#include "MPCAssistantEndpointContext.h"
#include "MPCAssistantSendCommand.h"

@class NSDate, NSMutableDictionary;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface MPCAssistantCommandInternal : NSObject {
  /* instance variables */
  MPCAssistantSendCommand *_sendCommand;
  MPCAssistantEndpointContext *_context;
  NSObject<OS_dispatch_queue> *_sendCommandQueue;
  NSMutableDictionary *_analytics;
  NSObject<OS_dispatch_queue> *_analyticsQueue;
  NSObject<OS_dispatch_group> *_analyticsGroup;
  NSDate *_startDate;
}

/* instance methods */
- (id)init;
- (void)sendCommandWithResult:(unsigned int)result toDestination:(id)destination withOptions:(id)options completion:(id /* block */)completion;
- (void)sendPlaybackQueueWithResult:(id)result toDestination:(id)destination withOptions:(id)options completion:(id /* block */)completion;
- (void)sendPlaybackArchiveWithResult:(id)result toDestination:(id)destination withOptions:(id)options completion:(id /* block */)completion;
- (id)_applyOriginatingDeviceUIDs:(id)uids;
- (void)_findOutputDevicesForDestination:(id)destination options:(id)options completion:(id /* block */)completion;
- (void)_setAnalyticsKey:(id)key value:(id)value;
- (void)_setAnalyticsError:(id)error;
@end

#endif /* MPCAssistantCommandInternal_h */
