//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.3.0.0
//
#ifndef MPCScriptedLooper_h
#define MPCScriptedLooper_h
@import Foundation;

#include "MPCSceneCollection.h"

@class AVPlayer, MPNotificationObserver, NSError;

@interface MPCScriptedLooper : NSObject

@property (nonatomic) long long status;
@property (retain, nonatomic) NSError *error;
@property (copy, nonatomic) id /* block */ pauseFinishedBlock;
@property (retain, nonatomic) MPCSceneCollection *sceneCollection;
@property (retain, nonatomic) id timeObserver;
@property (retain, nonatomic) MPNotificationObserver *itemDidPlayToEndObserver;
@property (nonatomic) long long currentSceneIndex;
@property (nonatomic) long long currentLoopCount;
@property (nonatomic) BOOL executingPauseScene;
@property (nonatomic) BOOL sceneExecutionPaused;
@property (readonly, nonatomic) AVPlayer *player;

/* class methods */
+ (BOOL)isScriptedLoopingDisabled;
+ (void)setScriptedLoopingDisabled:(BOOL)disabled;

/* instance methods */
- (id)initWithAsset:(id)asset;
- (id)initWithAsset:(id)asset audioSession:(id)session;
- (id)initWithURL:(id)url sceneCollection:(id)collection;
- (id)initWithURL:(id)url sceneCollection:(id)collection audioSession:(id)session;
- (id)initWithAsset:(id)asset sceneCollection:(id)collection;
- (id)initWithAsset:(id)asset sceneCollection:(id)collection audioSession:(id)session;
- (void)_sharedInitWithItem:(id)item audioSession:(id)session;
- (void)dealloc;
- (void)restartScenes;
- (void)playScenes;
- (void)pauseScenes;
- (void)observeValueForKeyPath:(id)path ofObject:(id)object change:(id)change context:(void *)context;
- (id)currentScene;
- (void)seekToFrameIfNeeded:(long long)needed completionHandler:(id /* block */)handler;
- (long long)frameForCMTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })cmtime;
- (void)_createSceneCollectionForAssetWithPreloadedKeys:(id)keys;
- (struct { long long x0; int x1; unsigned int x2; long long x3; })_CMTimeForFrame:(long long)frame;
- (void)_executeSceneCollection;
- (void)_executeCurrentScene;
- (void)_loopIfNeeded;
- (void)_advanceScene;
- (void)_pause;
- (void)_updateRateIfNeeded;
- (BOOL)isExecutingPauseScene;
- (BOOL)isSceneExecutionPaused;
@end

#endif /* MPCScriptedLooper_h */
