//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 371.14.0.0.0
//
#ifndef DNDSAppForegroundTriggerConfiguration_h
#define DNDSAppForegroundTriggerConfiguration_h
@import Foundation;

@class NSDictionary;

@interface DNDSAppForegroundTriggerConfiguration : NSObject {
  /* instance variables */
  NSDictionary *_bundleIDToModeIdentifierTriggers;
}

/* instance methods */
- (id)init;
- (id)triggeringBundleIdentifiers;
- (id)modeIdentifierForBundleIdentifier:(id)identifier;
- (void)addTriggerForModeWithIdentifier:(id)identifier onForegroundOfApp:(id)app;
- (id)description;
@end

#endif /* DNDSAppForegroundTriggerConfiguration_h */
