//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1262.300.81.4.10
//
#ifndef IMDMomentShareIngestionContext_h
#define IMDMomentShareIngestionContext_h
@import Foundation;

#include "IMDChat.h"

@class IMMessageItem, NSDictionary, NSMutableDictionary, NSURL, PHFetchResult, PHMomentShare;

@interface IMDMomentShareIngestionContext : NSObject

@property (readonly, nonatomic) NSURL *shareURL;
@property (readonly, nonatomic) IMMessageItem *message;
@property (readonly, nonatomic) IMDChat *chat;
@property (retain, nonatomic) PHMomentShare *momentShare;
@property (retain, nonatomic) PHFetchResult *assetsFetch;
@property (nonatomic) long long fetchType;
@property (nonatomic) long long state;
@property (readonly, nonatomic) NSDictionary *assetUUIDsToFileTransfers;

/* instance methods */
- (id)initWithURL:(id)url message:(id)message inChat:(id)chat;
- (void)addTransfers:(id)transfers;
- (void)clearAllTransfers;
- (void)completeTransferForAssetUUID:(id)uuid;
@end

#endif /* IMDMomentShareIngestionContext_h */
