//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.0.0.0.0
//
#ifndef NTPBLinkTap_h
#define NTPBLinkTap_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"

@class NSData, NSString;

@interface NTPBLinkTap : PBCodable<NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 groupType; unsigned int x :1 linkType; unsigned int x :1 tapLocationType; unsigned int x :1 webEmbedLocation; } _has;
}

@property (nonatomic) BOOL hasTapLocationType;
@property (nonatomic) int tapLocationType;
@property (readonly, nonatomic) BOOL hasArticleId;
@property (retain, nonatomic) NSString *articleId;
@property (readonly, nonatomic) BOOL hasReferencedArticleId;
@property (retain, nonatomic) NSString *referencedArticleId;
@property (readonly, nonatomic) BOOL hasTappedLinkUrl;
@property (retain, nonatomic) NSString *tappedLinkUrl;
@property (readonly, nonatomic) BOOL hasWebEmbedId;
@property (retain, nonatomic) NSString *webEmbedId;
@property (nonatomic) BOOL hasWebEmbedLocation;
@property (nonatomic) int webEmbedLocation;
@property (nonatomic) BOOL hasLinkType;
@property (nonatomic) int linkType;
@property (nonatomic) BOOL hasGroupType;
@property (nonatomic) int groupType;
@property (readonly, nonatomic) BOOL hasArticleViewingSessionId;
@property (retain, nonatomic) NSData *articleViewingSessionId;

/* instance methods */
- (id)webEmbedLocationAsString:(int)string;
- (int)StringAsWebEmbedLocation:(id)location;
- (id)groupTypeAsString:(int)string;
- (int)StringAsGroupType:(id)type;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* NTPBLinkTap_h */
