//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HDSampleEntity_h
#define HDSampleEntity_h
@import Foundation;

#include "HDDataEntity.h"

@interface HDSampleEntity : HDDataEntity
/* class methods */
+ (id)databaseTable;
+ (const struct { id x0; id x1; unsigned char x2; } *)columnDefinitionsWithCount:(unsigned long long *)count;
+ (id)indices;
+ (Class)_deletedEntityClass;
+ (Class)_entityClassForDeletion;
+ (id)insertDataObject:(id)object withProvenance:(id)provenance inDatabase:(id)database persistentID:(id)id error:(id *)error;
+ (BOOL)requiresSampleTypePredicate;
+ (id)orderingTermForSortDescriptor:(id)descriptor;
+ (id)mostRecentSampleWithType:(id)type profile:(id)profile encodingOptions:(id)options predicate:(id)predicate anchor:(id *)anchor error:(id *)error;
+ (id)oldestSampleWithType:(id)type profile:(id)profile encodingOptions:(id)options predicate:(id)predicate error:(id *)error;
+ (id)maxAnchorForSamplesWithType:(id)type profile:(id)profile error:(id *)error;
+ (void)deleteSamplesWithTypes:(id)types sourceEntities:(id)entities profile:(id)profile recursiveDeleteAuthorizationBlock:(id /* block */)block completionHandler:(id /* block */)handler;
+ (void)deleteSamplesWithPredicate:(id)predicate limit:(unsigned long long)limit generateDeletedObjects:(BOOL)objects transaction:(id)transaction profile:(id)profile recursiveDeleteAuthorizationBlock:(id /* block */)block completionHandler:(id /* block */)handler;
+ (void)deleteSamplesWithPredicate:(id)predicate limit:(unsigned long long)limit deletionContext:(id)context completionHandler:(id /* block */)handler;
+ (BOOL)enumerateAssociatedObjectsForIdentifier:(long long)identifier inDatabase:(id)database error:(id *)error associatedObjectHandler:(id /* block */)handler;
+ (id)samplesWithType:(id)type profile:(id)profile encodingOptions:(id)options predicate:(id)predicate limit:(unsigned long long)limit anchor:(id *)anchor error:(id *)error;
+ (id)entityEnumeratorWithType:(id)type profile:(id)profile;
+ (id)entityEnumeratorWithTypes:(id)types profile:(id)profile error:(id *)error;
+ (id)sourceIDsForSamplesWithType:(id)type profile:(id)profile predicate:(id)predicate error:(id *)error;
+ (long long)countOfSamplesWithType:(id)type profile:(id)profile matchingPredicate:(id)predicate withError:(id *)error;
+ (id)sampleCountsByTypeForProfile:(id)profile error:(id *)error;
+ (id)dateIntervalsForSampleTypes:(id)types profile:(id)profile error:(id *)error;
+ (id)populatedSampleTypes:(id)types inDateInterval:(id)interval profile:(id)profile error:(id *)error;
+ (id)sampleTypesForSamplesMatchingPredicate:(id)predicate profile:(id)profile error:(id *)error;
+ (id)anySampleOfType:(id)type profile:(id)profile encodingOptions:(id)options predicate:(id)predicate error:(id *)error;
+ (id)minimumSampleStartDateForProfile:(id)profile error:(id *)error;
+ (BOOL)validateEntitiesOfTypes:(id)types profile:(id)profile error:(id *)error validationErrorHandler:(id /* block */)handler;
+ (BOOL)_validateEntityWithEnumerator:(id)enumerator error:(id *)error validationErrorHandler:(id /* block */)handler;
+ (id)syntheticQuantityColumnName;
+ (long long)preferredEntityType;
+ (id /* block */)objectInsertionFilterForProfile:(id)profile;
+ (id)entityEncoderForProfile:(id)profile transaction:(id)transaction purpose:(long long)purpose encodingOptions:(id)options authorizationFilter:(id /* block */)filter;
+ (id)columnNamesForTimeOffset;
@end

#endif /* HDSampleEntity_h */
