//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef DOMWheelEvent_h
#define DOMWheelEvent_h
@import Foundation;

#include "DOMMouseEvent.h"

@interface DOMWheelEvent : DOMMouseEvent

@property (readonly) int wheelDeltaX;
@property (readonly) int wheelDeltaY;
@property (readonly) int wheelDelta;
@property (readonly) BOOL isHorizontal;

/* instance methods */
- (double)deltaX;
- (double)deltaY;
- (double)deltaZ;
- (unsigned int)deltaMode;
- (BOOL)webkitDirectionInvertedFromDevice;
- (void)initWheelEvent:(int)event wheelDeltaY:(int)y view:(id)view screenX:(int)x screenY:(int)y clientX:(int)x clientY:(int)y ctrlKey:(BOOL)key altKey:(BOOL)key shiftKey:(BOOL)key metaKey:(BOOL)key;
@end

#endif /* DOMWheelEvent_h */
