//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 949.0.0.0.0
//
#ifndef NWKLRUCacheNode_h
#define NWKLRUCacheNode_h
@import Foundation;

#include "NWKLRUCacheNode.h"

@interface NWKLRUCacheNode : NSObject

@property (readonly, nonatomic) id key;
@property (readonly, nonatomic) id value;
@property (retain, nonatomic) NWKLRUCacheNode *previousNode;
@property (retain, nonatomic) NWKLRUCacheNode *nextNode;

/* instance methods */
- (id)initWithValue:(id)value forKey:(id)key;
@end

#endif /* NWKLRUCacheNode_h */
