//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 949.0.0.0.0
//
#ifndef NWKWFWeatherChannelParserV2_h
#define NWKWFWeatherChannelParserV2_h
@import Foundation;

@interface NWKWFWeatherChannelParserV2 : NSObject
/* class methods */
+ (id)parsedForecastModelFromData:(id)data forLocation:(id)location date:(id)date;
@end

#endif /* NWKWFWeatherChannelParserV2_h */
