//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1880.5.0.0.0
//
#ifndef NLFirstGlanceAchievementDataProvider_h
#define NLFirstGlanceAchievementDataProvider_h
@import Foundation;

#include "NLFirstGlanceDataProvider.h"
#include "NLFirstGlanceAchievementDataProvider-Protocol.h"

@class NSString;

@interface NLFirstGlanceAchievementDataProvider : NLFirstGlanceDataProvider<NLFirstGlanceAchievementDataProvider>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)progressAchievementAndMilestoneWithCompletion:(id /* block */)completion;
- (id)progressLocalizationKeyForAchievement:(id)achievement progressMilestone:(id)milestone;
- (id)yesterdayLocalizationKeyForAchievement:(id)achievement;
- (id)completedAchievementForYesterday;
- (BOOL)hasAchievementProgressToDisplay;
- (void)_firstAchievementFromAchievements:(id)achievements passingMilestoneTest:(id /* block */)test completion:(id /* block */)completion;
@end

#endif /* NLFirstGlanceAchievementDataProvider_h */
