//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1450.2.4.0.0
//
#ifndef SSAppWakeRequest_h
#define SSAppWakeRequest_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface SSAppWakeRequest : NSObject<NSCopying>

@property (copy, nonatomic) NSString *appIdentifier;
@property (copy, nonatomic) NSDictionary *launchOptions;
@property (nonatomic) BOOL shouldLaunchApp;
@property (copy, nonatomic) NSString *processAssertionIdentifier;
@property (nonatomic) double processAssertionInterval;
@property (copy, nonatomic) NSString *processAssertionReason;

/* class methods */
+ (id)familyContentRemovalRequestWithAppIdentifier:(id)identifier accountPairs:(id)pairs;
+ (id)newsstandFinishRequestWithAppIdentifier:(id)identifier issueIdentifiers:(id)identifiers;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* SSAppWakeRequest_h */
