//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1450.2.4.0.0
//
#ifndef SSPreorder_h
#define SSPreorder_h
@import Foundation;

#include "SSItemImageCollection.h"
#include "SSXPCCoding-Protocol.h"

@class NSDate, NSNumber, NSString;

@interface SSPreorder : NSObject<SSXPCCoding> {
  /* instance variables */
  NSNumber *_accountID;
  unsigned long long _itemID;
  long long _pid;
  unsigned long long _preorderID;
}

@property (readonly, nonatomic) NSString *artistName;
@property (readonly, nonatomic) SSItemImageCollection *imageCollection;
@property (readonly, nonatomic) NSString *itemKind;
@property (readonly, nonatomic) long long persistentIdentifier;
@property (readonly, nonatomic) NSDate *releaseDate;
@property (readonly, nonatomic) NSString *releaseDateString;
@property (readonly, nonatomic) NSNumber *storeAccountIdentifier;
@property (readonly, nonatomic) unsigned long long storeItemIdentifier;
@property (readonly, nonatomic) unsigned long long storePreorderIdentifier;
@property (readonly, nonatomic) NSString *title;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)_initWithPersistentIdentifier:(long long)identifier;
- (void)dealloc;
- (id)copyReleaseDateStringWithStyle:(long long)style;
- (void)_setArtistName:(id)name;
- (void)_setImageCollection:(id)collection;
- (void)_setItemKind:(id)kind;
- (void)_setReleaseDate:(id)date;
- (void)_setReleaseDateString:(id)string;
- (void)_setStoreAccountIdentifier:(id)identifier;
- (void)_setStoreItemIdentifier:(long long)identifier;
- (void)_setStorePreorderIdentifier:(long long)identifier;
- (void)_setTitle:(id)title;
- (BOOL)isEqual:(id)equal;
- (id)initWithXPCEncoding:(id)xpcencoding;
- (id)copyXPCEncoding;
@end

#endif /* SSPreorder_h */
