//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef PKContactlessCardIngester_h
#define PKContactlessCardIngester_h
@import Foundation;

#include "PKPaymentProvisioningMethodMetadata.h"

@class NSNumberFormatter, NSString;
@protocol OS_dispatch_queue, PKContactlessCardIngesterDelegate;

@interface PKContactlessCardIngester : NSObject {
  /* instance variables */
  BOOL _listening;
  NSString *_pushTopic;
  PKPaymentProvisioningMethodMetadata *_readerModeProvisioningMetadata;
  NSNumberFormatter *_currencyNumberFormatter;
  NSObject<PKContactlessCardIngesterDelegate> *_delegate;
  NSObject<OS_dispatch_queue> *_contactlessCardIngesterQueue;
  id /* block */ _cardSessionTokenCompletionHandler;
  id /* block */ _disableCardCompletionHandler;
}

/* class methods */
+ (BOOL)isSupported;
+ (id)debugDescriptionForStatus:(unsigned long long)status;

/* instance methods */
- (id)initWithPaymentSetupProduct:(id)product delegate:(id)delegate;
- (void)invalidate;
- (void)ingestCardWithSuccessHandler:(id /* block */)handler;
- (void)ingestCardWithCardSessionToken:(id)token successHandler:(id /* block */)handler;
- (void)_cancelCardIngestion;
- (void)_ingestCardWithCompletion:(id /* block */)completion;
- (void)_ingestCardWithCardSessionToken:(id)token completion:(id /* block */)completion;
- (void)_stopListeningToRemoteAdminEvents;
- (void)_startListeningToRemoteAdminEventsIfRequired;
- (id)_displayableErrorForSPStatusCode:(unsigned long long)code seldError:(id)error;
@end

#endif /* PKContactlessCardIngester_h */
