//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef PKPaymentTransactionAward_h
#define PKPaymentTransactionAward_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "PKTransactionAmount.h"

@class NSDate, NSString;

@interface PKPaymentTransactionAward : NSObject<NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSString *typeString;
@property (copy, nonatomic) NSString *identifier;
@property (nonatomic) long long type;
@property (copy, nonatomic) NSString *subtype;
@property (nonatomic) long long order;
@property (copy, nonatomic) PKTransactionAmount *amount;
@property (copy, nonatomic) NSString *localizedAmount;
@property (copy, nonatomic) NSString *awardDescription;
@property (copy, nonatomic) NSString *relevantAccountName;
@property (nonatomic) BOOL hasDeepLink;
@property (copy, nonatomic) NSDate *claimExpiryDate;
@property (nonatomic) BOOL claimExpired;
@property (copy, nonatomic) NSDate *redeemExpiryDate;
@property (nonatomic) BOOL redeemExpired;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithDictionary:(id)dictionary;
- (id)formattedStringValue;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
- (BOOL)isEqualToPaymentTransactionAward:(id)award;
@end

#endif /* PKPaymentTransactionAward_h */
