//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3774.300.42.0.0
//
#ifndef MERemoteExtensionContext_h
#define MERemoteExtensionContext_h
@import Foundation;

#include "NSExtensionContext.h"
#include "MEExtensionRemoteHostProtocol-Protocol.h"
#include "MERemoteExtensionProtocol-Protocol.h"

@class NSArray, NSMapTable, NSString;

@interface MERemoteExtensionContext : NSExtensionContext<MERemoteExtensionProtocol>

@property (retain, nonatomic) NSMapTable *composeSessionToHandlerMap;
@property (readonly) NSObject<MEExtensionRemoteHostProtocol> *remoteHostPoxy;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSArray *requiredHeaders;

/* class methods */
+ (id)log;
+ (id)_extensionAuxiliaryVendorProtocol;
+ (id)_extensionAuxiliaryHostProtocol;

/* instance methods */
- (id)initWithInputItems:(id)items listenerEndpoint:(id)endpoint contextUUID:(id)uuid;
- (void)dealloc;
- (id)remoteProxy;
- (id)_extensionInterface;
- (id)_createPrincipalObject;
- (id)_contentBlockerInterface;
- (id)contentRulesJSON;
- (void)contentRulesJSONWithCompletionHandler:(id /* block */)handler;
- (id)_mailActionInterface;
- (void)decideActionForMessage:(id)message completionHandler:(id /* block */)handler;
- (void)requiredHeadersWithCompletion:(id /* block */)completion;
- (id)_composeSessionInterfaceForSession:(id)session;
- (void)mailComposeSessionDidBegin:(id)begin;
- (void)mailComposeSessionDidEnd:(id)end;
- (void)session:(id)session annotateAddressesWithCompletionHandler:(id /* block */)handler;
- (void)session:(id)session canSendMessageWithCompletionHandler:(id /* block */)handler;
- (void)session:(id)session hasSendMessageCheckWithCompletion:(id /* block */)completion;
- (id)additionalHeadersForSession:(id)session;
- (void)session:(id)session getAdditionalHeadersWithCompletion:(id /* block */)completion;
- (id)_messageSecurityHandlerInterface;
- (void)getEncodingStatusForMessage:(id)message composeContext:(id)context completionHandler:(id /* block */)handler;
- (void)encodeMessage:(id)message composeContext:(id)context completionHandler:(id /* block */)handler;
- (id)decodedMessageForMessageData:(id)data;
- (id)decodedMessageForMessageData:(id)data decodeContext:(id)context;
- (void)decodedMessageForMessageData:(id)data decodeContext:(id)context withCompletionHandler:(id /* block */)handler;
@end

#endif /* MERemoteExtensionContext_h */
