//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 127.16.0.0.0
//
#ifndef _TtC18ActivityUIServices33ActivitySystemApertureSceneHandle_ActivityUIServices_h
#define _TtC18ActivityUIServices33ActivitySystemApertureSceneHandle_ActivityUIServices_h
@import Foundation;

@interface ActivityUIServices.ActivitySystemApertureSceneHandle (ActivityUIServices) <FBSceneDelegate>
/* instance methods */
- (void)sceneDidActivate:(id)activate;
- (void)sceneDidInvalidate:(id)invalidate;
- (void)sceneDidDeactivate:(id)deactivate withError:(id)error;
- (void)scene:(id)scene didReceiveActions:(id)actions;
- (void)scene:(id)scene didUpdateClientSettingsWithDiff:(id)diff oldClientSettings:(id)settings transitionContext:(id)context;
@end

#endif /* _TtC18ActivityUIServices33ActivitySystemApertureSceneHandle_ActivityUIServices_h */
