//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 127.16.0.0.0
//
#ifndef ACUISActivityMetricsRequest_h
#define ACUISActivityMetricsRequest_h
@import Foundation;

#include "ACUISActivityItemMetricsRequest.h"
#include "ACUISSystemApertureMetricsRequest.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class _TtC18ActivityUIServices22ActivityMetricsRequest;

@interface ACUISActivityMetricsRequest : NSObject<NSCopying, NSSecureCoding> {
  /* instance variables */
  ActivityUIServices.ActivityMetricsRequest *_metricsRequest;
}

@property (copy, nonatomic) ACUISActivityItemMetricsRequest *ambientMetrics;
@property (copy, nonatomic) ACUISActivityItemMetricsRequest *lockScreenMetrics;
@property (copy, nonatomic) ACUISSystemApertureMetricsRequest *systemApertureMetrics;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)_initWithMetricsRequest:(id)request;
- (id)initWithLockScreenMetrics:(id)metrics;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)description;
- (id)_activityMetricsRequest;
- (id)_ACUISItemMetricsRequestFromRequest:(id)request;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* ACUISActivityMetricsRequest_h */
