//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 127.16.0.0.0
//
#ifndef BSXPCCoding_Protocol_h
#define BSXPCCoding_Protocol_h
@import Foundation;

@protocol BSXPCCoding <NSObject>
/* instance methods */
- (id)initWithXPCDictionary:(id)xpcdictionary;
- (void)encodeWithXPCDictionary:(id)xpcdictionary;
@optional
/* instance methods */
- (Class)fallbackXPCEncodableClass;
@end

#endif /* BSXPCCoding_Protocol_h */
