//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKPopulationNormsChartViewController_h
#define HKPopulationNormsChartViewController_h
@import Foundation;

#include "UIViewController.h"
#include "HKPopulationNormsClassificationCollectionView.h"
#include "HKPopulationNormsDescriptionView.h"
#include "HKPopulationNormsGraphView.h"
#include "HKPopulationNormsViewModelDataSource-Protocol.h"
#include "UICollectionViewDataSource-Protocol.h"
#include "UICollectionViewDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UILabel, UISegmentedControl, UIView;

@interface HKPopulationNormsChartViewController : UIViewController<UICollectionViewDataSource, UICollectionViewDelegate>

@property (retain, nonatomic) NSObject<HKPopulationNormsViewModelDataSource> *viewModel;
@property (retain, nonatomic) UILabel *chartTitleLabel;
@property (retain, nonatomic) UISegmentedControl *biologicalSexSegmentedControl;
@property (retain, nonatomic) HKPopulationNormsGraphView *populationNormsGraphView;
@property (retain, nonatomic) UILabel *classificationLevelsTitleLabel;
@property (retain, nonatomic) HKPopulationNormsClassificationCollectionView *classificationCollectionView;
@property (retain, nonatomic) HKPopulationNormsDescriptionView *classificationDescriptionView;
@property (retain, nonatomic) UILabel *attributionLabel;
@property (retain, nonatomic) NSLayoutConstraint *previousPopulationNormsGraphHeightConstraint;
@property (copy, nonatomic) NSString *baseIdentifier;
@property (readonly, nonatomic) BOOL shouldEmbedInScrollView;
@property (readonly, nonatomic) UIView *contentView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDisplayType:(id)type healthStore:(id)store;
- (id)initWithDisplayType:(id)type healthStore:(id)store shouldEmbedInScrollView:(BOOL)view;
- (void)loadView;
- (void)viewWillAppear:(BOOL)appear;
- (void)viewDidDisappear:(BOOL)disappear;
- (void)traitCollectionDidChange:(id)change;
- (void)updatePopulationNormsGraphHeightWithTraitCollection:(id)collection;
- (void)_refreshViewModelIfNecessary;
- (void)_setupFonts;
- (id)_viewModelForDisplayType:(id)type healthStore:(id)store;
- (void)segmentedControlDidChange:(id)change;
- (long long)collectionView:(id)view numberOfItemsInSection:(long long)section;
- (id)collectionView:(id)view cellForItemAtIndexPath:(id)path;
- (void)collectionView:(id)view didHighlightItemAtIndexPath:(id)path;
- (void)collectionView:(id)view didUnhighlightItemAtIndexPath:(id)path;
- (void)collectionView:(id)view didSelectItemAtIndexPath:(id)path;
- (void)_deselectClassificationCellAtIndexPath:(id)path;
- (void)_selectClassificationCellAtIndexPath:(id)path;
@end

#endif /* HKPopulationNormsChartViewController_h */
