//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKUIConnectedGymIconUtilties_h
#define HKUIConnectedGymIconUtilties_h
@import Foundation;

@interface HKUIConnectedGymIconUtilties : NSObject
/* class methods */
+ (void)initialize;
+ (id)iconForConnectedGymDevice:(id)device preferredIconWidth:(double)width;
@end

#endif /* HKUIConnectedGymIconUtilties_h */
