//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 624.0.100.0.0
//
#ifndef CPLExtractedBatch_h
#define CPLExtractedBatch_h
@import Foundation;

#include "CPLChangeBatch.h"
#include "NSFastEnumeration-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSMutableSet, NSSet, NSString;

@interface CPLExtractedBatch : NSObject<NSSecureCoding> {
  /* instance variables */
  NSDictionary *_pushContexts;
  NSMutableDictionary *_mutablePushContexts;
  NSSet *_untrustableScopedIdentifiers;
  NSMutableSet *_mutableUntrustableScopedIndentifiers;
  BOOL _resourceSizeIsCalculated;
}

@property (readonly, nonatomic) CPLChangeBatch *batch;
@property (readonly, nonatomic) unsigned long long resourceSize;
@property (nonatomic) BOOL full;
@property (readonly, nonatomic) BOOL batchCanLowerQuota;
@property (readonly, nonatomic) NSObject<NSFastEnumeration> *uploadIdentifiers;
@property (copy, nonatomic) NSString *clientCacheIdentifier;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)init;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)uploadIdentifierForChange:(id)change;
- (void)addChange:(id)change fromStorage:(id)storage;
- (unsigned long long)effectiveResourceSizeToUploadUsingStorage:(id)storage;
- (void)forceScopeIndexOnAllRecordsTo:(long long)to;
- (void)enumeratePushContextsWithBlock:(id /* block */)block;
- (BOOL)isFull;
@end

#endif /* CPLExtractedBatch_h */
