//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 10.2.8.0.0
//
#ifndef ASDGatherLogsRequestOptions_h
#define ASDGatherLogsRequestOptions_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSArray, NSString;

@interface ASDGatherLogsRequestOptions : NSObject<NSCopying>

@property (copy, nonatomic) NSString *fileName;
@property (nonatomic) BOOL verbose;
@property (copy, nonatomic) NSArray *urlFilters;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* ASDGatherLogsRequestOptions_h */
