disabled_rules:
  - line_length
  - force_cast
  - comment_spacing
  - private_over_fileprivate
  - vertical_whitespace
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - nesting
  - multiple_closures_with_trailing_closure
  - force_try
  - syntactic_sugar
  - for_where
  - legacy_constant
  - non_optional_string_data_conversion

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment

trailing_whitespace:
  ignores_empty_lines: true

identifier_name:
  min_length:
    warning: 0
    error: 0
  validates_start_with_lowercase: false
  allowed_symbols:
    - _

type_name:
  allowed_symbols:
    - _

file_length:
  warning: 5000
  error: 10000

large_tuple:
  warning: 5
  error: 10

attributes:
  attributes_with_arguments_always_on_line_above: false


custom_rules:
  no_c_style_comment:
    name: "C-Style Comment"
    regex: "(/\\*[\\s\\S]*\\*/)"
    match_kinds:
      - comment
    message: "C-Style comment is not recommended, use '//' instead (Command + / for shortcut)"
    severity: warning
