//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMEPersistentConnectionServerDelegate_Protocol_h
#define HMEPersistentConnectionServerDelegate_Protocol_h
@import Foundation;

@protocol HMEPersistentConnectionServerDelegate <NSObject>
/* instance methods */
- (void)sendUpdatedEvents:(id)events toConnection:(id)connection;
- (void)sendUpdatedCachedEvents:(id)events toConnection:(id)connection;
- (BOOL)shouldAllowEvent:(id)event topic:(id)topic connection:(id)connection;
@end

#endif /* HMEPersistentConnectionServerDelegate_Protocol_h */
