//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef WBSDataCache_Protocol_h
#define WBSDataCache_Protocol_h
@import Foundation;

@protocol WBSDataCache <NSObject>

@property (readonly, nonatomic) BOOL terminating;
@property (weak, nonatomic) NSObject<WBSDataCacheDelegate> *dataCacheDelegate;

/* instance methods */
- (void)setUp;
- (void)savePendingChangesBeforeTearDown;
- (void)reset;
- (id)settingForKey:(id)key;
- (void)setSetting:(id)setting forKey:(id)key;
- (id)requestEntryForKeyString:(id)string;
- (void)getEntryURLForKeyString:(id)string completionHandler:(id /* block */)handler;
- (void)setEntry:(id)entry forKeyString:(id)string completionHandler:(id /* block */)handler;
- (void)removeEntriesForKeyStrings:(id)strings completionHandler:(id /* block */)handler;
- (void)removeEntriesForKeyStringsNotIncludedIn:(id)in completionHandler:(id /* block */)handler;
- (long long)entryStateForKeyString:(id)string;
- (BOOL)isTerminating;
@end

#endif /* WBSDataCache_Protocol_h */
