//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef WBSParsecSearchSportsAttributionExtraCompletionItem_h
#define WBSParsecSearchSportsAttributionExtraCompletionItem_h
@import Foundation;

#include "WBSParsecModel.h"
#include "WBSCompletionListItem-Protocol.h"
#include "WBSParsecImageRepresentation.h"

@class NSString, NSURL;

@interface WBSParsecSearchSportsAttributionExtraCompletionItem : WBSParsecModel<WBSCompletionListItem>

@property (readonly, copy, nonatomic) NSString *label;
@property (readonly, nonatomic) NSURL *url;
@property (readonly, nonatomic) WBSParsecImageRepresentation *imageRepresentation;
@property (readonly, nonatomic) NSString *parsecDomainIdentifier;
@property (readonly, nonatomic) NSString *lastSearchQuery;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)schema;

/* instance methods */
- (id)initWithDictionary:(id)dictionary;
@end

#endif /* WBSParsecSearchSportsAttributionExtraCompletionItem_h */
