//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 297.1.0.0.0
//
#ifndef XBApplicationSnapshotPredicate_h
#define XBApplicationSnapshotPredicate_h
@import Foundation;

#include "BSDescriptionProviding-Protocol.h"
#include "XBDisplayEdgeInsetsWrapper.h"

@class BSMutableSettings, NSString;

@interface XBApplicationSnapshotPredicate : NSObject<BSDescriptionProviding> {
  /* instance variables */
  BSMutableSettings *_clientSettings;
}

@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSString *scheme;
@property (copy, nonatomic) NSString *launchInterfaceIdentifier;
@property (copy, nonatomic) NSString *requiredOSVersion;
@property (nonatomic) unsigned long long interfaceOrientationMask;
@property (nonatomic) struct CGSize { double x0; double x1; } referenceSize;
@property (nonatomic) double imageScale;
@property (nonatomic) unsigned long long contentTypeMask;
@property (nonatomic) unsigned long long statusBarStateMask;
@property (nonatomic) long long userInterfaceStyle;
@property (copy, nonatomic) XBDisplayEdgeInsetsWrapper *customSafeAreaInsets;
@property (nonatomic) BOOL fullScreen;
@property (nonatomic) unsigned long long statusBarState;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)predicate;

/* instance methods */
- (id)init;
- (BOOL)evaluateWithObject:(id)object;
- (BOOL)isFullScreen;
- (void)_setClientObject:(id)object forKey:(unsigned long long)key;
- (void)_removeClientObjectForKey:(unsigned long long)key;
- (BOOL)_hasClientObjectForKey:(unsigned long long)key;
- (id)_clientObjectForKey:(unsigned long long)key;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
@end

#endif /* XBApplicationSnapshotPredicate_h */
