//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2000.2.18.0.0
//
#ifndef ArouetCandidatesResult_h
#define ArouetCandidatesResult_h
@import Foundation;

@class NSArray, NSString;

@interface ArouetCandidatesResult : NSObject {
  /* instance variables */
  NSArray *_candidateTypes;
}

@property (readonly, nonatomic) NSArray *candidateStrings;
@property (readonly, nonatomic) NSString *inputString;
@property (readonly, nonatomic) struct _NSRange { unsigned long long x0; unsigned long long x1; } baseWordRange;
@property (readonly, nonatomic) NSString *baseWord;

/* instance methods */
- (id)initWithCandidateStrings:(id)strings candidateTypes:(id)types inputString:(id)string baseWordRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (long long)candidateTypeAtIndex:(long long)index;
- (id)description;
@end

#endif /* ArouetCandidatesResult_h */
