//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2000.2.18.0.0
//
#ifndef PUICStatusViewImageViewConfiguration_h
#define PUICStatusViewImageViewConfiguration_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSBundle, NSString, UIColor;

@interface PUICStatusViewImageViewConfiguration : NSObject<NSCopying>

@property (copy, nonatomic) NSString *imageName;
@property (retain, nonatomic) NSBundle *bundle;
@property (copy, nonatomic) UIColor *tintColor;
@property (nonatomic) BOOL templated;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isTemplated;
@end

#endif /* PUICStatusViewImageViewConfiguration_h */
