//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2000.2.18.0.0
//
#ifndef PUICSearchSuggestionsViewController_h
#define PUICSearchSuggestionsViewController_h
@import Foundation;

#include "PUICListCollectionViewController.h"

@class UICollectionViewDiffableDataSource;

@interface PUICSearchSuggestionsViewController : PUICListCollectionViewController

@property (retain, nonatomic) UICollectionViewDiffableDataSource *dataSource;

/* instance methods */
- (id)init;
- (id)initWithCollectionViewLayout:(id)layout;
- (void)commonInit;
- (void)appendSuggestions:(id)suggestions toSuggestionGroup:(id)group;
- (void)removeSuggestions:(id)suggestions;
- (double)collectionView:(id)view layout:(id)layout heightForHeaderInSection:(long long)section;
@end

#endif /* PUICSearchSuggestionsViewController_h */
