//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1262.300.81.4.10
//
#ifndef IMWallpaper_h
#define IMWallpaper_h
@import Foundation;

#include "IMWallpaperMetadata.h"
#include "NSSecureCoding-Protocol.h"

@class IMWallpaper_SwiftImpl, NSString;

@interface IMWallpaper : NSObject<NSSecureCoding> {
  /* instance variables */
  IMWallpaper_SwiftImpl *swiftImpl;
}

@property (readonly, copy, nonatomic) NSString *fileName;
@property (readonly, copy, nonatomic) NSString *filePath;
@property (readonly, copy, nonatomic) NSString *lowResFileName;
@property (readonly, copy, nonatomic) NSString *lowResFilePath;
@property (readonly, nonatomic) long long dataVersion;
@property (readonly, nonatomic) BOOL wallpaperExists;
@property (readonly, nonatomic) BOOL lowResWallpaperExists;
@property (readonly, nonatomic) IMWallpaperMetadata *metadata;
@property (readonly, nonatomic) BOOL contentIsSensitive;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithFileName:(id)name filePath:(id)path lowResFileName:(id)name lowResFilePath:(id)path metadata:(id)metadata contentIsSensitive:(BOOL)sensitive;
- (id)initWithFileName:(id)name filePath:(id)path data:(id)data lowResFileName:(id)name lowResFilePath:(id)path lowResData:(id)data metadata:(id)metadata contentIsSensitive:(BOOL)sensitive error:(id *)error;
- (id)initWithDictionaryRepresentation:(id)representation;
- (id)initWithCoder:(id)coder;
- (id)wallpaperData;
- (id)lowResWallpaperData;
- (BOOL)isEqual:(id)equal;
- (id)publicDictionaryRepresentation;
- (id)dictionaryRepresentation;
@end

#endif /* IMWallpaper_h */
