//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 396.4.0.0.0
//
#ifndef TRIExperimentRollbackPushNotification_h
#define TRIExperimentRollbackPushNotification_h
@import Foundation;

#include "TRIPBMessage.h"

@class NSString;

@interface TRIExperimentRollbackPushNotification : TRIPBMessage

@property (copy, @dynamic, nonatomic) NSString *experimentId;
@property (@dynamic, nonatomic) BOOL hasExperimentId;

/* class methods */
+ (id)descriptor;
@end

#endif /* TRIExperimentRollbackPushNotification_h */
