//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2.8.10.0.0
//
#ifndef MTIDScheme_h
#define MTIDScheme_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"

@class NSArray, NSString;

@interface MTIDScheme : NSObject<NSSecureCoding>

@property (copy, nonatomic) NSString *idNamespace;
@property (nonatomic) long long idType;
@property (nonatomic) long long rotationSchedule;
@property (nonatomic) long long lifespan;
@property (copy, nonatomic) NSArray *correlations;
@property (copy, nonatomic) NSString *version;
@property (copy, nonatomic) NSString *containerIdentifier;
@property (nonatomic) unsigned long long localHash;
@property (nonatomic) unsigned long long correlationHash;
@property (copy, nonatomic) NSArray *topics;
@property (nonatomic) BOOL isDefault;
@property (readonly, nonatomic) unsigned long long storagePoolSize;
@property (readonly, nonatomic) double maxFutureTimeInterval;
@property (readonly, nonatomic) double maxPastTimeInterval;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithNamespace:(id)namespace options:(id)options;
- (id)initWithNamespace:(id)namespace type:(long long)type;
- (void)overrideLifespanMaybe;
- (id)description;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (unsigned long long)calculateHash;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* MTIDScheme_h */
