//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef _TtC9PassKitUI13UIFlowManager_PassKitUI_h
#define _TtC9PassKitUI13UIFlowManager_PassKitUI_h
@import Foundation;

@interface PassKitUI.UIFlowManager (PassKitUI) <PKUIFlowManagerRendererDelegate>
/* instance methods */
- (void)rendererDidRunOutOfContentWithRenderer:(id)renderer;
- (void)rendererDidDisappearWithRenderer:(id)renderer;
@end

#endif /* _TtC9PassKitUI13UIFlowManager_PassKitUI_h */
