//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef PKApplyTermsVerifyingViewController_h
#define PKApplyTermsVerifyingViewController_h
@import Foundation;

#include "PKExplanationViewController.h"
#include "PKApplyController.h"
#include "PKPaymentSetupViewControllerDelegate-Protocol.h"

@class CLInUseAssertion, NSSet, PKApplyRequiredFieldsPage;

@interface PKApplyTermsVerifyingViewController : PKExplanationViewController {
  /* instance variables */
  PKApplyController *_applyController;
  NSSet *_termsIdentifiers;
  NSObject<PKPaymentSetupViewControllerDelegate> *_setupDelegate;
  BOOL _isProcessingTerms;
  unsigned long long _featureIdentifier;
  CLInUseAssertion *_inUseAssertion;
  PKApplyRequiredFieldsPage *_applyPage;
}

/* instance methods */
- (id)initWithController:(id)controller setupDelegate:(id)delegate context:(long long)context termsIdentifiers:(id)identifiers applyPage:(id)page;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)appear;
- (void)viewWillDisappear:(BOOL)disappear;
- (void)_processTerms;
- (void)_showActivationSpinner:(BOOL)spinner;
- (void)_terminateSetupFlow;
- (id)analyticsPageTag;
@end

#endif /* PKApplyTermsVerifyingViewController_h */
