//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef PKContinuousButton_h
#define PKContinuousButton_h
@import Foundation;

#include "UIButton.h"
#include "PKLegacyButtonInterface-Protocol.h"

@class CAFilter, CAShapeLayer, NSMutableSet, NSString, UIActivityIndicatorView, UIColor, UIImage, _UIBackdropView;

@interface PKContinuousButton : UIButton<PKLegacyButtonInterface> {
  /* instance variables */
  struct { double cornerRadius; long long shape; long long style; long long highlightEffect; long long disabledEffect; } _configuration;
  UIImage *_image;
  NSMutableSet *_disabledImageStates;
  UIColor *_overrideBackgroundColor;
  UIColor *_overrideTitleColor;
  CAFilter *_highlightFilter;
  UIColor *_normalInputColor;
  UIColor *_highlightInputColor;
  UIColor *_selectedInputColor;
  UIColor *_disabledInputColor;
  UIColor *_appliedInputColor;
  CAShapeLayer *_layer;
  _UIBackdropView *_backdropView;
  long long _backdropStyle;
  BOOL _updatingBackdropSettings;
  BOOL _highlighted;
  BOOL _selected;
  BOOL _enabled;
  struct CGSize { double width; double height; } _boundsSize;
  UIActivityIndicatorView *_activityIndicatorView;
  UIColor *_activityIndicatorColor;
}

@property (nonatomic) BOOL blurDisabled;
@property (nonatomic) BOOL showSpinner;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (Class)layerClass;
+ (id)_filterInputColorForEffect:(long long)effect;

/* instance methods */
- (id)pk_childrenForAppearance;
- (void)pk_applyAppearance:(id)appearance;
- (id)initWithCoder:(id)coder;
- (id)init;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (id)initWithCornerRadius:(double)radius effect:(long long)effect;
- (id)initWithConfiguration:(struct { double x0; long long x1; long long x2; long long x3; long long x4; })configuration;
- (void)dealloc;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (void)tintColorDidChange;
- (void)_dynamicUserInterfaceTraitDidChange;
- (void)layoutSubviews;
- (void)updateBackgroundColorWithColor:(id)color;
- (void)updateTitleColorWithColor:(id)color;
- (void)updateActivityIndicatorColorWithColor:(id)color;
- (void)updateWithImage:(id)image;
- (void)setImageEnabled:(BOOL)enabled forState:(unsigned long long)state;
- (void)updateImageView;
- (void)_updateBackdropSettings;
- (void)_accessibilitySettingsDidChange:(id)change;
- (void)_updateColor;
- (void)_updateTitleColor;
- (void)_createHighlightFilterIfNecessary;
- (void)setEnabled:(BOOL)enabled;
- (void)setHighlighted:(BOOL)highlighted;
- (void)setSelected:(BOOL)selected;
- (void)_updateFilter;
@end

#endif /* PKContinuousButton_h */
