//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef PKDashboardPaymentTransactionItemPresenter_h
#define PKDashboardPaymentTransactionItemPresenter_h
@import Foundation;

#include "PKDashboardItemPresenter-Protocol.h"
#include "PKPaymentTransactionCollectionViewCell.h"
#include "PKPaymentTransactionDetailsFactory.h"
#include "PKPaymentTransactionIconGenerator.h"

@class NSString, PKContactResolver, PKPaymentDefaultDataProvider, UIFont, UIImage;
@protocol PKPaymentTransactionDetailViewControllerDeleteOverrider;

@interface PKDashboardPaymentTransactionItemPresenter : NSObject<PKDashboardItemPresenter> {
  /* instance variables */
  unsigned long long _context;
  PKPaymentDefaultDataProvider *_dataProvider;
  PKPaymentTransactionIconGenerator *_iconGenerator;
  UIFont *_transactionCellPrimaryLabelFont;
  UIFont *_transactionCellPrimaryLabelPeerPaymentFont;
  UIFont *_transactionCellValueLabelFont;
  UIFont *_transactionCellValueLabelPeerPaymentFont;
  UIFont *_transactionCellSecondaryLabelFont;
  UIFont *_transactionCellSecondaryLabelPeerPaymentFont;
  UIImage *_emptyImage;
  UIImage *_cashbackImage;
  UIImage *_appleCardImage;
  PKPaymentTransactionDetailsFactory *_transactionDetailsFactory;
  PKPaymentTransactionCollectionViewCell *_sampleCell;
  BOOL _useAccessibilityLayout;
}

@property (retain, nonatomic) PKContactResolver *contactResolver;
@property (retain, nonatomic) NSObject<PKPaymentTransactionDetailViewControllerDeleteOverrider> *deleteOverrider;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithContext:(unsigned long long)context detailViewStyle:(long long)style;
- (id)_contactKeysToFetch;
- (Class)itemClass;
- (id)collectionViewCellClasses;
- (void)traitCollectionDidChangeFromTrait:(id)trait toTrait:(id)trait inCollectionView:(id)view;
- (BOOL)canSelectItem:(id)item inCollectionView:(id)view atIndexPath:(id)path;
- (void)didSelectItem:(id)item inCollectionView:(id)view atIndexPath:(id)path navigationController:(id)controller canPresent:(id /* block */)present;
- (id)cellForItem:(id)item inCollectionView:(id)view atIndexPath:(id)path;
- (struct CGSize { double x0; double x1; })sizeForItem:(id)item inCollectionView:(id)view atIndexPath:(id)path;
- (void)updateCell:(id)cell forItem:(id)item inCollectionView:(id)view atIndexPath:(id)path;
- (void)prefetchForItem:(id)item inCollectionView:(id)view;
- (BOOL)hideSeparatorForItem:(id)item inCollectionView:(id)view;
- (void)viewControllerForTransaction:(id)transaction transactionSourceCollection:(id)collection familyCollection:(id)collection account:(id)account accountUserCollection:(id)collection physicalCards:(id)cards forcePreventHistory:(BOOL)history completion:(id /* block */)completion;
- (BOOL)_shouldShowIconForTransactionSource:(id)source transaction:(id)transaction context:(unsigned long long)context;
- (void)_configureCell:(id)cell forItem:(id)item inCollectionView:(id)view forIndexPath:(id)path;
- (void)_updateAvatarOnTransactionCell:(id)cell withTransaction:(id)transaction contact:(id)contact;
- (void)_updatePrimaryLabelOnTransactionCell:(id)cell withPeerPaymentCounterpartHandle:(id)handle contact:(id)contact;
- (struct CGSize { double x0; double x1; })_imageSize;
- (id)cashbackImage;
- (id)appleCardImage;
@end

#endif /* PKDashboardPaymentTransactionItemPresenter_h */
