//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef PKPassShareEntitlementSelectionViewController_h
#define PKPassShareEntitlementSelectionViewController_h
@import Foundation;

#include "PKPaymentSetupOptionsViewController.h"
#include "PKPassEntitlementSelectionSectionController.h"
#include "PKPassEntitlementSelectionSectionControllerDelegate-Protocol.h"
#include "PKPassEntitlementTimeSectionController.h"
#include "PKPassEntitlementTimeSectionControllerDelegate-Protocol.h"
#include "PKPassShareTimeLimitViewControllerDelegate-Protocol.h"

@class NSString, PKPassEntitlementsComposer;

@interface PKPassShareEntitlementSelectionViewController : PKPaymentSetupOptionsViewController<PKPassEntitlementSelectionSectionControllerDelegate, PKPassEntitlementTimeSectionControllerDelegate, PKPassShareTimeLimitViewControllerDelegate> {
  /* instance variables */
  unsigned long long _mode;
  PKPassEntitlementsComposer *_entitlementComposer;
  PKPassEntitlementSelectionSectionController *_entitlementSectionController;
  PKPassEntitlementTimeSectionController *_timeSectionController;
  BOOL _isShowingMyEntitlements;
}

@property (nonatomic) BOOL showDoneButton;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithMyEntitlements:(id)entitlements;
- (id)initWithMode:(unsigned long long)mode entitlementComposer:(id)composer maxEntitlementSelectionCount:(unsigned long long)count;
- (id)_initWithMode:(unsigned long long)mode entitlementComposer:(id)composer maxEntitlementSelectionCount:(unsigned long long)count isShowingMyEntitlements:(BOOL)entitlements;
- (void)loadView;
- (void)viewWillAppear:(BOOL)appear;
- (void)_dismissButtonPressed;
- (void)_reloadSections:(BOOL)sections;
- (void)entitlementSelectionDidChange;
- (void)showAdvancedScheduleSelectionFlowForEntitlementEntry:(id)entry;
- (void)didTapPassEntitlementTimeSectionController:(id)controller;
@end

#endif /* PKPassShareEntitlementSelectionViewController_h */
