//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef PKServiceAddPassesViewController_h
#define PKServiceAddPassesViewController_h
@import Foundation;

#include "PKNavigationController.h"
#include "PKAddPassesCardStackViewController.h"
#include "PKAddPassesCardStackViewControllerDelegate-Protocol.h"
#include "PKIssuerBindingViewController.h"
#include "PKIssuerBindingViewControllerDelegate-Protocol.h"
#include "PKServiceAddPassesViewControllerProtocol-Protocol.h"
#include "PKServiceAddPassesViewControllerResultsDelegate-Protocol.h"

@class NSString;

@interface PKServiceAddPassesViewController : PKNavigationController<PKAddPassesCardStackViewControllerDelegate, PKIssuerBindingViewControllerDelegate, PKServiceAddPassesViewControllerProtocol> {
  /* instance variables */
  struct CGSize { double width; double height; } _screenSize;
  double _screenScale;
  BOOL _placeholderViewControllerDidCancel;
  PKAddPassesCardStackViewController *_cardStackViewController;
  PKIssuerBindingViewController *_issuerBindingViewController;
}

@property (weak, nonatomic) NSObject<PKServiceAddPassesViewControllerResultsDelegate> *resultsDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (BOOL)_preventsAppearanceProxyCustomization;
+ (id)_exportedInterface;
+ (id)_remoteViewControllerInterface;

/* instance methods */
- (id)init;
- (unsigned long long)supportedInterfaceOrientations;
- (BOOL)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (void)dealloc;
- (void)addPassesCardStackViewController:(id)controller didFinishAddingPasses:(id)passes;
- (void)addPassesCardStackViewController:(id)controller didCancelAddingPasses:(id)passes;
- (void)issuerBindingViewController:(id)controller didFinishWithPassesData:(id)data;
- (void)issuerBindingViewControllerDidCancel:(id)cancel;
- (void)setDisplayPropertiesWithScreenSize:(struct CGSize { double x0; double x1; })size scale:(double)scale;
- (void)ingestPasses:(id)passes orPassesContainer:(id)container orIssuerData:(id)data withSignature:(id)signature fromPresentationSource:(unsigned long long)source;
- (void)_dismissDelayed;
- (void)_setUpCardStackViewControllerWithPassDataArray:(id)array orPassesContainer:(id)container fromPresentationSource:(unsigned long long)source shouldPushController:(BOOL)controller;
- (void)_setUpIssuerBindingViewControllerWithData:(id)data signature:(id)signature fromPresentationSource:(unsigned long long)source;
- (void)_ingestionDidFinishWithResult:(unsigned long long)result;
- (void)evaluateBrightness;
- (void)resetBrightness;
- (void)_beginReportingIfNecessary;
- (void)_endReportingIfNecessary;
@end

#endif /* PKServiceAddPassesViewController_h */
