//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1552.3.6.1.1
//
#ifndef PKSubcredentialInvitationFlowControllerProtocol_Protocol_h
#define PKSubcredentialInvitationFlowControllerProtocol_Protocol_h
@import Foundation;

@protocol PKSubcredentialInvitationFlowControllerProtocol <PKSubcredentialProvisioningFlowController>
/* instance methods */
- (id)localDeviceProvisioningViewModelForOperation:(id)operation;
- (id)remoteDeviceProvisioningViewModelForOperation:(id)operation;
- (id)alertForOperation:(id)operation withError:(id)error retryHandler:(id /* block */)handler cancelationHandler:(id /* block */)handler;
@end

#endif /* PKSubcredentialInvitationFlowControllerProtocol_Protocol_h */
