//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 887.3.0.0.0
//
#ifndef BBXPCPersistentStore_h
#define BBXPCPersistentStore_h
@import Foundation;

#include "BBPersistentStoreInterface-Protocol.h"

@class NSString, NSXPCConnection;
@protocol OS_dispatch_queue;

@interface BBXPCPersistentStore : NSObject<BBPersistentStoreInterface> {
  /* instance variables */
  NSObject<OS_dispatch_queue> *_connectionQueue;
  NSXPCConnection *_settingsPersistenceConnection;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)_ensureSettingsPersistenceConnection;
- (void)_resetSettingsPersistenceConnection;
- (void)deleteSectionInfoFile;
- (void)deleteSectionInfoLegacyFile;
- (BOOL)hasSectionInfoLegacyFile;
- (id)readClearedSections;
- (id)readSectionInfo;
- (id)readSectionInfoLegacy;
- (id)readSectionOrder;
- (void)writeClearedSections:(id)sections;
- (void)writeSectionInfo:(id)info;
- (void)writeSectionOrder:(id)order;
- (id)readSectionInfoWithVersionNumberForMigration;
- (long long)effectiveGlobalAnnounceCarPlaySetting;
- (void)setGlobalAnnounceCarPlaySetting:(long long)setting;
- (long long)effectiveGlobalAnnounceHeadphonesSetting;
- (void)setGlobalAnnounceHeadphonesSetting:(long long)setting;
- (long long)effectiveGlobalAnnounceSetting;
- (void)setGlobalAnnounceSetting:(long long)setting;
- (long long)effectiveGlobalContentPreviewsSetting;
- (void)setGlobalContentPreviewsSetting:(long long)setting;
- (long long)effectiveGlobalNotificationListDisplayStyleSetting;
- (void)setGlobalNotificationListDisplayStyleSetting:(long long)setting;
- (long long)effectiveGlobalScheduledDeliverySetting;
- (void)setGlobalScheduledDeliverySetting:(long long)setting;
- (long long)effectiveGlobalScheduledDeliveryShowNextSummarySetting;
- (void)setGlobalScheduledDeliveryShowNextSummarySetting:(long long)setting;
- (id)effectiveGlobalScheduledDeliveryTimes;
- (void)setGlobalScheduledDeliveryTimes:(id)times;
@end

#endif /* BBXPCPersistentStore_h */
