//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1936.30.51.4.2
//
#ifndef SHSheetActivityPerformerDelegate_Protocol_h
#define SHSheetActivityPerformerDelegate_Protocol_h
@import Foundation;

@protocol SHSheetActivityPerformerDelegate <NSObject>
/* instance methods */
- (id)linkMetadataForActivityPerformer:(id)performer;
- (id)collaborationServiceForActivityPerformer:(id)performer;
@end

#endif /* SHSheetActivityPerformerDelegate_Protocol_h */
