//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1880.5.0.0.0
//
#ifndef FIUIChartPointNumeric_h
#define FIUIChartPointNumeric_h
@import Foundation;

#include "FIUIChartPoint-Protocol.h"

@class NSDate, NSNumber, NSString;

@interface FIUIChartPointNumeric : NSObject<FIUIChartPoint>

@property (copy, nonatomic) NSNumber *yValue;
@property (copy, nonatomic) NSDate *xValue;
@property (readonly, nonatomic) NSNumber *minYValue;
@property (readonly, nonatomic) NSNumber *maxYValue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)chartPointWithXValue:(id)xvalue yValue:(id)value;

/* instance methods */
- (id)initWithXValue:(id)xvalue yValue:(id)value;
@end

#endif /* FIUIChartPointNumeric_h */
