//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1226.2.2.1.0
//
#ifndef HVPBContentState_h
#define HVPBContentState_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"

@class NSMutableArray;

@interface HVPBContentState : PBCodable<NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 levelOfService; } _has;
}

@property (retain, nonatomic) NSMutableArray *consumers;
@property (nonatomic) BOOL hasLevelOfService;
@property (nonatomic) int levelOfService;

/* class methods */
+ (Class)consumersType;

/* instance methods */
- (void)clearConsumers;
- (void)addConsumers:(id)consumers;
- (unsigned long long)consumersCount;
- (id)consumersAtIndex:(unsigned long long)index;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* HVPBContentState_h */
