//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 47.1.0.0.0
//
#ifndef RPTResizeTestParameters_h
#define RPTResizeTestParameters_h
@import Foundation;

#include "RPTCoordinateSpaceConverter.h"
#include "RPTTestParameters-Protocol.h"
#include "_RPTCoordinateSpaces-Protocol.h"

@class NSString, UIWindow;

@interface RPTResizeTestParameters : NSObject<_RPTCoordinateSpaces, RPTTestParameters>

@property (copy, nonatomic) NSString *testName;
@property (retain, nonatomic) UIWindow *window;
@property (nonatomic) struct CGSize { double x0; double x1; } minimumWindowSize;
@property (nonatomic) struct CGSize { double x0; double x1; } maximumWindowSize;
@property (copy, nonatomic) id /* block */ completionHandler;
@property (retain, nonatomic) RPTCoordinateSpaceConverter *conversion;
@property (readonly, nonatomic) BOOL managesTestStartAndEnd;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)prepareWithComposer:(id)composer;
- (id)initWithTestName:(id)name window:(id)window completionHandler:(id /* block */)handler;
- (id /* block */)composerBlock;
@end

#endif /* RPTResizeTestParameters_h */
