//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 85.0.0.0.0
//
#ifndef FFFileWriter_Protocol_h
#define FFFileWriter_Protocol_h
@import Foundation;

@protocol FFFileWriter 
/* instance methods */
- (BOOL)writeData:(id)data toFile:(id)file error:(id *)error;
- (BOOL)createDirectoryAtURL:(id)url error:(id *)error;
@end

#endif /* FFFileWriter_Protocol_h */
