//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3302.21.3.0.0
//
#ifndef KVItem_CESRSpeechProfileBuilder_h
#define KVItem_CESRSpeechProfileBuilder_h
@import Foundation;

@class NSLocale, NSMutableArray, NSString, NSURL, NSXPCConnection;

@interface KVItem (CESRSpeechProfileBuilder)
/* instance methods */
- (void)setIsBoosted:(BOOL)boosted;
- (BOOL)isBoosted;
@end

#endif /* KVItem_CESRSpeechProfileBuilder_h */
