//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1852.4.7.0.3
//
#ifndef NSNumber__DKDeduping_h
#define NSNumber__DKDeduping_h
@import Foundation;

@interface NSNumber (_DKDeduping) <_DKDeduping>
/* instance methods */
- (id)dk_dedup;
- (id)dedup;
@end

#endif /* NSNumber__DKDeduping_h */
