//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 141.1.1.0.0
//
#ifndef _EXExtensionIdentity_h
#define _EXExtensionIdentity_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"
#include "_EXExtensionConfigurationProviding-Protocol.h"
#include "_EXExtensionRepresenting-Protocol.h"

@class ISIcon, LSApplicationExtensionRecord, LSBundleRecord, NSArray, NSDictionary, NSString, NSURL, NSUUID;

@interface _EXExtensionIdentity : NSObject<_EXExtensionConfigurationProviding, NSSecureCoding, _EXExtensionRepresenting>

@property (readonly) NSDictionary *extensionPointConfiguration;
@property (readonly) unsigned long long type;
@property (readonly) NSString *internalServiceName;
@property (readonly) NSString *serviceName;
@property (readonly, @dynamic) Class principalClass;
@property (readonly, @dynamic) Class extensionClass;
@property (readonly) BOOL presentsUserInterface;
@property (readonly, @dynamic) Class connectionHandlerClass;
@property (readonly) Class extensionContextClass;
@property (readonly, @dynamic) NSDictionary *requiredHostEntitlements;
@property (readonly, @dynamic) BOOL supportsNSExtensionPlistKeys;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, @dynamic) NSDictionary *entitlements;
@property (readonly, @dynamic) BOOL systemComponent;
@property (readonly, @dynamic) NSURL *containingURL;
@property (readonly, @dynamic) NSUUID *UUID;
@property (readonly, @dynamic) NSURL *executableURL;
@property (readonly, @dynamic) NSDictionary *sdkDictionary;
@property (readonly, @dynamic) NSDictionary *extensionDictionary;
@property (readonly, @dynamic) unsigned int platform;
@property (readonly, @dynamic) unsigned char userElection;
@property (readonly, @dynamic) unsigned char defaultUserElection;
@property (readonly, @dynamic) NSString *sandboxProfileName;
@property (readonly, @dynamic) NSArray *alternateSandboxProfileNames;
@property (readonly, @dynamic) BOOL hasSandboxEntitlement;
@property (readonly, @dynamic) BOOL disableLaunchdCheckinTimeout;
@property (readonly, @dynamic) BOOL performsUserInteractiveWork;
@property (readonly, @dynamic) BOOL requiresMultiInstance;
@property (readonly, @dynamic) NSObject<_EXExtensionConfigurationProviding> *configuration;
@property (readonly, @dynamic) Class extensionContextClass;
@property (readonly, @dynamic) Class hostContextClass;
@property (readonly, @dynamic) unsigned long long enablementState;
@property (readonly, @dynamic) NSString *extensionPointIdentifier;
@property (readonly, @dynamic) NSString *bundleIdentifier;
@property (readonly, @dynamic) NSString *bundleVersion;
@property (readonly, @dynamic) LSBundleRecord *containingBundleRecord;
@property (readonly, @dynamic) LSApplicationExtensionRecord *applicationExtensionRecord;
@property (readonly, @dynamic) NSURL *url;
@property (readonly, @dynamic) NSUUID *uniqueIdentifier;
@property (readonly, @dynamic) NSString *localizedName;
@property (readonly, @dynamic) BOOL presentsUserInterface;
@property (readonly, @dynamic) BOOL requiresMacCatalystBehavior;
@property (readonly, @dynamic) BOOL requiresSceneHosting;
@property (readonly, @dynamic) NSDictionary *attributes;
@property (readonly, @dynamic) NSDictionary *nsExtensionAttributes;
@property (readonly, @dynamic) NSArray *roles;
@property (readonly, @dynamic) ISIcon *icon;
@property (readonly, @dynamic) BOOL requiresLegacyInfrastructure;
@property (readonly, @dynamic) BOOL enabled;
@property (readonly, @dynamic) BOOL unelected;
@property (readonly, @dynamic) BOOL showsInExtensionsManager;
@property (readonly, @dynamic) BOOL canDisable;
@property (readonly, @dynamic) BOOL targetsSystemExtensionPoint;
@property (readonly, @dynamic) BOOL requiresHostToBeContainerApp;
@property (readonly, @dynamic) BOOL spotlightIndexable;
@property (readonly, @dynamic) NSArray *spotlightImporterIdentifiers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)allocWithZone:(struct _NSZone *)zone;
+ (BOOL)supportsSecureCoding;
+ (BOOL)enableExtension:(id)extension error:(id *)error;
+ (BOOL)disableExtension:(id)extension error:(id *)error;

/* instance methods */
- (id)xpcOverlayDictionaryOverridingSandboxProfileName:(id)name multiInstance:(BOOL)instance arguments:(id)arguments additionalEnvironment:(id)environment;
- (id)_executableURLWithError:(id *)error;
- (id)_init;
- (id)initWithPlugInKitProxy:(id)proxy;
- (id)initWithApplicationExtensionRecord:(id)record;
- (id)initWithServiceIdentifier:(id)identifier error:(id *)error;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (BOOL)isEqualToExtension:(id)extension;
- (BOOL)isEqual:(id)equal;
- (id)entitlementNamed:(id)named ofClass:(Class)class;
- (id)makeXPCConnectionWithError:(id *)error;
- (BOOL)isSystemComponent;
@end

#endif /* _EXExtensionIdentity_h */
