//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2.2.1.0.0
//
#ifndef LCFDatabaseColumn_h
#define LCFDatabaseColumn_h
@import Foundation;

@class NSString;

@interface LCFDatabaseColumn : NSObject

@property (readonly, nonatomic) NSString *name;
@property (readonly, nonatomic) NSString *typeDb;
@property (readonly, nonatomic) long long type;

/* instance methods */
- (id)init:(id)init typeDb:(id)db;
@end

#endif /* LCFDatabaseColumn_h */
