//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3302.3.1.0.0
//
#ifndef KVDonateXPCClientFactory_h
#define KVDonateXPCClientFactory_h
@import Foundation;

#include "KVDonateServiceProvider-Protocol.h"
#include "KVDonateVersionLog.h"

@class NSString;

@interface KVDonateXPCClientFactory : NSObject<KVDonateServiceProvider> {
  /* instance variables */
  KVDonateVersionLog *_versionLog;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)initWithQueue:(id)queue;
- (id)makeConnection:(id)connection;
- (void)terminateConnection:(id)connection;
- (id)versionLog;
@end

#endif /* KVDonateXPCClientFactory_h */
