//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 25.300.51.0.0
//
#ifndef SKAChannelManagingDelegate_Protocol_h
#define SKAChannelManagingDelegate_Protocol_h
@import Foundation;

@protocol SKAChannelManagingDelegate <NSObject>
/* instance methods */
- (void)channelManager:(id)manager didReceiveData:(id)data onChannel:(id)channel identifier:(unsigned long long)identifier dateReceived:(id)received dateExpired:(id)expired;
- (void)channelManager:(id)manager failedToSubscribeToChannel:(id)channel withError:(id)error;
@end

#endif /* SKAChannelManagingDelegate_Protocol_h */
