//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1431.300.81.0.0
//
#ifndef TUContactsDataProvider_h
#define TUContactsDataProvider_h
@import Foundation;

#include "TUContactsDataProviderAppleCareHandles.h"
#include "TUContactsDataSource-Protocol.h"

@interface TUContactsDataProvider : NSObject

@property (nonatomic) BOOL useFamilyNameFirst;
@property (copy, nonatomic) id /* block */ localeSupportsPrefixHintForFetchRequest;
@property (readonly, nonatomic) NSObject<TUContactsDataSource> *contactsDataSource;
@property (copy, nonatomic) TUContactsDataProviderAppleCareHandles *appleCareHandles;
@property (nonatomic) BOOL useGivenName;

/* class methods */
+ (id)keysByCombiningDefaultKeysWithKeysToFetch:(id)fetch;
+ (id)numberFormatter;
+ (id)defaultContactKeyDescriptors;
+ (id)unsupportedLocalesForPrefixHint;
+ (id)familyNameFirstLocaleCountryCodes;

/* instance methods */
- (id)init;
- (id)initWithContactsDataSource:(id)source;
- (id)processBatchFetchRequests:(id)requests;
- (id)executeBatchFetchRequests:(id)requests;
- (id)executeFetchRequest:(id)request;
- (id)resultForSingleHandleFetchRequest:(id)request fetchedContacts:(id)contacts;
- (id)contactLabelForContacts:(id)contacts matchingHandle:(id)handle countryCode:(id)code;
- (id)labeledHandlesForContactWithIdentifier:(id)identifier;
- (id)labeledHandlesForContacts:(id)contacts;
- (id)contactWithIdentifier:(id)identifier keysToFetch:(id)fetch;
- (id)unifiedContactsForFetchRequest:(id)request;
- (id)contactsForHandle:(id)handle countryCode:(id)code keysToFetch:(id)fetch prefixHint:(id)hint;
- (id)nameForContact:(id)contact;
- (id)localizedCompositeNameForContact:(id)contact secondContact:(id)contact;
- (id)compositeNameForContacts:(id)contacts;
- (id)compositeNameForFetchRequest:(id)request;
- (id)formattedNameForHandle:(id)handle countryCode:(id)code;
- (BOOL)shouldIgnoreHandle:(id)handle withFetchRequest:(id)request;
- (int)personIDForContact:(id)contact;
- (id)prefixHintForFetchRequest:(id)request;
- (id)ISOCountryCodeForHandle:(id)handle fetchRequest:(id)request;
- (BOOL)shouldUseGivenName;
- (BOOL)shouldUseFamilyNameFirst;
@end

#endif /* TUContactsDataProvider_h */
