//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1431.300.81.0.0
//
#ifndef TUJoinConversationRequest_h
#define TUJoinConversationRequest_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "TUConversationActivity.h"
#include "TUConversationLink.h"
#include "TUConversationParticipantAssociation.h"
#include "TUConversationProvider.h"
#include "TUFilteredRequest-Protocol.h"
#include "TUHandle.h"

@class NSDictionary, NSSet, NSString, NSURL, NSUUID;

@interface TUJoinConversationRequest : NSObject<TUFilteredRequest, NSCopying, NSSecureCoding>

@property (retain, nonatomic) TUHandle *callerID;
@property (copy, nonatomic) NSUUID *messagesGroupUUID;
@property (copy, nonatomic) NSString *messagesGroupName;
@property (nonatomic) BOOL showUIPrompt;
@property (nonatomic) BOOL uplinkMuted;
@property (nonatomic) unsigned long long avMode;
@property (nonatomic) unsigned long long presentationMode;
@property (retain, nonatomic) NSString *collaborationIdentifier;
@property (nonatomic) BOOL video;
@property (nonatomic) BOOL sendLetMeInRequest;
@property (nonatomic) BOOL joiningConversationWithLink;
@property (copy, nonatomic) NSSet *invitationPreferences;
@property (readonly, copy, nonatomic) NSDictionary *notificationStylesByHandleType;
@property (copy, nonatomic) TUConversationParticipantAssociation *participantAssociation;
@property (copy, nonatomic) NSSet *remoteMembers;
@property (nonatomic) BOOL hostedOnCurrentDevice;
@property (nonatomic) BOOL endpointOnCurrentDevice;
@property (nonatomic) BOOL prefersAddingRemoteMembersAfterHandoff;
@property (readonly, nonatomic) BOOL hasAnySiriDisplayNames;
@property (readonly, nonatomic) BOOL isOneToOne;
@property (readonly, copy, nonatomic) NSSet *otherInvitedHandles;
@property (copy, nonatomic) NSString *audioSourceIdentifier;
@property (retain, nonatomic) NSUUID *UUID;
@property (nonatomic) BOOL videoEnabled;
@property (nonatomic) BOOL shouldSuppressInCallUI;
@property (nonatomic) BOOL wantsStagingArea;
@property (copy, nonatomic) TUConversationLink *conversationLink;
@property (retain, nonatomic) TUConversationActivity *activity;
@property (nonatomic) BOOL shouldLaunchBackgroundInCallUI;
@property (readonly, nonatomic) NSURL *URL;
@property (nonatomic) BOOL sendToScreening;
@property (retain, nonatomic) TUConversationProvider *provider;
@property (nonatomic) int originatingUIType;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)remoteMembersFromURLComponents:(id)urlcomponents;
+ (id)otherInvitedHandlesFromURLComponents:(id)urlcomponents;
+ (BOOL)videoEnabledFromURLComponents:(id)urlcomponents;
+ (BOOL)uplinkMutedFromURLComponents:(id)urlcomponents;
+ (BOOL)videoFromURLComponents:(id)urlcomponents;
+ (BOOL)shouldSuppressInCallUIFromURLComponents:(id)urlcomponents;
+ (BOOL)wantsStagingAreaFromURLComponents:(id)urlcomponents;
+ (BOOL)sendToScreeningFromURLComponents:(id)urlcomponents;
+ (id)conversationLinkFromURLComponents:(id)urlcomponents;
+ (id)callerIDFromURLComponents:(id)urlcomponents;
+ (id)messagesGroupUUIDFromURLComponents:(id)urlcomponents;
+ (id)uuidFromURLComponents:(id)urlcomponents;
+ (id)messagesGroupNameFromURLComponents:(id)urlcomponents;
+ (BOOL)showUIPromptFromURLComponents:(id)urlcomponents;
+ (BOOL)sendLetMeInRequestFromURLComponents:(id)urlcomponents;
+ (BOOL)joiningConversationWithLinkFromURLComponents:(id)urlcomponents;
+ (id)audioSourceIdentifierFromURLComponents:(id)urlcomponents;
+ (int)originatingUITypeFromURLComponents:(id)urlcomponents;
+ (id)collaborationIdentifierFromURLComponents:(id)urlcomponents;
+ (id)invitationPreferencesFromURLComponents:(id)urlcomponents;
+ (id)providerFromURLComponents:(id)urlcomponents;
+ (unsigned long long)avModeFromURLComponents:(id)urlcomponents;
+ (unsigned long long)presentationModeFromURLComponents:(id)urlcomponents;
+ (id)sanitizedMembersFromMembers:(id)members;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithProvider:(id)provider remoteMemberHandles:(id)handles;
- (id)initWithProvider:(id)provider remoteMembers:(id)members otherInvitedHandles:(id)handles;
- (id)initWithRemoteMembers:(id)members;
- (id)initWithRemoteMembers:(id)members otherInvitedHandles:(id)handles;
- (id)initWithConversation:(id)conversation;
- (id)initWithConversationLink:(id)link otherInvitedHandles:(id)handles sendLetMeInRequest:(BOOL)request;
- (id)initWithConversationLink:(id)link otherInvitedHandles:(id)handles remoteMembers:(id)members sendLetMeInRequest:(BOOL)request;
- (id)initWithURL:(id)url;
- (id)initWithGroupUUID:(id)uuid localParticipantHandle:(id)handle remoteParticipantHandles:(id)handles;
- (id)initWithUserActivity:(id)activity;
- (BOOL)isEqual:(id)equal;
- (BOOL)isEqualToRequest:(id)request;
- (id)bundleIdentifier;
- (id)handles;
- (id)contactNamesByHandleWithContactsDataSource:(id)source;
- (BOOL)supportsAVMode:(unsigned long long)avmode;
- (BOOL)isVideo;
- (BOOL)isVideoEnabled;
- (id)queryItems;
- (id)remoteMembersQueryItem;
- (id)otherInvitedHandlesQueryItem;
- (id)videoEnabledQueryItem;
- (id)uplinkMutedQueryItem;
- (id)videoQueryItem;
- (id)shouldSuppressInCallUIQueryItem;
- (id)wantsStagingAreaQueryItem;
- (id)conversationLinkQueryItem;
- (id)callerIDQueryItem;
- (id)messagesGroupUUIDQueryItem;
- (id)uuidQueryItem;
- (id)messagesGroupNameQueryItem;
- (id)showUIPromptQueryItem;
- (id)sendLetMeInRequestQueryItem;
- (id)joiningConversationWithLinkQueryItem;
- (id)audioSourceIdentifierQueryItem;
- (id)collaborationIdentifierQueryItem;
- (id)invitationPreferencesQueryItem;
- (id)providerQueryItem;
- (id)avModeQueryItem;
- (id)presentationModeQueryItem;
- (id)originatingUIQueryItem;
- (id)sendToScreeningQueryItem;
- (id)conversationMembersForIntent:(id)intent;
- (id)userActivityUsingStartCallIntents;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (BOOL)isUplinkMuted;
- (BOOL)isJoiningConversationWithLink;
@end

#endif /* TUJoinConversationRequest_h */
