//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1431.300.81.0.0
//
#ifndef TUNotifyObserver_h
#define TUNotifyObserver_h
@import Foundation;

#include "TUNotifyObserver-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface TUNotifyObserver : NSObject<TUNotifyObserver>

@property (readonly, nonatomic) struct os_unfair_lock_s { unsigned int x0; } lock;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (copy, nonatomic) NSString *notificationName;
@property (nonatomic) int token;
@property (copy, nonatomic) id /* block */ callback;
@property (readonly, nonatomic) unsigned long long state;
@property (readonly, nonatomic) BOOL observing;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithNotificationName:(id)name queue:(id)queue;
- (id)initWithNotificationName:(id)name queue:(id)queue callback:(id /* block */)callback;
- (void)dealloc;
- (BOOL)isObserving;
- (void)beginObserving;
- (void)endObserving;
- (void)_endObserving;
@end

#endif /* TUNotifyObserver_h */
