//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 81.0.0.0.0
//
#ifndef PRManagedLikeness_h
#define PRManagedLikeness_h
@import Foundation;

#include "NSManagedObject.h"

@class NSDate, NSNumber, NSString;

@interface PRManagedLikeness : NSManagedObject

@property (retain, @dynamic, nonatomic) NSString *uniqueID;
@property (retain, @dynamic, nonatomic) NSString *ownerID;
@property (retain, @dynamic, nonatomic) NSNumber *version;
@property (retain, @dynamic, nonatomic) NSString *recipe;
@property (retain, @dynamic, nonatomic) NSString *scope;
@property (retain, @dynamic, nonatomic) NSString *staticRepresentationFileID;
@property (retain, @dynamic, nonatomic) NSNumber *cropRectX;
@property (retain, @dynamic, nonatomic) NSNumber *cropRectY;
@property (retain, @dynamic, nonatomic) NSNumber *cropRectWidth;
@property (retain, @dynamic, nonatomic) NSNumber *cropRectHeight;
@property (retain, @dynamic, nonatomic) NSDate *expiration;
@property (retain, @dynamic, nonatomic) NSDate *softExpiration;
@property (retain, @dynamic, nonatomic) NSNumber *type;
@property (retain, @dynamic, nonatomic) NSString *externalID;
@property (retain, @dynamic, nonatomic) NSDate *dateAdded;
@property (retain, @dynamic, nonatomic) NSDate *dateCreated;
@property (retain, @dynamic, nonatomic) NSNumber *source;

@end

#endif /* PRManagedLikeness_h */
