//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 81.0.0.0.0
//
#ifndef PRManagedPropagationEvent_h
#define PRManagedPropagationEvent_h
@import Foundation;

#include "NSManagedObject.h"

@class NSNumber, NSString;

@interface PRManagedPropagationEvent : NSManagedObject

@property (retain, @dynamic, nonatomic) NSString *recipientID;
@property (retain, @dynamic, nonatomic) NSNumber *sentVersion;

@end

#endif /* PRManagedPropagationEvent_h */
