//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1205.1.1.2.0
//
#ifndef CUIKEditingContextObserver_Protocol_h
#define CUIKEditingContextObserver_Protocol_h
@import Foundation;

@protocol CUIKEditingContextObserver <NSObject>
/* instance methods */
- (id)oldObject:(id)object didUpdateTo:(id)to;
- (BOOL)isTestObserver;
@optional
/* instance methods */
- (void)saveCancelled;
@end

#endif /* CUIKEditingContextObserver_Protocol_h */
