//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1205.1.1.2.0
//
#ifndef CUIKCalendarInfo_h
#define CUIKCalendarInfo_h
@import Foundation;

#include "CUIKGroupInfo.h"

@class EKCalendar, NSString, UIColor;

@interface CUIKCalendarInfo : NSObject

@property (retain, nonatomic) EKCalendar *calendar;
@property (retain, nonatomic) UIColor *color;
@property (nonatomic) BOOL selected;
@property (weak, nonatomic) CUIKGroupInfo *group;
@property (readonly, copy, nonatomic) NSString *title;
@property (readonly, nonatomic) int displayOrder;
@property (readonly, nonatomic) BOOL isSubscribed;
@property (readonly, nonatomic) BOOL isShared;
@property (readonly, nonatomic) BOOL isPublished;
@property (readonly, nonatomic) BOOL isEditable;
@property (nonatomic) BOOL isEnabled;
@property (nonatomic) unsigned long long customGroupType;
@property (nonatomic) BOOL filteredByFocus;

/* instance methods */
- (void)_updateCustomGroupType;
- (id)initWithCalendar:(id)calendar;
- (id)description;
- (id)stringForSharedCalendar;
@end

#endif /* CUIKCalendarInfo_h */
