//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1387.3.4.0.0
//
#ifndef _ACComponentVector_h
#define _ACComponentVector_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"

@protocol {AudioComponentVector="__begin_"^v"__end_"^v"__end_cap_"{__compressed_pair<std::shared_ptr<APComponent> *, std::allocator<std::shared_ptr<APComponent>>>="__value_"^v}"mSorted"B};

@interface _ACComponentVector : NSObject<NSSecureCoding> {
  /* instance variables */
  struct AudioComponentVector { void *__begin_; void *__end_; struct __compressed_pair<std::shared_ptr<APComponent> *, std::allocator<std::shared_ptr<APComponent>>> { void *__value_; } __end_cap_; BOOL mSorted; } mVector;
}

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithVector:(const void *)vector;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* _ACComponentVector_h */
