//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HDMobilityWalkingSteadinessAnalyticsDailyEventDataSource_h
#define HDMobilityWalkingSteadinessAnalyticsDailyEventDataSource_h
@import Foundation;

#include "HKMobilityWalkingSteadinessAnalyticsDailyEventDataSourceProvider-Protocol.h"

@class HDProfile, NSString, NSUserDefaults;

@interface HDMobilityWalkingSteadinessAnalyticsDailyEventDataSource : NSObject<HKMobilityWalkingSteadinessAnalyticsDailyEventDataSourceProvider> {
  /* instance variables */
  HDProfile *_profile;
  NSUserDefaults *_mobilitySettingsDefaults;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithProfile:(id)profile;
- (id)activePairedWatchTypeWithError:(id *)error;
- (id)ageWithError:(id *)error;
- (id)biologicalSexWithError:(id *)error;
- (id)hasHeightWithError:(id *)error;
- (id)hasLaunchedHealthAppInLastWeek:(id *)week;
- (id)hasLaunchedHealthAppInLastMonth:(id *)month;
- (id)numberOfDaysSinceLastWalkingSteadinessMeasurementWithError:(id *)error;
- (id)numberOfLowNotificationsInPastYearWithError:(id *)error;
- (id)numberOfRepeatLowNotificationsInPastYearWithError:(id *)error;
- (id)numberOfVeryLowNotificationsInPastYearWithError:(id *)error;
- (id)numberOfRepeatVeryLowNotificationsInPastYearWithError:(id *)error;
- (id)numberOfInitialNotificationsInPastYearWithError:(id *)error;
- (id)daysSinceLastRepeatNotificationWithError:(id *)error;
- (id)daysSinceLastInitialNotificationWithError:(id *)error;
- (id)currentWalkingSteadinessClassificationWithError:(id *)error;
- (id)previousWalkingSteadinessClassificationWithError:(id *)error;
- (id)hasWalkingSteadinessMeasurementsWithError:(id *)error;
- (id)walkingSteadinessNotificationsEnabledWithError:(id *)error;
- (id)areHealthNotificationsAuthorizedWithError:(id *)error;
- (id)_samplePredicateForPastYearFromDate:(id)date;
- (id)_categoryValuePredicateWithValues:(id)values;
- (id)_countOfCategorySamplesInPastYearWithType:(id)type values:(id)values error:(id *)error;
- (id)_countOfSamplesInPastYearWithType:(id)type valuePredicate:(id)predicate error:(id *)error;
- (id)_countOfSamplesWithType:(id)type predicate:(id)predicate error:(id *)error;
- (id)_numberOfDaysSinceLastSampleWithSampleType:(id)type predicate:(id)predicate error:(id *)error;
- (id)_numberOfDaysSinceLastCategorySampleWithSampleType:(id)type values:(id)values error:(id *)error;
- (id)_hasSampleWithType:(id)type error:(id *)error;
- (id)_hasLaunchedHealthAppInLastWeekWithError:(id *)error;
- (id)_hasLaunchedHealthAppInLastMonthWithError:(id *)error;
- (id)_hasLaunchedHealthAppInLastTimeInterval:(double)interval error:(id *)error;
- (id)_healthAppLastOpenedDateWithError:(id *)error;
@end

#endif /* HDMobilityWalkingSteadinessAnalyticsDailyEventDataSource_h */
