//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3.1.1.0.0
//
#ifndef COSE_Sign1_h
#define COSE_Sign1_h
@import Foundation;

#include "COSE.h"

@class NSArray, NSData, NSString;

@interface COSE_Sign1 : COSE

@property (readonly, nonatomic) NSData *signature;
@property (readonly, nonatomic) NSArray *x509bag;
@property (readonly, nonatomic) NSArray *x509chain;
@property (readonly, nonatomic) NSString *x509uri;
@property (readonly, nonatomic) NSString *x509hashAlgorithmIdentifier;
@property (readonly, nonatomic) NSData *x509hashValue;

/* instance methods */
- (id)initWithProtectedHeaders:(id)headers unprotectedHeaders:(id)headers payload:(id)payload signature:(id)signature includeCBORTag:(BOOL)cbortag;
- (id)initWithCBOR:(id)cbor;
- (id)description;
@end

#endif /* COSE_Sign1_h */
