//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1226.2.2.1.0
//
#ifndef PPMutableNamedEntityRecord_h
#define PPMutableNamedEntityRecord_h
@import Foundation;

#include "PPNamedEntityRecord.h"
#include "PPNamedEntity.h"
#include "PPNamedEntityMetadata.h"
#include "PPSource.h"

@class NSString;

@interface PPMutableNamedEntityRecord : PPNamedEntityRecord

@property (retain, @dynamic, nonatomic) PPNamedEntity *entity;
@property (retain, @dynamic, nonatomic) PPSource *source;
@property (@dynamic, nonatomic) unsigned long long algorithm;
@property (@dynamic, nonatomic) double initialScore;
@property (@dynamic, nonatomic) double decayRate;
@property (retain, @dynamic, nonatomic) NSString *extractionOsBuild;
@property (@dynamic, nonatomic) unsigned char changeType;
@property (@dynamic, nonatomic) unsigned int extractionAssetVersion;
@property (@dynamic, nonatomic) double sentimentScore;
@property (retain, @dynamic, nonatomic) PPNamedEntityMetadata *metadata;

/* instance methods */
- (id)init;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* PPMutableNamedEntityRecord_h */
