//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2206.0.5.0.0
//
#ifndef WFRemoteExtensionProxy_h
#define WFRemoteExtensionProxy_h
@import Foundation;

#include "INCExtensionProxy-Protocol.h"

@class INCExtensionConnection, SARemoteDevice;

@interface WFRemoteExtensionProxy : NSObject<INCExtensionProxy>

@property (readonly, nonatomic) INCExtensionConnection *connection;
@property (readonly, copy, nonatomic) SARemoteDevice *remoteDevice;

/* instance methods */
- (id)initWithConnection:(id)connection andDevice:(id)device;
- (void)handleIntentRemotelyWithRemoteOperation:(id)operation completion:(id /* block */)completion;
- (void)confirmIntentWithCompletionHandler:(id /* block */)handler;
- (void)handleIntentWithCompletionHandler:(id /* block */)handler;
- (void)resolveIntentSlotKeyPath:(id)path completionHandler:(id /* block */)handler;
- (void)resolveIntentSlotKeyPaths:(id)paths completionHandler:(id /* block */)handler;
@end

#endif /* WFRemoteExtensionProxy_h */
