//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2206.0.5.0.0
//
#ifndef WFRemoteExecutionIncomingAskEachTimeSession_h
#define WFRemoteExecutionIncomingAskEachTimeSession_h
@import Foundation;

#include "WFRemoteExecutionSession.h"

@class NSDictionary, NSSet;

@interface WFRemoteExecutionIncomingAskEachTimeSession : WFRemoteExecutionSession

@property (retain, nonatomic) NSSet *lastKnownDestinations;
@property (retain, nonatomic) NSDictionary *lastKnownOptions;

/* instance methods */
- (void)handleIncomingProtobuf:(id)protobuf currentlyActiveSessions:(id)sessions responseDestinations:(id)destinations responseOptions:(id)options;
- (void)sendResponse:(id)response destinations:(id)destinations options:(id)options;
- (void)handleTimeout;
- (void)finishWithError:(id)error;
- (id)missingParameterError;
@end

#endif /* WFRemoteExecutionIncomingAskEachTimeSession_h */
