//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1232.2.3.0.0
//
#ifndef CalInMemoryTrackedDatabase_h
#define CalInMemoryTrackedDatabase_h
@import Foundation;

#include "CalDatabaseInMemoryChangeTracking.h"

@class NSHashTable;

@interface CalInMemoryTrackedDatabase : NSObject

@property (readonly, nonatomic) CalDatabaseInMemoryChangeTracking *database;
@property (readonly, nonatomic) NSHashTable *clients;
@property (readonly, nonatomic) BOOL hasClients;

/* instance methods */
- (id)init;
@end

#endif /* CalInMemoryTrackedDatabase_h */
