//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1232.2.3.0.0
//
#ifndef CalScheduledTaskCache_TimeZoneFetchContext_h
#define CalScheduledTaskCache_TimeZoneFetchContext_h
@import Foundation;

@class NSMutableDictionary, NSTimeZone;

@interface CalScheduledTaskCache_TimeZoneFetchContext : NSObject

@property (retain, nonatomic) NSTimeZone *previousTimeZone;
@property (retain, nonatomic) NSTimeZone *nextTimeZone;
@property (retain, nonatomic) NSMutableDictionary *dict;

/* instance methods */
@end

#endif /* CalScheduledTaskCache_TimeZoneFetchContext_h */
