//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.1.0.0
//
#ifndef _MRMediaRemoteMessageProtobuf_h
#define _MRMediaRemoteMessageProtobuf_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"
#include "_MRAVModifyOutputContextRequestProtobuf.h"
#include "_MRAdjustVolumeMessageProtobuf.h"
#include "_MRAudioFadeMessageProtobuf.h"
#include "_MRAudioFadeResponseMessageProtobuf.h"
#include "_MRClientUpdatesConfigurationProtobuf.h"
#include "_MRConfigureConnectionMessageProtobuf.h"
#include "_MRCreateHostedEndpointRequestProtobuf.h"
#include "_MRCreateHostedEndpointResponseProtobuf.h"
#include "_MRCryptoPairingMessageProtobuf.h"
#include "_MRDeviceInfoMessageProtobuf.h"
#include "_MRDiscoveryUpdateEndpointsProtobufMessage.h"
#include "_MRDiscoveryUpdateOutputDevicesProtobufMessage.h"
#include "_MRErrorProtobuf.h"
#include "_MRGameControllerMessageProtobuf.h"
#include "_MRGameControllerPropertiesMessageProtobuf.h"
#include "_MRGenericMessageProtobuf.h"
#include "_MRGetKeyboardSessionProtobuf.h"
#include "_MRGetRemoteTextInputSessionProtobuf.h"
#include "_MRGetStateMessageProtobuf.h"
#include "_MRGetVoiceInputDevicesMessageProtobuf.h"
#include "_MRGetVoiceInputDevicesResponseMessageProtobuf.h"
#include "_MRGetVolumeControlCapabilitiesMessageProtobuf.h"
#include "_MRGetVolumeControlCapabilitiesResultMessageProtobuf.h"
#include "_MRGetVolumeMessageProtobuf.h"
#include "_MRGetVolumeMutedMessageProtobuf.h"
#include "_MRGetVolumeMutedResultMessageProtobuf.h"
#include "_MRGetVolumeResultMessageProtobuf.h"
#include "_MRKeyboardMessageProtobuf.h"
#include "_MRNotificationMessageProtobuf.h"
#include "_MROriginClientPropertiesMessageProtobuf.h"
#include "_MRPlaybackQueueProtobuf.h"
#include "_MRPlaybackQueueRequestProtobuf.h"
#include "_MRPlaybackSessionMigrateBeginMessageProtobuf.h"
#include "_MRPlaybackSessionMigrateEndMessageProtobuf.h"
#include "_MRPlaybackSessionMigrateRequestMessageProtobuf.h"
#include "_MRPlaybackSessionMigrateResponseMessageProtobuf.h"
#include "_MRPlaybackSessionRequestMessageProtobuf.h"
#include "_MRPlaybackSessionResponseMessageProtobuf.h"
#include "_MRPlayerClientParticipantsUpdateMessageProtobuf.h"
#include "_MRPlayerClientPropertiesMessageProtobuf.h"
#include "_MRPresentRouteAuthorizationStatusMessageProtobuf.h"
#include "_MRPromptForRouteAuthorizationMessageProtobuf.h"
#include "_MRPromptForRouteAuthorizationResponseMessageProtobuf.h"
#include "_MRRegisterForGameControllerEventsMessageProtobuf.h"
#include "_MRRegisterGameControllerMessageProtobuf.h"
#include "_MRRegisterGameControllerResponseMessageProtobuf.h"
#include "_MRRegisterHIDDeviceMessageProtobuf.h"
#include "_MRRegisterHIDDeviceResultMessageProtobuf.h"
#include "_MRRegisterVoiceInputDeviceMessageProtobuf.h"
#include "_MRRegisterVoiceInputDeviceResponseMessageProtobuf.h"
#include "_MRRemoteTextInputMessageProtobuf.h"
#include "_MRRemoveClientMessageProtobuf.h"
#include "_MRRemoveEndpointsMessageProtobuf.h"
#include "_MRRemoveOutputDevicesMessageProtobuf.h"
#include "_MRRemovePlayerMessageProtobuf.h"
#include "_MRSendButtonEventMessageProtobuf.h"
#include "_MRSendCommandMessageProtobuf.h"
#include "_MRSendCommandResultMessageProtobuf.h"
#include "_MRSendHIDEventMessageProtobuf.h"
#include "_MRSendHIDReportMessageProtobuf.h"
#include "_MRSendLyricsEventMessageProtobuf.h"
#include "_MRSendPackedVirtualTouchEventMessageProtobuf.h"
#include "_MRSendVirtualTouchEventMessageProtobuf.h"
#include "_MRSendVoiceInputMessageProtobuf.h"
#include "_MRSetArtworkMessageProtobuf.h"
#include "_MRSetConnectionStateMessageProtobuf.h"
#include "_MRSetConversationDetectionEnabledMessageProtobuf.h"
#include "_MRSetDiscoveryModeProtobufMessage.h"
#include "_MRSetHiliteModeMessageProtobuf.h"
#include "_MRSetListeningModeMessageProtobuf.h"
#include "_MRSetNowPlayingClientMessageProtobuf.h"
#include "_MRSetNowPlayingPlayerMessageProtobuf.h"
#include "_MRSetReadyStateMessageProtobuf.h"
#include "_MRSetRecordingStateMessageProtobuf.h"
#include "_MRSetStateMessageProtobuf.h"
#include "_MRSetVolumeMessageProtobuf.h"
#include "_MRSetVolumeMutedMessageProtobuf.h"
#include "_MRTextInputMessageProtobuf.h"
#include "_MRTransactionMessageProtobuf.h"
#include "_MRUnregisterGameControllerMessageProtobuf.h"
#include "_MRUpdateActiveSystemEndpointMessageProtobuf.h"
#include "_MRUpdateClientMessageProtobuf.h"
#include "_MRUpdateContentItemArtworkMessageProtobuf.h"
#include "_MRUpdateContentItemMessageProtobuf.h"
#include "_MRUpdateEndpointsMessageProtobuf.h"
#include "_MRUpdateOutputDevicesMessageProtobuf.h"
#include "_MRUpdatePlayerMessageProtobuf.h"
#include "_MRVolumeControlAvailabilityProtobuf.h"
#include "_MRVolumeControlCapabilitiesDidChangeMessageProtobuf.h"
#include "_MRVolumeDidChangeMessageProtobuf.h"
#include "_MRVolumeMutedDidChangeMessageProtobuf.h"
#include "_MRWakeDeviceMessageProtobuf.h"

@class NSString;

@interface _MRMediaRemoteMessageProtobuf : PBCodable<NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 timestamp; unsigned int x :1 errorCode; unsigned int x :1 type; } _has;
}

@property (nonatomic) BOOL hasType;
@property (nonatomic) int type;
@property (readonly, nonatomic) BOOL hasReplyIdentifier;
@property (retain, nonatomic) NSString *replyIdentifier;
@property (readonly, nonatomic) BOOL hasAuthenticationToken;
@property (retain, nonatomic) NSString *authenticationToken;
@property (nonatomic) BOOL hasErrorCode;
@property (nonatomic) unsigned int errorCode;
@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (readonly, nonatomic) BOOL hasUniqueIdentifier;
@property (retain, nonatomic) NSString *uniqueIdentifier;
@property (readonly, nonatomic) BOOL hasSendCommandMessage;
@property (retain, nonatomic) _MRSendCommandMessageProtobuf *sendCommandMessage;
@property (readonly, nonatomic) BOOL hasSendCommandResultMessage;
@property (retain, nonatomic) _MRSendCommandResultMessageProtobuf *sendCommandResultMessage;
@property (readonly, nonatomic) BOOL hasSetStateMessage;
@property (retain, nonatomic) _MRSetStateMessageProtobuf *setStateMessage;
@property (readonly, nonatomic) BOOL hasNotificationMessage;
@property (retain, nonatomic) _MRNotificationMessageProtobuf *notificationMessage;
@property (readonly, nonatomic) BOOL hasContentItemsChangedNotificationMessage;
@property (retain, nonatomic) _MRPlaybackQueueProtobuf *contentItemsChangedNotificationMessage;
@property (readonly, nonatomic) BOOL hasDeviceInfoMessage;
@property (retain, nonatomic) _MRDeviceInfoMessageProtobuf *deviceInfoMessage;
@property (readonly, nonatomic) BOOL hasClientUpdatesConfigMessage;
@property (retain, nonatomic) _MRClientUpdatesConfigurationProtobuf *clientUpdatesConfigMessage;
@property (readonly, nonatomic) BOOL hasPlaybackQueueRequest;
@property (retain, nonatomic) _MRPlaybackQueueRequestProtobuf *playbackQueueRequest;
@property (readonly, nonatomic) BOOL hasConnectionState;
@property (retain, nonatomic) _MRSetConnectionStateMessageProtobuf *connectionState;
@property (readonly, nonatomic) BOOL hasGetVolumeMessage;
@property (retain, nonatomic) _MRGetVolumeMessageProtobuf *getVolumeMessage;
@property (readonly, nonatomic) BOOL hasGetVolumeResultMessage;
@property (retain, nonatomic) _MRGetVolumeResultMessageProtobuf *getVolumeResultMessage;
@property (readonly, nonatomic) BOOL hasSetVolumeMessage;
@property (retain, nonatomic) _MRSetVolumeMessageProtobuf *setVolumeMessage;
@property (readonly, nonatomic) BOOL hasVolumeDidChangeMessage;
@property (retain, nonatomic) _MRVolumeDidChangeMessageProtobuf *volumeDidChangeMessage;
@property (readonly, nonatomic) BOOL hasUpdateContentItemMessage;
@property (retain, nonatomic) _MRUpdateContentItemMessageProtobuf *updateContentItemMessage;
@property (readonly, nonatomic) BOOL hasSetDefaultSupportedCommandsMessage;
@property (retain, nonatomic) _MRSetStateMessageProtobuf *setDefaultSupportedCommandsMessage;
@property (readonly, nonatomic) BOOL hasGetStateMessage;
@property (retain, nonatomic) _MRGetStateMessageProtobuf *getStateMessage;
@property (readonly, nonatomic) BOOL hasError;
@property (retain, nonatomic) _MRErrorProtobuf *error;
@property (readonly, nonatomic) BOOL hasPlayerClientParticipantsUpdateMessage;
@property (retain, nonatomic) _MRPlayerClientParticipantsUpdateMessageProtobuf *playerClientParticipantsUpdateMessage;
@property (readonly, nonatomic) BOOL hasSetArtworkMessage;
@property (retain, nonatomic) _MRSetArtworkMessageProtobuf *setArtworkMessage;
@property (readonly, nonatomic) BOOL hasRegisterHIDDeviceMessage;
@property (retain, nonatomic) _MRRegisterHIDDeviceMessageProtobuf *registerHIDDeviceMessage;
@property (readonly, nonatomic) BOOL hasRegisterHIDDeviceResultMessage;
@property (retain, nonatomic) _MRRegisterHIDDeviceResultMessageProtobuf *registerHIDDeviceResultMessage;
@property (readonly, nonatomic) BOOL hasSendHIDEventMessage;
@property (retain, nonatomic) _MRSendHIDEventMessageProtobuf *sendHIDEventMessage;
@property (readonly, nonatomic) BOOL hasSendHIDReportMessage;
@property (retain, nonatomic) _MRSendHIDReportMessageProtobuf *sendHIDReportMessage;
@property (readonly, nonatomic) BOOL hasSendVirtualTouchEventMessage;
@property (retain, nonatomic) _MRSendVirtualTouchEventMessageProtobuf *sendVirtualTouchEventMessage;
@property (readonly, nonatomic) BOOL hasMasterVolumeControlCapabilitiesDidChangeMessage;
@property (retain, nonatomic) _MRVolumeControlAvailabilityProtobuf *masterVolumeControlCapabilitiesDidChangeMessage;
@property (readonly, nonatomic) BOOL hasGameController;
@property (retain, nonatomic) _MRGameControllerMessageProtobuf *gameController;
@property (readonly, nonatomic) BOOL hasRegisterGameController;
@property (retain, nonatomic) _MRRegisterGameControllerMessageProtobuf *registerGameController;
@property (readonly, nonatomic) BOOL hasRegisterGameControllerResponse;
@property (retain, nonatomic) _MRRegisterGameControllerResponseMessageProtobuf *registerGameControllerResponse;
@property (readonly, nonatomic) BOOL hasUnregisterGameController;
@property (retain, nonatomic) _MRUnregisterGameControllerMessageProtobuf *unregisterGameController;
@property (readonly, nonatomic) BOOL hasRegisterForGameControllerEvents;
@property (retain, nonatomic) _MRRegisterForGameControllerEventsMessageProtobuf *registerForGameControllerEvents;
@property (readonly, nonatomic) BOOL hasKeyboardMessage;
@property (retain, nonatomic) _MRKeyboardMessageProtobuf *keyboardMessage;
@property (readonly, nonatomic) BOOL hasGetKeyboardMessage;
@property (retain, nonatomic) _MRGetKeyboardSessionProtobuf *getKeyboardMessage;
@property (readonly, nonatomic) BOOL hasTextInputMessage;
@property (retain, nonatomic) _MRTextInputMessageProtobuf *textInputMessage;
@property (readonly, nonatomic) BOOL hasGetVoiceInputDevicesMessage;
@property (retain, nonatomic) _MRGetVoiceInputDevicesMessageProtobuf *getVoiceInputDevicesMessage;
@property (readonly, nonatomic) BOOL hasGetVoiceInputDevicesResponseMessage;
@property (retain, nonatomic) _MRGetVoiceInputDevicesResponseMessageProtobuf *getVoiceInputDevicesResponseMessage;
@property (readonly, nonatomic) BOOL hasRegisterVoiceInputDeviceMessage;
@property (retain, nonatomic) _MRRegisterVoiceInputDeviceMessageProtobuf *registerVoiceInputDeviceMessage;
@property (readonly, nonatomic) BOOL hasRegisterVoiceInputDeviceResponseMessage;
@property (retain, nonatomic) _MRRegisterVoiceInputDeviceResponseMessageProtobuf *registerVoiceInputDeviceResponseMessage;
@property (readonly, nonatomic) BOOL hasSetRecordingStateMessage;
@property (retain, nonatomic) _MRSetRecordingStateMessageProtobuf *setRecordingStateMessage;
@property (readonly, nonatomic) BOOL hasSendVoiceInputMessage;
@property (retain, nonatomic) _MRSendVoiceInputMessageProtobuf *sendVoiceInputMessage;
@property (readonly, nonatomic) BOOL hasTransactionPackets;
@property (retain, nonatomic) _MRTransactionMessageProtobuf *transactionPackets;
@property (readonly, nonatomic) BOOL hasCryptoPairingMessage;
@property (retain, nonatomic) _MRCryptoPairingMessageProtobuf *cryptoPairingMessage;
@property (readonly, nonatomic) BOOL hasGameControllerProperties;
@property (retain, nonatomic) _MRGameControllerPropertiesMessageProtobuf *gameControllerProperties;
@property (readonly, nonatomic) BOOL hasReadyStateMessage;
@property (retain, nonatomic) _MRSetReadyStateMessageProtobuf *readyStateMessage;
@property (readonly, nonatomic) BOOL hasSendButtonEventMessage;
@property (retain, nonatomic) _MRSendButtonEventMessageProtobuf *sendButtonEventMessage;
@property (readonly, nonatomic) BOOL hasSetHiliteModeMessage;
@property (retain, nonatomic) _MRSetHiliteModeMessageProtobuf *setHiliteModeMessage;
@property (readonly, nonatomic) BOOL hasWakeDeviceMessage;
@property (retain, nonatomic) _MRWakeDeviceMessageProtobuf *wakeDeviceMessage;
@property (readonly, nonatomic) BOOL hasGenericMessage;
@property (retain, nonatomic) _MRGenericMessageProtobuf *genericMessage;
@property (readonly, nonatomic) BOOL hasSendPackedVirtualTouchEventMessage;
@property (retain, nonatomic) _MRSendPackedVirtualTouchEventMessageProtobuf *sendPackedVirtualTouchEventMessage;
@property (readonly, nonatomic) BOOL hasSendLyricsEventMessage;
@property (retain, nonatomic) _MRSendLyricsEventMessageProtobuf *sendLyricsEventMessage;
@property (readonly, nonatomic) BOOL hasSetNowPlayingClientMessage;
@property (retain, nonatomic) _MRSetNowPlayingClientMessageProtobuf *setNowPlayingClientMessage;
@property (readonly, nonatomic) BOOL hasSetNowPlayingPlayerMessage;
@property (retain, nonatomic) _MRSetNowPlayingPlayerMessageProtobuf *setNowPlayingPlayerMessage;
@property (readonly, nonatomic) BOOL hasModifyOutputContextRequestMessage;
@property (retain, nonatomic) _MRAVModifyOutputContextRequestProtobuf *modifyOutputContextRequestMessage;
@property (readonly, nonatomic) BOOL hasRemoveClientMessage;
@property (retain, nonatomic) _MRRemoveClientMessageProtobuf *removeClientMessage;
@property (readonly, nonatomic) BOOL hasRemovePlayerMessage;
@property (retain, nonatomic) _MRRemovePlayerMessageProtobuf *removePlayerMessage;
@property (readonly, nonatomic) BOOL hasUpdateClientMessage;
@property (retain, nonatomic) _MRUpdateClientMessageProtobuf *updateClientMessage;
@property (readonly, nonatomic) BOOL hasUpdateContentItemArtworkMessage;
@property (retain, nonatomic) _MRUpdateContentItemArtworkMessageProtobuf *updateContentItemArtworkMessage;
@property (readonly, nonatomic) BOOL hasUpdatePlayerMessage;
@property (retain, nonatomic) _MRUpdatePlayerMessageProtobuf *updatePlayerMessage;
@property (readonly, nonatomic) BOOL hasPromptForRouteAuthorizationMessage;
@property (retain, nonatomic) _MRPromptForRouteAuthorizationMessageProtobuf *promptForRouteAuthorizationMessage;
@property (readonly, nonatomic) BOOL hasPromptForRouteAuthorizationResponseMessage;
@property (retain, nonatomic) _MRPromptForRouteAuthorizationResponseMessageProtobuf *promptForRouteAuthorizationResponseMessage;
@property (readonly, nonatomic) BOOL hasPresentRouteAuthorizationStatusMessage;
@property (retain, nonatomic) _MRPresentRouteAuthorizationStatusMessageProtobuf *presentRouteAuthorizationStatusMessage;
@property (readonly, nonatomic) BOOL hasGetVolumeControlCapabilitiesMessage;
@property (retain, nonatomic) _MRGetVolumeControlCapabilitiesMessageProtobuf *getVolumeControlCapabilitiesMessage;
@property (readonly, nonatomic) BOOL hasGetVolumeControlCapabilitiesResultMessage;
@property (retain, nonatomic) _MRGetVolumeControlCapabilitiesResultMessageProtobuf *getVolumeControlCapabilitiesResultMessage;
@property (readonly, nonatomic) BOOL hasVolumeControlCapabilitiesDidChangeMessage;
@property (retain, nonatomic) _MRVolumeControlCapabilitiesDidChangeMessageProtobuf *volumeControlCapabilitiesDidChangeMessage;
@property (readonly, nonatomic) BOOL hasUpdateOutputDevicesMessage;
@property (retain, nonatomic) _MRUpdateOutputDevicesMessageProtobuf *updateOutputDevicesMessage;
@property (readonly, nonatomic) BOOL hasRemoveOutputDevicesMessage;
@property (retain, nonatomic) _MRRemoveOutputDevicesMessageProtobuf *removeOutputDevicesMessage;
@property (readonly, nonatomic) BOOL hasRemoteTextInputMessage;
@property (retain, nonatomic) _MRRemoteTextInputMessageProtobuf *remoteTextInputMessage;
@property (readonly, nonatomic) BOOL hasGetRemoteTextInputSessionMessage;
@property (retain, nonatomic) _MRGetRemoteTextInputSessionProtobuf *getRemoteTextInputSessionMessage;
@property (readonly, nonatomic) BOOL hasPlaybackSessionRequestMessage;
@property (retain, nonatomic) _MRPlaybackSessionRequestMessageProtobuf *playbackSessionRequestMessage;
@property (readonly, nonatomic) BOOL hasPlaybackSessionResponseMessage;
@property (retain, nonatomic) _MRPlaybackSessionResponseMessageProtobuf *playbackSessionResponseMessage;
@property (readonly, nonatomic) BOOL hasPlaybackSessionMigrateRequestMessage;
@property (retain, nonatomic) _MRPlaybackSessionMigrateRequestMessageProtobuf *playbackSessionMigrateRequestMessage;
@property (readonly, nonatomic) BOOL hasPlaybackSessionMigrateResponseMessage;
@property (retain, nonatomic) _MRPlaybackSessionMigrateResponseMessageProtobuf *playbackSessionMigrateResponseMessage;
@property (readonly, nonatomic) BOOL hasErrorDescription;
@property (retain, nonatomic) NSString *errorDescription;
@property (readonly, nonatomic) BOOL hasPlaybackSessionMigrateBeginMessage;
@property (retain, nonatomic) _MRPlaybackSessionMigrateBeginMessageProtobuf *playbackSessionMigrateBeginMessage;
@property (readonly, nonatomic) BOOL hasPlaybackSessionMigrateEndMessage;
@property (retain, nonatomic) _MRPlaybackSessionMigrateEndMessageProtobuf *playbackSessionMigrateEndMessage;
@property (readonly, nonatomic) BOOL hasUpdateActiveSystemEndpointMessage;
@property (retain, nonatomic) _MRUpdateActiveSystemEndpointMessageProtobuf *updateActiveSystemEndpointMessage;
@property (readonly, nonatomic) BOOL hasDiscoveryModeMessage;
@property (retain, nonatomic) _MRSetDiscoveryModeProtobufMessage *discoveryModeMessage;
@property (readonly, nonatomic) BOOL hasUpdateEndpointsMessage;
@property (retain, nonatomic) _MRUpdateEndpointsMessageProtobuf *updateEndpointsMessage;
@property (readonly, nonatomic) BOOL hasRemoveEndpointsMessage;
@property (retain, nonatomic) _MRRemoveEndpointsMessageProtobuf *removeEndpointsMessage;
@property (readonly, nonatomic) BOOL hasPlayerClientPropertiesMessage;
@property (retain, nonatomic) _MRPlayerClientPropertiesMessageProtobuf *playerClientPropertiesMessage;
@property (readonly, nonatomic) BOOL hasOriginClientPropertiesMessage;
@property (retain, nonatomic) _MROriginClientPropertiesMessageProtobuf *originClientPropertiesMessage;
@property (readonly, nonatomic) BOOL hasAudioFadeMessage;
@property (retain, nonatomic) _MRAudioFadeMessageProtobuf *audioFadeMessage;
@property (readonly, nonatomic) BOOL hasAudioFadeResponseMessage;
@property (retain, nonatomic) _MRAudioFadeResponseMessageProtobuf *audioFadeResponseMessage;
@property (readonly, nonatomic) BOOL hasDiscoveryUpdateEndpointsMessage;
@property (retain, nonatomic) _MRDiscoveryUpdateEndpointsProtobufMessage *discoveryUpdateEndpointsMessage;
@property (readonly, nonatomic) BOOL hasDiscoveryUpdateOutputDevicesMessage;
@property (retain, nonatomic) _MRDiscoveryUpdateOutputDevicesProtobufMessage *discoveryUpdateOutputDevicesMessage;
@property (readonly, nonatomic) BOOL hasSetListeningModeMessage;
@property (retain, nonatomic) _MRSetListeningModeMessageProtobuf *setListeningModeMessage;
@property (readonly, nonatomic) BOOL hasConfigureConnectionMessage;
@property (retain, nonatomic) _MRConfigureConnectionMessageProtobuf *configureConnectionMessage;
@property (readonly, nonatomic) BOOL hasCreateHostedEndpointRequest;
@property (retain, nonatomic) _MRCreateHostedEndpointRequestProtobuf *createHostedEndpointRequest;
@property (readonly, nonatomic) BOOL hasCreateHostedEndpointResponse;
@property (retain, nonatomic) _MRCreateHostedEndpointResponseProtobuf *createHostedEndpointResponse;
@property (readonly, nonatomic) BOOL hasAdjustVolumeMessage;
@property (retain, nonatomic) _MRAdjustVolumeMessageProtobuf *adjustVolumeMessage;
@property (readonly, nonatomic) BOOL hasGetVolumeMutedMessage;
@property (retain, nonatomic) _MRGetVolumeMutedMessageProtobuf *getVolumeMutedMessage;
@property (readonly, nonatomic) BOOL hasGetVolumeMutedResultMessage;
@property (retain, nonatomic) _MRGetVolumeMutedResultMessageProtobuf *getVolumeMutedResultMessage;
@property (readonly, nonatomic) BOOL hasSetVolumeMutedMessage;
@property (retain, nonatomic) _MRSetVolumeMutedMessageProtobuf *setVolumeMutedMessage;
@property (readonly, nonatomic) BOOL hasVolumeMutedDidChangeMessage;
@property (retain, nonatomic) _MRVolumeMutedDidChangeMessageProtobuf *volumeMutedDidChangeMessage;
@property (readonly, nonatomic) BOOL hasSetConversationDetectionEnabledMessage;
@property (retain, nonatomic) _MRSetConversationDetectionEnabledMessageProtobuf *setConversationDetectionEnabledMessage;

/* instance methods */
- (id)typeAsString:(int)string;
- (int)StringAsType:(id)type;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* _MRMediaRemoteMessageProtobuf_h */
