//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2206.0.5.0.0
//
#ifndef IKEngine_h
#define IKEngine_h
@import Foundation;

#include "IKEngineDelegate-Protocol.h"

@class NSMutableDictionary, NSString;

@interface IKEngine : NSObject {
  /* instance variables */
  NSMutableDictionary *_connections;
}

@property (nonatomic) NSObject<IKEngineDelegate> *delegate;
@property (copy, nonatomic) NSString *OAuthToken;
@property (copy, nonatomic) NSString *OAuthTokenSecret;

/* class methods */
+ (void)setOAuthConsumerKey:(id)key andConsumerSecret:(id)secret;

/* instance methods */
- (id)initWithDelegate:(id)delegate;
- (id)init;
- (id)connectionForIdentifier:(id)identifier;
- (id)identifierForConnection:(id)connection;
- (unsigned long long)numberOfConnections;
- (id)authTokenForUsername:(id)username password:(id)password userInfo:(id)info;
- (id)verifyCredentialsWithUserInfo:(id)info;
- (id)bookmarksWithUserInfo:(id)info;
- (id)bookmarksInFolder:(id)folder limit:(unsigned long long)limit existingBookmarks:(id)bookmarks userInfo:(id)info;
- (id)updateReadProgressOfBookmark:(id)bookmark toProgress:(double)progress userInfo:(id)info;
- (id)addBookmarkWithURL:(id)url userInfo:(id)info;
- (id)addBookmarkWithURL:(id)url title:(id)title description:(id)description folder:(id)folder resolveFinalURL:(BOOL)url userInfo:(id)info;
- (id)deleteBookmark:(id)bookmark userInfo:(id)info;
- (id)starBookmark:(id)bookmark userInfo:(id)info;
- (id)unstarBookmark:(id)bookmark userInfo:(id)info;
- (id)archiveBookmark:(id)bookmark userInfo:(id)info;
- (id)unarchiveBookmark:(id)bookmark userInfo:(id)info;
- (id)moveBookmark:(id)bookmark toFolder:(id)folder userInfo:(id)info;
- (id)textOfBookmark:(id)bookmark userInfo:(id)info;
- (id)foldersWithUserInfo:(id)info;
- (id)addFolderWithTitle:(id)title userInfo:(id)info;
- (id)deleteFolder:(id)folder userInfo:(id)info;
- (id)orderFolders:(id)folders userInfo:(id)info;
- (void)cancelConnection:(id)connection;
- (void)cancelAllConnections;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connectionDidFinishLoading:(id)loading;
- (void)dealloc;
- (id)_startConnectionWithAPIPath:(id)apipath bodyArguments:(id)arguments type:(int)type userInfo:(id)info context:(id)context;
- (id)_signatureWithKey:(id)key baseString:(id)string;
@end

#endif /* IKEngine_h */
