//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2206.0.5.0.0
//
#ifndef NSURLConnectionDataDelegate_Protocol_h
#define NSURLConnectionDataDelegate_Protocol_h
@import Foundation;

@protocol NSURLConnectionDataDelegate <NSURLConnectionDelegate>
@optional
/* instance methods */
- (id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connection:(id)connection didReceiveData:(id)data;
- (id)connection:(id)connection needNewBodyStream:(id)stream;
- (void)connection:(id)connection didSendBodyData:(long long)data totalBytesWritten:(long long)written totalBytesExpectedToWrite:(long long)write;
- (id)connection:(id)connection willCacheResponse:(id)response;
- (void)connectionDidFinishLoading:(id)loading;
@end

#endif /* NSURLConnectionDataDelegate_Protocol_h */
