//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2206.0.5.0.0
//
#ifndef WFSSHKeyDecoder_h
#define WFSSHKeyDecoder_h
@import Foundation;

@class NSData;

@interface WFSSHKeyDecoder : NSObject

@property (readonly, nonatomic) NSData *data;
@property (nonatomic) unsigned long long offset;
@property (nonatomic) unsigned long long length;

/* instance methods */
- (id)initWithData:(id)data;
- (const char *)currentPointer;
- (void)advanceBy:(unsigned long long)by;
- (unsigned int)decodeInteger;
- (id)decodeStringWithLength:(unsigned long long)length;
- (id)decodeStringWithPrecedingLength;
- (id)decodeDataWithLength:(unsigned long long)length;
- (id)decodeDataWithPrecedingLength;
@end

#endif /* WFSSHKeyDecoder_h */
