//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1161.4.0.0.0
//
#ifndef NPKBalanceDetailCommutePlanFieldsSectionProvider_h
#define NPKBalanceDetailCommutePlanFieldsSectionProvider_h
@import Foundation;

#include "NPKBalanceDetailSectionProvider.h"

@interface NPKBalanceDetailCommutePlanFieldsSectionProvider : NPKBalanceDetailSectionProvider
/* instance methods */
- (id)commutePlanField;
- (id)sectionIdentifiers;
- (id)titleForSectionWithIdentifier:(id)identifier;
- (id)itemsForSectionWithIdentifier:(id)identifier;
- (BOOL)_fieldContainsDetails;
@end

#endif /* NPKBalanceDetailCommutePlanFieldsSectionProvider_h */
