//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1161.4.0.0.0
//
#ifndef NPKPassDetailViewControllerDelegate_Protocol_h
#define NPKPassDetailViewControllerDelegate_Protocol_h
@import Foundation;

@protocol NPKPassDetailViewControllerDelegate <NPKListViewControllerDelegate>
/* instance methods */
- (void)passDetailViewControllerDidRequestServiceMode:(id)mode;
- (void)passDetailViewControllerDidRequestSessionEnd:(id)end;
- (void)passDetailViewControllerDidReceiveUnarchiveRequestForPass:(id)pass;
- (void)passDetailViewControllerDidReceiveDeletionRequestForPass:(id)pass;
- (void)passDetailViewControllerDidRequestActionForTileItem:(id)item atIndexPath:(id)path inTilesViewController:(id)controller forPass:(id)pass;
@end

#endif /* NPKPassDetailViewControllerDelegate_Protocol_h */
