//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1161.4.0.0.0
//
#ifndef NPKPeerPaymentPagedButtonsView_h
#define NPKPeerPaymentPagedButtonsView_h
@import Foundation;

#include "UIView.h"
#include "NPKButton.h"
#include "NPKPeerPaymentPagedButtonsViewDelegate-Protocol.h"
#include "UIScrollViewDelegate-Protocol.h"

@class NSString, PUICActivityIndicatorView, PUICButton, PUICPageIndicatorView, UIScrollView;

@interface NPKPeerPaymentPagedButtonsView : UIView<UIScrollViewDelegate>

@property (retain, nonatomic) PUICPageIndicatorView *pageControl;
@property (retain, nonatomic) NPKButton *payButton;
@property (retain, nonatomic) PUICActivityIndicatorView *activityIndicatorForPayButton;
@property (retain, nonatomic) NPKButton *requestButton;
@property (retain, nonatomic) PUICActivityIndicatorView *activityIndicatorForRequestButton;
@property (retain, nonatomic) UIScrollView *scrollView;
@property (weak, nonatomic) NSObject<NPKPeerPaymentPagedButtonsViewDelegate> *delegate;
@property (readonly, nonatomic) PUICActivityIndicatorView *activityIndicatorForDisplayedButton;
@property (readonly, nonatomic) PUICButton *displayedButton;
@property (readonly, nonatomic) NSString *expectedTitleForDisplayedButton;
@property (nonatomic) long long currentPage;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)_initializeSubviews;
- (void)layoutSubviews;
- (BOOL)canBecomeFirstResponder;
- (void)_payButtonTapped:(id)tapped;
- (void)_requestButtonTapped:(id)tapped;
- (void)scrollViewDidEndDecelerating:(id)decelerating;
- (void)scrollViewDidEndDragging:(id)dragging willDecelerate:(BOOL)decelerate;
@end

#endif /* NPKPeerPaymentPagedButtonsView_h */
