//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1161.4.0.0.0
//
#ifndef NPKShareEntitlementsConfiguration_h
#define NPKShareEntitlementsConfiguration_h
@import Foundation;

#include "NPKPassDetailSectionProviderConfiguration.h"

@class NSArray, PKPassShare;

@interface NPKShareEntitlementsConfiguration : NPKPassDetailSectionProviderConfiguration

@property (weak, nonatomic) PKPassShare *share;
@property (weak, nonatomic) NSArray *shareableEntitlements;
@property (weak, nonatomic) NSArray *selectedEntitlements;
@property (nonatomic) unsigned long long maxEntitlementSelectionCount;
@property (nonatomic) BOOL allowsEditing;
@property (nonatomic) BOOL showSaveButton;

/* instance methods */
- (id)initWithPass:(id)pass shareableEntitlements:(id)entitlements selectedEntitlements:(id)entitlements maxEntitlementSelectionCount:(unsigned long long)count allowsEditing:(BOOL)editing;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)configurationByApplyingConfiguration:(id)configuration;
@end

#endif /* NPKShareEntitlementsConfiguration_h */
