//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 503.2.0.0.0
//
#ifndef STAppInfo_h
#define STAppInfo_h
@import Foundation;

@class NSData, NSString, NSURL;

@interface STAppInfo : NSObject

@property (nonatomic) long long source;
@property (copy, nonatomic) NSString *bundleIdentifier;
@property (copy, nonatomic) NSString *displayName;
@property (nonatomic) short platform;
@property (copy, nonatomic) NSString *developerName;
@property (copy, nonatomic) NSString *ratingLabel;
@property (copy, nonatomic) NSURL *localURL;
@property (copy, nonatomic) NSURL *artworkURL;
@property (copy) NSData *artworkData;

/* instance methods */
- (id)description;
@end

#endif /* STAppInfo_h */
