//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 503.2.0.0.0
//
#ifndef STAskToManageContactsRequestReceivedUserNotificationContext_h
#define STAskToManageContactsRequestReceivedUserNotificationContext_h
@import Foundation;

#include "STUserNotificationContext.h"

@interface STAskToManageContactsRequestReceivedUserNotificationContext : STUserNotificationContext
/* instance methods */
- (id)init;
- (void)customizeNotificationContent:(id)content withCompletionBlock:(id /* block */)block;
@end

#endif /* STAskToManageContactsRequestReceivedUserNotificationContext_h */
