//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 503.2.0.0.0
//
#ifndef STUserData_h
#define STUserData_h
@import Foundation;

@class NSString;

@interface STUserData : NSObject

@property (readonly, copy, nonatomic) NSString *identifier;
@property (readonly, copy, nonatomic) NSString *givenName;
@property (readonly, nonatomic) BOOL isParent;
@property (readonly, nonatomic) BOOL isRemote;
@property (readonly, nonatomic) BOOL hasPasscode;
@property (readonly, nonatomic) BOOL screenTimeEnabled;
@property (readonly, nonatomic) BOOL syncingEnabled;
@property (readonly, nonatomic) BOOL checkForUnsafePhotos;
@property (readonly, nonatomic) BOOL isCommunicationSafetyNotificationEnabled;
@property (readonly, nonatomic) BOOL isCommunicationSafetyAnalyticsEnabled;
@property (readonly, nonatomic) NSString *familyMemberType;

/* instance methods */
- (id)initWithIdentifier:(id)identifier givenName:(id)name isParent:(BOOL)parent isRemote:(BOOL)remote hasPasscode:(BOOL)passcode screenTimeEnabled:(BOOL)enabled syncingEnabled:(BOOL)enabled checkForUnsafePhotos:(BOOL)photos communicationSafetyNotificationEnabled:(BOOL)enabled communicationSafetyAnalyticsEnabled:(BOOL)enabled familyMemberType:(id)type;
@end

#endif /* STUserData_h */
