//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 930.0.0.0.0
//
#ifndef _TtC13TeaFoundationP33_89C94C1602C77B8CEBFBCE49D1F8016731BlockBasedBackgroundFetchWorker_h
#define _TtC13TeaFoundationP33_89C94C1602C77B8CEBFBCE49D1F8016731BlockBasedBackgroundFetchWorker_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface TeaFoundation.(BlockBasedBackgroundFetchWorker in _89C94C1602C77B8CEBFBCE49D1F80167) : Swift._SwiftObject { // (Swift)
  /* instance variables */
   triggers;
   block;
}

@end

#endif /* _TtC13TeaFoundationP33_89C94C1602C77B8CEBFBCE49D1F8016731BlockBasedBackgroundFetchWorker_h */
