//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 956.0.0.0.0
//
#ifndef ACDAccountCache_h
#define ACDAccountCache_h
@import Foundation;

@class NSMutableDictionary;

@interface ACDAccountCache : NSObject {
  /* instance variables */
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _cachesLock;
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _expirersLock;
}

@property unsigned int cacheValidityDuration;
@property (retain) NSMutableDictionary *cachedAccountsByID;
@property (retain) NSMutableDictionary *cachedAccountIDsByType;
@property (retain) NSMutableDictionary *cachedAccountTypesByID;
@property (retain) NSMutableDictionary *expirersByID;
@property (retain) NSMutableDictionary *generationWritersByKey;

/* instance methods */
- (id)initWithValidityDuration:(unsigned int)duration;
- (void)cacheAccount:(id)account;
- (id)cachedAccountForIdentifier:(id)identifier;
- (id)_keyForType:(id)type justActive:(BOOL)active;
- (void)cacheAccounts:(id)accounts forType:(id)type justActive:(BOOL)active;
- (id)cachedAccountsOfType:(id)type justActive:(BOOL)active;
- (void)_lock_removeAccountsForType:(id)type;
- (id)_expirerIdentifierForAccountTypeID:(id)id;
- (void)cacheAccountType:(id)type;
- (id)cachedAccountTypeForID:(id)id;
- (void)removeAccountType:(id)type;
- (void)removeAccount:(id)account store:(id)store;
- (void)clearCache;
- (void)_resetParentAccountForCachedAccountIfNeeded:(id)needed;
- (void)cacheGenerationForAccounts:(id)accounts cacheSuffix:(id)suffix;
- (id)_lock_writerForKey:(id)key;
- (void)_lock_cacheGenerationForAccounts:(id)accounts cacheSuffix:(id)suffix;
- (void)_lock_resetCacheGenerationsForChildren:(id)children recurseDepth:(unsigned long long)depth store:(id)store;
- (void)_lock_resetAllAccountTypeIdentifiers;
- (void)_lock_resetGenerationForType:(id)type;
@end

#endif /* ACDAccountCache_h */
