//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef _UIDatePickerMode_DateAndTime_h
#define _UIDatePickerMode_DateAndTime_h
@import Foundation;

#include "_UIDatePickerMode.h"

@class NSDateFormatter, NSString;

@interface _UIDatePickerMode_DateAndTime : _UIDatePickerMode {
  /* instance variables */
  BOOL _weekdayLast;
  double _wmdWeekMonthDayWidth;
  double _wmdHourWidth;
  double _wmdMinuteWidth;
  double _wmdAMPMWidth;
  double _wmdWeekdayWidth;
  NSString *_weekdayFormat;
  NSString *_monthDayFormat;
  NSString *_hourFormat;
  NSString *_minuteFormat;
  NSDateFormatter *_relativeFormatter;
  NSDateFormatter *_weekdayFormatter;
}

/* class methods */
+ (long long)datePickerMode;
+ (unsigned long long)extractableCalendarUnits;

/* instance methods */
- (void)_shouldReset:(id)reset;
- (void)resetComponentWidths;
- (void)noteCalendarChanged;
- (id)relativeFormatter;
- (id)weekdayFormatter;
- (id)localizedFormatString;
- (id)dateFormatForCalendarUnit:(unsigned long long)unit;
- (long long)displayedCalendarUnits;
- (unsigned long long *)elements;
- (void)loadDate:(id)date animated:(BOOL)animated;
- (void)_resetBaseDateComponentsIfNecessaryFromDate:(id)date;
- (void)_takeBaseDateComponentsFromDate:(id)date;
- (id)baseDateComponents;
- (long long)numberOfRowsForCalendarUnit:(unsigned long long)unit;
- (double)componentWidthForDateTimeCalendarUnit:(unsigned long long)unit font:(id)font maxWidth:(double)width;
- (double)widthForCalendarUnit:(unsigned long long)unit font:(id)font maxWidth:(double)width;
- (double)weekdayWidth;
- (BOOL)isWeekdayLast;
- (id)titleForRow:(long long)row inComponent:(long long)component;
- (id)dateForRow:(long long)row inCalendarUnit:(unsigned long long)unit;
- (long long)rowForDate:(id)date dateComponents:(id)components component:(long long)component currentRow:(long long)row;
- (id)_dateForWeekMonthDayRow:(long long)row;
- (BOOL)_shouldEnableWeekMonthDayForRow:(long long)row;
- (BOOL)_shouldEnableValueForRow:(long long)row inComponent:(long long)component calendarUnit:(unsigned long long)unit;
- (id)viewForRow:(long long)row inComponent:(long long)component reusingView:(id)view;
- (void)updateEnabledStateOfViewForRow:(long long)row inComponent:(long long)component;
- (unsigned long long)nextUnitLargerThanUnit:(unsigned long long)unit;
- (unsigned long long)nextUnitSmallerThanUnit:(unsigned long long)unit;
@end

#endif /* _UIDatePickerMode_DateAndTime_h */
