//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef _UIKBArbiterInputDestinationProtocol_Protocol_h
#define _UIKBArbiterInputDestinationProtocol_Protocol_h
@import Foundation;

@protocol _UIKBArbiterInputDestinationProtocol <_UIKBArbiterInputEventsProtocol>
/* instance methods */
- (void)notifyIAVHeight:(double)iavheight;
- (void)signalKeyboardClientChanged:(id)changed onCompletion:(id /* block */)completion;
- (void)setWindowContextID:(unsigned int)id focusContext:(id)context windowState:(unsigned long long)state withLevel:(double)level;
- (void)setClientFocusContext:(id)context;
- (void)applicationShouldFocusWithBundle:(id)bundle onCompletion:(id /* block */)completion;
- (void)focusApplicationWithProcessIdentifier:(int)identifier context:(id)context onCompletion:(id /* block */)completion;
- (void)focusApplicationWithProcessIdentifier:(int)identifier context:(id)context stealingKeyboard:(BOOL)keyboard onCompletion:(id /* block */)completion;
@end

#endif /* _UIKBArbiterInputDestinationProtocol_Protocol_h */
