//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef _UIPassthroughGateGestureRecognizer_h
#define _UIPassthroughGateGestureRecognizer_h
@import Foundation;

#include "UIGestureRecognizer.h"
#include "_UIPassthroughGestureDelegate-Protocol.h"

@interface _UIPassthroughGateGestureRecognizer : UIGestureRecognizer

@property (weak, @dynamic, nonatomic) NSObject<_UIPassthroughGestureDelegate> *delegate;

/* class methods */
+ (BOOL)_supportsTouchContinuation;

/* instance methods */
- (id)initWithTarget:(id)target action:(SEL)action;
- (void)open;
- (void)endClosed;
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;
- (BOOL)_shouldReceiveTouch:(id)touch withEvent:(id)event;
@end

#endif /* _UIPassthroughGateGestureRecognizer_h */
