//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef _UISearchBarScopeContainerLayout_h
#define _UISearchBarScopeContainerLayout_h
@import Foundation;

#include "_UISearchBarLayoutBase.h"
#include "UIView.h"
#include "_UISearchBarContainerSublayoutDelegate-Protocol.h"
#include "_UISearchBarSearchContainerLayout.h"

@interface _UISearchBarScopeContainerLayout : _UISearchBarLayoutBase

@property (weak, nonatomic) NSObject<_UISearchBarContainerSublayoutDelegate> *delegate;
@property (nonatomic) BOOL collapsed;
@property (retain, nonatomic) _UISearchBarSearchContainerLayout *neighboringSearchLayout;
@property (retain, nonatomic) UIView *scopeBar;
@property (nonatomic) BOOL hasScopeBar;
@property (nonatomic) unsigned long long numberOfScopeTitles;
@property (nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } defaultScopeBarInsets;
@property (copy, nonatomic) id /* block */ hostedScopeBarHeightForBarMetrics;
@property (copy, nonatomic) id /* block */ hostedScopeBarTopInsetForBarMetrics;
@property (readonly, nonatomic) struct UIEdgeInsets { double x0; double x1; double x2; double x3; } containerSpecificInsets;
@property (readonly, nonatomic) double naturalContainerHeight;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } scopeBarLayoutFrame;
@property (readonly, nonatomic) double scopeBarOpacity;

/* instance methods */
- (double)scopeControlHeight;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)updateLayout;
- (void)applyLayout;
- (id)description;
- (BOOL)isCollapsed;
@end

#endif /* _UISearchBarScopeContainerLayout_h */
