//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef _UIScenePresentationView_h
#define _UIScenePresentationView_h
@import Foundation;

#include "_UIVisibilityPropagationView.h"
#include "BSDescriptionProviding-Protocol.h"
#include "BSInvalidatable-Protocol.h"
#include "FBSceneObserver-Protocol.h"
#include "UIScenePresentation-Protocol.h"
#include "UIScenePresentationContext.h"
#include "UIScenePresenter-Protocol.h"
#include "UIView.h"
#include "_UISceneLayerHostContainerView.h"
#include "_UISceneLayerHostContainerViewDataSource-Protocol.h"
#include "_UIScenePresenter.h"

@class FBSSceneSettings, FBSSceneSettingsDiffInspector, FBScene, NSHashTable, NSString;

@interface _UIScenePresentationView : _UIVisibilityPropagationView<FBSceneObserver, _UISceneLayerHostContainerViewDataSource, BSDescriptionProviding, UIScenePresentation, BSInvalidatable> {
  /* instance variables */
  FBScene *_scene;
  FBSSceneSettings *_effectiveSettings;
  FBSSceneSettingsDiffInspector *_geometrySettingsDiffInspector;
  NSHashTable *_observers;
  BOOL _invalidated;
}

@property (retain, nonatomic) UIScenePresentationContext *currentPresentationContext;
@property (retain, nonatomic) _UISceneLayerHostContainerView *hostContainerView;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) NSObject<UIScenePresenter> *presenter;
@property (retain, nonatomic) UIView *backgroundView;

/* instance methods */
- (id)initWithPresenter:(id)presenter;
- (void)dealloc;
- (void)addObserver:(id)observer;
- (void)removeObserver:(id)observer;
- (void)didMoveToWindow;
- (id)_hitTest:(struct CGPoint { double x0; double x1; })test withEvent:(id)event windowServerHitTestWindow:(id)window;
- (void)invalidate;
- (id)identifier;
- (id)presentationContextForSceneLayerHostContainerView;
- (void)scene:(id)scene clientDidConnect:(id)connect;
- (void)sceneDidActivate:(id)activate;
- (void)sceneWillDeactivate:(id)deactivate withError:(id)error;
- (void)scene:(id)scene didPrepareUpdateWithContext:(id)context;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (void)_updatePresentationContextFrom:(id)from toContext:(id)context;
- (void)_updateBackgroundColor;
- (void)_geometryDidUpdateWithTransitionContext:(id)context;
- (void)_updateFrameAndTransform;
@end

#endif /* _UIScenePresentationView_h */
