//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef UIAccessibilityHUDView_h
#define UIAccessibilityHUDView_h
@import Foundation;

#include "UIView.h"
#include "UIAccessibilityHUDItem.h"
#include "UIBlurEffect.h"
#include "UIImageView.h"
#include "UILabel.h"
#include "UIView.h"
#include "UIVisualEffectView.h"

@interface UIAccessibilityHUDView : UIView {
  /* instance variables */
  UIView *_transformContainer;
  UIVisualEffectView *_effectView;
  UIBlurEffect *_blurEffect;
  UIVisualEffectView *_itemEffectView;
  UIImageView *_imageView;
  UILabel *_titleLabel;
  UIView *_customView;
}

@property (copy, nonatomic) UIAccessibilityHUDItem *item;

/* class methods */
+ (struct CGSize { double x0; double x1; })preferredHUDSize;

/* instance methods */
- (id)initWithHUDItem:(id)huditem;
- (id)_contentEffectsForItem:(id)item;
- (void)_updateLabelForItem;
- (id)layoutManager;
- (struct CGSize { double x0; double x1; })sizeThatFits:(struct CGSize { double x0; double x1; })fits;
- (void)layoutSubviews;
- (void)_show:(BOOL)_show animated:(BOOL)animated completion:(id /* block */)completion;
- (void)showAnimated:(BOOL)animated completion:(id /* block */)completion;
- (void)dismissAnimated:(BOOL)animated completion:(id /* block */)completion;
- (id)containerViewForLayout;
- (id)itemContainerViewForLayout;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })imageInsetsForLayout;
- (id)titleLabel;
- (id)imageView;
- (id)customView;
@end

#endif /* UIAccessibilityHUDView_h */
