//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef UICollectionViewTableLayoutInvalidationContext_h
#define UICollectionViewTableLayoutInvalidationContext_h
@import Foundation;

#include "UICollectionViewLayoutInvalidationContext.h"

@interface UICollectionViewTableLayoutInvalidationContext : UICollectionViewLayoutInvalidationContext

@property (nonatomic) BOOL invalidateTableLayoutDelegateMetrics;
@property (nonatomic) BOOL skipSectionInvalidation;

@end

#endif /* UICollectionViewTableLayoutInvalidationContext_h */
