//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef UIKeyboardCandidatePocketShadow_h
#define UIKeyboardCandidatePocketShadow_h
@import Foundation;

#include "UICollectionReusableView.h"

@interface UIKeyboardCandidatePocketShadow : UICollectionReusableView

@property (nonatomic) BOOL shadowFadesToBottom;
@property (nonatomic) BOOL drawsShadow;
@property (nonatomic) BOOL showsInDarkBackground;

/* class methods */
+ (double)widthWithShadow:(BOOL)shadow;
+ (id)leftShadowImage;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)drawRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rect;
- (void)applyLayoutAttributes:(id)attributes;
@end

#endif /* UIKeyboardCandidatePocketShadow_h */
