//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3.2.4.0.0
//
#ifndef BLSHFlipbookContext_h
#define BLSHFlipbookContext_h
@import Foundation;

@class CAContext;

@interface BLSHFlipbookContext : NSObject

@property (readonly, nonatomic) CAContext *caContext;
@property (readonly, nonatomic) BOOL wantsTransform;
@property (readonly, nonatomic) BOOL inverted;

/* instance methods */
- (id)initWithCAContext:(id)cacontext wantsTransform:(BOOL)transform inverted:(BOOL)inverted;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
- (BOOL)isInverted;
@end

#endif /* BLSHFlipbookContext_h */
