//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 800.20.10.0.0
//
#ifndef WLKAdamIDToCanonicalIDRequestOperation_h
#define WLKAdamIDToCanonicalIDRequestOperation_h
@import Foundation;

#include "WLKUTSNetworkRequestOperation.h"
#include "WLKAdamIDToCanonicalIDResponse.h"

@class NSString;

@interface WLKAdamIDToCanonicalIDRequestOperation : WLKUTSNetworkRequestOperation

@property (retain, nonatomic) NSString *adamId;
@property (retain, nonatomic) WLKAdamIDToCanonicalIDResponse *response;

/* instance methods */
- (id)initWithAdamId:(id)id;
- (void)processResponse;
@end

#endif /* WLKAdamIDToCanonicalIDRequestOperation_h */
