//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 624.0.100.0.0
//
#ifndef IPAVideoOperation_h
#define IPAVideoOperation_h
@import Foundation;

#include "IPAEditOperation.h"

@interface IPAVideoOperation : IPAEditOperation
/* class methods */
+ (id)presetifyAdjustment:(id)adjustment;

/* instance methods */
- (id)archivalRepresentation;
@end

#endif /* IPAVideoOperation_h */
