//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 64562.3.1.1.0
//
#ifndef DVTFileStream_h
#define DVTFileStream_h
@import Foundation;

#include "DVTInputStream-Protocol.h"

@class NSFileHandle, NSString;

@interface DVTFileStream : NSObject<DVTInputStream> {
  /* instance variables */
  NSFileHandle *_fileHandle;
  unsigned long long _fileSize;
  unsigned long long _currentRead;
}

@property (readonly) NSFileHandle *file;
@property (readonly, nonatomic) BOOL supportsPeek;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithURL:(id)url;
- (id)initWithFD:(int)fd;
- (void)_updateFileSize;
- (BOOL)hasData;
- (id)peek:(unsigned long long)peek error:(id *)error;
- (id)read:(unsigned long long)read error:(id *)error;
- (id)readToEnd:(id *)end;
@end

#endif /* DVTFileStream_h */
