//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 320.100.1.0.0
//
#ifndef TPSPhonebookTelephonyController_h
#define TPSPhonebookTelephonyController_h
@import Foundation;

#include "TPSTelephonyController.h"
#include "CoreTelephonyClientSuppServicesDelegate-Protocol.h"

@class CTPhoneNumberInfo, CTXPCServiceSubscriptionContext, NSString;

@interface TPSPhonebookTelephonyController : TPSTelephonyController<CoreTelephonyClientSuppServicesDelegate>

@property (readonly, nonatomic) CTXPCServiceSubscriptionContext *subscriptionContext;
@property (nonatomic) long long phoneBookEntryCount;
@property (retain, nonatomic) CTPhoneNumberInfo *phoneNumberInfo;
@property (copy, nonatomic) NSString *updatePhoneNumber;
@property (copy, nonatomic) id /* block */ updatePhoneNumberInfoCompletion;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)initWithSubscriptionContext:(id)context;
- (id)getPhoneNumberInfo;
- (id)getPhoneNumberInfoWithError:(id *)error;
- (void)fetchPhoneNumberInfo;
- (void)fetchPhoneNumberInfoWithCompletion:(id /* block */)completion;
- (void)selectPhoneBookWithName:(int)name password:(id)password completion:(id /* block */)completion;
- (void)savePhoneBookEntryAtIndex:(int)index withContactName:(id)name contactNumber:(id)number;
- (void)savePhoneBookEntryAtIndex:(int)index withContactName:(id)name contactNumber:(id)number completion:(id /* block */)completion;
- (void)updatePhoneNumberInfo:(id)info label:(id)label number:(id)number completion:(id /* block */)completion;
- (void)phoneNumberChanged:(id)changed;
- (void)phoneBookSelected:(id)selected;
@end

#endif /* TPSPhonebookTelephonyController_h */
