//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 841.3.9.0.0
//
#ifndef HFTargetModeControlItem_h
#define HFTargetModeControlItem_h
@import Foundation;

#include "HFMultiStateControlItem.h"
#include "HFMultiStateValueSet.h"
#include "HFPowerStateControlItem.h"
#include "HFToggleableControlItem-Protocol.h"

@class NSString;

@interface HFTargetModeControlItem : HFMultiStateControlItem<HFToggleableControlItem>

@property (readonly, nonatomic) NSString *targetModeCharacteristicType;
@property (readonly, nonatomic) HFMultiStateValueSet *targetModeValueSet;
@property (readonly, nonatomic) HFPowerStateControlItem *primaryPowerStateControlItem;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithValueSource:(id)source targetModeCharacteristicType:(id)type targetModeValueSet:(id)set primaryPowerStateControlItem:(id)item displayResults:(id)results;
- (id)initWithValueSource:(id)source characteristicType:(id)type possibleValueSet:(id)set displayResults:(id)results;
- (id)copyWithCharacteristicOptions:(id)options valueSource:(id)source;
- (id)updateWithOptions:(id)options;
- (id)valueForCharacteristicValues:(id)values;
- (id)characteristicValuesForValue:(id)value;
- (id)toggleValue;
@end

#endif /* HFTargetModeControlItem_h */
