//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 841.3.9.0.0
//
#ifndef HFTriggerActionsSetsUISummary_h
#define HFTriggerActionsSetsUISummary_h
@import Foundation;

@class NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface HFTriggerActionsSetsUISummary : NSObject

@property (nonatomic) unsigned long long numberOfScenes;
@property (nonatomic) unsigned long long numberOfStandaloneServices;
@property (nonatomic) unsigned long long numberOfMediaAccessories;
@property (nonatomic) unsigned long long totalStandaloneAndMediaAccessoriesCount;
@property (retain, nonatomic) NSString *firstSceneName;
@property (retain, nonatomic) NSString *firstServiceName;
@property (retain, nonatomic) NSString *mediaAccessoryName;
@property (retain, nonatomic) NSMutableArray *icons;
@property (retain, nonatomic) NSMutableArray *iconDescriptors;
@property (retain, nonatomic) NSMutableDictionary *iconCounter;
@property (readonly, nonatomic) NSString *summaryDescription;
@property (readonly, nonatomic) NSArray *summaryDescriptors;
@property (readonly, nonatomic) BOOL hasUniqueServiceGroup;
@property (nonatomic) BOOL needsIconSort;
@property (readonly, nonatomic) unsigned long long numberOfIcons;
@property (retain, nonatomic) NSString *uniqueServiceGroupName;

/* instance methods */
- (id)initWithSummaryText:(id)text summaryIconDescriptors:(id)descriptors;
- (id)initWithSummaryText:(id)text summaryIconNames:(id)names;
- (id)init;
- (id)summaryText;
- (id)summaryText:(BOOL)text;
- (id)_descriptionForZeroAccessories;
- (id)_descriptionForZeroScenes;
- (id)summaryIcons;
- (id)summaryIconDescriptors;
- (void)addSceneNamed:(id)named;
- (void)addServiceNamed:(id)named;
- (void)addIconDescriptor:(id)descriptor;
- (void)_incrementIconCounter:(id)counter;
- (void)_sortIconDescriptors;
- (void)addMediaAccessoryNamed:(id)named;
@end

#endif /* HFTriggerActionsSetsUISummary_h */
