//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 7209.1.301.0.0
//
#ifndef _UISSecureControlCategory_h
#define _UISSecureControlCategory_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSString;

@interface _UISSecureControlCategory : NSObject<NSCopying, NSSecureCoding> {
  /* instance variables */
  union { unsigned short all; struct { unsigned int x :6 type; unsigned int x :5 iconIndex; unsigned int x :5 labelIndex; } x0; } _fields;
}

@property (readonly, nonatomic) unsigned long long type;
@property (readonly, nonatomic) unsigned int secureName;
@property (readonly, nonatomic) unsigned int secureNameForDrawing;
@property (readonly, nonatomic) NSString *iconGlyph;
@property (readonly, nonatomic) BOOL valid;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithType:(unsigned long long)type iconIndex:(unsigned long long)index labelIndex:(unsigned long long)index;
- (id)initWithCoder:(id)coder;
- (unsigned long long)authenticationMessageContextForStyle:(id)style;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
- (BOOL)isValid;
@end

#endif /* _UISSecureControlCategory_h */
