//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4416.36.0.0.0
//
#ifndef SBSUserNotificationCAPackageDefinition_h
#define SBSUserNotificationCAPackageDefinition_h
@import Foundation;

#include "SBSUserNotificationAssetDefinition.h"

@class NSString;

@interface SBSUserNotificationCAPackageDefinition : SBSUserNotificationAssetDefinition

@property (readonly, copy, nonatomic) NSString *caPackagePath;

/* class methods */
+ (id)_definitionType;
+ (id)definitionWithCAPackagePath:(id)path;

/* instance methods */
- (id)_initWithCAPackagePath:(id)path;
- (id)_initWithDictionary:(id)dictionary;
- (id)build;
@end

#endif /* SBSUserNotificationCAPackageDefinition_h */
