//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.1.17.12.4
//
#ifndef WBChangeRecord_h
#define WBChangeRecord_h
@import Foundation;

#include "WebBookmark.h"
#include "WebBookmarkCollection.h"

@interface WBChangeRecord : NSObject

@property (readonly, nonatomic) WebBookmarkCollection *collection;
@property (readonly, nonatomic) WebBookmark *bookmark;
@property (readonly, nonatomic) int changeType;
@property (readonly, nonatomic) long long localRecordGeneration;

/* instance methods */
- (id)initWithBookmarkCollection:(id)collection bookmark:(id)bookmark changeType:(int)type localRecordGeneration:(long long)generation;
- (id)_changeTypeDescription;
- (id)_changedAttributeDescription;
- (id)description;
@end

#endif /* WBChangeRecord_h */
