//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 114.2.2.0.0
//
#ifndef WAGGestureServerChannelDelegate_Protocol_h
#define WAGGestureServerChannelDelegate_Protocol_h
@import Foundation;

@protocol WAGGestureServerChannelDelegate <NSObject>
/* instance methods */
- (void)channel:(id)channel connection:(id)connection didReceiveClientMessage:(id)message;
- (void)channel:(id)channel didDisconnectFromClient:(id)client;
@end

#endif /* WAGGestureServerChannelDelegate_Protocol_h */
