//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2200.4.3.7.0
//
#ifndef MTAlarmCache_h
#define MTAlarmCache_h
@import Foundation;

#include "MTAlarm.h"

@class NSMutableArray;

@interface MTAlarmCache : NSObject

@property (copy, nonatomic) id /* block */ updateBlock;
@property (retain, nonatomic) NSMutableArray *orderedAlarms;
@property (retain, nonatomic) NSMutableArray *sleepAlarms;
@property (retain, nonatomic) MTAlarm *nextAlarm;
@property (nonatomic) BOOL needsUpdate;
@property (nonatomic) struct os_unfair_lock_s { unsigned int x0; } cacheLock;

/* instance methods */
- (id)initWithUpdateBlock:(id /* block */)block;
- (void)_withLock:(id /* block */)lock;
- (void)markNeedsUpdate;
- (BOOL)_isUpdateNeeded;
- (void)_getCachedAlarmsWithCompletion:(id /* block */)completion doSynchronous:(BOOL)synchronous;
- (void)getCachedAlarmsWithCompletion:(id /* block */)completion;
- (void)getCachedAlarmsSyncWithCompletion:(id /* block */)completion;
@end

#endif /* MTAlarmCache_h */
