//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2200.4.3.7.0
//
#ifndef MTSleepCoordinatorStateMachineInfoProvider_Protocol_h
#define MTSleepCoordinatorStateMachineInfoProvider_Protocol_h
@import Foundation;

@protocol MTSleepCoordinatorStateMachineInfoProvider <MTStateMachineInfoProvider>

@property (readonly, nonatomic) MTAlarm *sleepAlarm;
@property (readonly, nonatomic) NSDate *currentDate;
@property (readonly, nonatomic) unsigned long long sleepTimeOutMinutes;

@end

#endif /* MTSleepCoordinatorStateMachineInfoProvider_Protocol_h */
