//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2653.2.1.0.0
//
#ifndef DAEditPropertyAction_h
#define DAEditPropertyAction_h
@import Foundation;

#include "DAAction.h"

@class NSString;

@interface DAEditPropertyAction : DAAction

@property (readonly, nonatomic) NSString *propertyName;
@property (readonly, nonatomic) NSString *value;
@property (readonly, nonatomic) NSString *propertyNamespace;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithChangedItem:(id)item propertyName:(id)name value:(id)value propertyNamespace:(id)namespace serverId:(id)id;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* DAEditPropertyAction_h */
