//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1112.2.15.0.0
//
#ifndef CSLMRUApplicationsSetting_h
#define CSLMRUApplicationsSetting_h
@import Foundation;

#include "CSLMRUApplicationsProviding-Protocol.h"
#include "CSLMRUApplicationsSettingDelegate-Protocol.h"

@class NSArray, NSString, NSUserDefaults;

@interface CSLMRUApplicationsSetting : NSObject<CSLMRUApplicationsProviding> {
  /* instance variables */
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
  NSUserDefaults *_userDefaults;
}

@property (readonly, nonatomic) NSArray *mruApplications;
@property (readonly, nonatomic) unsigned long long maximumMRU;
@property (weak, nonatomic) NSObject<CSLMRUApplicationsSettingDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)dealloc;
- (void)_withLock:(id /* block */)lock;
- (void)observeValueForKeyPath:(id)path ofObject:(id)object change:(id)change context:(void *)context;
- (void)_updateMRUApplications:(id)mruapplications;
- (void)_updateMaximumMRU:(unsigned long long)mru;
@end

#endif /* CSLMRUApplicationsSetting_h */
