//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1112.2.15.0.0
//
#ifndef CSLPIBacklightProvider_Protocol_h
#define CSLPIBacklightProvider_Protocol_h
@import Foundation;

@protocol CSLPIBacklightProvider <NSObject>
/* instance methods */
- (BOOL)backlightProviderIsScreenOn;
- (BOOL)backlightProviderWillScreenBeOn;
- (BOOL)backlightProviderIsScreenBlanked;
- (void)onForIdentifier:(id)identifier reason:(unsigned int)reason isUserInitiated:(BOOL)initiated pid:(int)pid timestamp:(unsigned long long)timestamp;
- (void)offForIdentifier:(id)identifier reason:(unsigned int)reason isUserInitiated:(BOOL)initiated pid:(int)pid timestamp:(unsigned long long)timestamp;
- (void)invalidateAllFramesForReason:(id)reason;
@end

#endif /* CSLPIBacklightProvider_Protocol_h */
