//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1112.2.15.0.0
//
#ifndef CSLStingAlternateActionConfiguration_h
#define CSLStingAlternateActionConfiguration_h
@import Foundation;

#include "CSLStingViewConfiguration.h"
#include "NSCopying-Protocol.h"

@interface CSLStingAlternateActionConfiguration : NSObject<NSCopying>

@property (readonly, nonatomic) CSLStingViewConfiguration *nextConfiguration;
@property (readonly, nonatomic) CSLStingViewConfiguration *alternateConfiguration;

/* class methods */
+ (id)configurationWithNext:(id)next alternate:(id)alternate;

/* instance methods */
- (id)initWithNextConfiguration:(id)configuration alternateConfiguration:(id)configuration;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* CSLStingAlternateActionConfiguration_h */
