//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 752.2.0.0.0
//
#ifndef ASCompetitionStore_h
#define ASCompetitionStore_h
@import Foundation;

#include "ASDatabaseClient.h"

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface ASCompetitionStore : NSObject {
  /* instance variables */
  ASDatabaseClient *_databaseClient;
  NSObject<OS_dispatch_queue> *_serialQueue;
  NSMutableDictionary *_currentCompetitionListCache;
  NSMutableDictionary *_archivedCompetitionListCache;
  NSMutableDictionary *_remoteCompetitionListCache;
}

/* instance methods */
- (id)initWithDatabaseClient:(id)client;
- (BOOL)loadCachedCompetitions;
- (void)deleteCachedCompetitions;
- (id)currentCompetitionListForFriendWithUUID:(id)uuid;
- (id)archivedCompetitionListForFriendWithUUID:(id)uuid;
- (id)currentRemoteCompetitionForContact:(id)contact;
- (BOOL)saveCompetitionLists:(id)lists;
- (BOOL)saveRemoteCompetitionList:(id)list;
- (BOOL)_saveCompetitionLists:(id)lists owner:(long long)owner;
- (BOOL)_saveCompetitionListToDatabase:(id)database owner:(long long)owner error:(id *)error;
- (BOOL)_removeCompetitionsWithFriendFromDatabase:(id)database type:(long long)type error:(id *)error;
- (BOOL)_saveCompetitionsToDatabase:(id)database friendUUID:(id)uuid type:(long long)type error:(id *)error;
- (void)_queue_saveCompetitionListsToCache:(id)cache owner:(long long)owner;
- (id)_cachedCompetitionListForFriendWithUUID:(id)uuid type:(long long)type owner:(long long)owner;
- (id)_queue_competitionListCacheForType:(long long)type owner:(long long)owner;
@end

#endif /* ASCompetitionStore_h */
