//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1004.0.0.0.0
//
#ifndef CRDataType_Protocol_h
#define CRDataType_Protocol_h
@import Foundation;

@protocol CRDataType <NSObject>
/* instance methods */
- (void)mergeWith:(id)with;
- (id)deltaSince:(id)since in:(id)in;
- (void)realizeLocalChangesIn:(id)in;
- (id)tombstone;
- (void)walkGraph:(id /* block */)graph;
- (void)setDocument:(id)document;
@end

#endif /* CRDataType_Protocol_h */
