//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1004.0.0.0.0
//
#ifndef REMFetchResult_h
#define REMFetchResult_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"
#include "REMFetchMetadata.h"
#include "REMFetchResultToken.h"

@class NSArray;

@interface REMFetchResult : NSObject<NSSecureCoding>

@property (nonatomic) long long type;
@property (readonly, nonatomic) long long count;
@property (readonly, nonatomic) NSArray *requestedObjectIDs;
@property (readonly, nonatomic) NSArray *fetchedAccountStorages;
@property (readonly, nonatomic) NSArray *fetchedListStorages;
@property (readonly, nonatomic) NSArray *fetchedReminderStorages;
@property (readonly, nonatomic) REMFetchMetadata *metadata;
@property (retain, nonatomic) REMFetchResultToken *fetchResultToken;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithType:(long long)type;
- (id)initWithCount:(long long)count;
- (id)initWithAccountStorages:(id)storages listStorages:(id)storages reminderStorages:(id)storages requestedObjectIDs:(id)ids metadata:(id)metadata;
- (id)initWithAccountStorages:(id)storages;
- (id)initWithListStorages:(id)storages;
- (id)initWithReminderStorages:(id)storages;
- (id)initWithRequestedObjectIDs:(id)ids;
- (id)initWithMetadata:(id)metadata;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)description;
@end

#endif /* REMFetchResult_h */
