//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1004.0.0.0.0
//
#ifndef REMLogStore_h
#define REMLogStore_h
@import Foundation;

@interface REMLogStore : NSObject
/* class methods */
+ (id)container;
+ (id)stagedLightweightCoreDataMigration;
+ (id)xpc;
+ (id)read;
+ (id)write;
+ (id)search;
+ (id)utility;
+ (id)OVERSIZED;
@end

#endif /* REMLogStore_h */
