//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 866.4.0.0.0
//
#ifndef _CUIThemeModelMeshRendition_h
#define _CUIThemeModelMeshRendition_h
@import Foundation;

#include "CUIThemeRendition.h"

@class MDLMesh, NSArray, NSMutableArray;

@interface _CUIThemeModelMeshRendition : CUIThemeRendition {
  /* instance variables */
  MDLMesh *_mesh;
}

@property (readonly) NSArray *submeshKeys;

/* instance methods */
- (id)initForArchiving:(id)archiving withSubmeshRenditionKeys:(id)keys;
- (unsigned long long)writeToData:(id)data;
@end

#endif /* _CUIThemeModelMeshRendition_h */
