//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 866.4.0.0.0
//
#ifndef CUIPSDLayerMaskRef_h
#define CUIPSDLayerMaskRef_h
@import Foundation;

#include "CUIPSDLayerRef.h"

@interface CUIPSDLayerMaskRef : NSObject {
  /* instance variables */
  CUIPSDLayerRef *_layerRef;
  BOOL _isVectorMask;
}

/* instance methods */
- (id)initLayerMaskWithLayerRef:(id)ref;
- (id)initVectorMaskWithLayerRef:(id)ref;
- (void)dealloc;
- (id)layerRef;
- (BOOL)isLinked;
- (BOOL)isEnabled;
- (BOOL)isInvertedWhenBlending;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds;
- (struct CGPath *)newBezierPath;
- (struct CGPath *)newBezierPathAtScale:(double)scale;
- (struct CGImage *)createCGImageMask;
@end

#endif /* CUIPSDLayerMaskRef_h */
