//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3093.2.4.4.10
//
#ifndef AXCodeLoader_h
#define AXCodeLoader_h
@import Foundation;

#include "AXImageMonitor-Protocol.h"
#include "AXImageMonitorObserver-Protocol.h"

@class NSMutableDictionary, NSMutableSet, NSString;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface AXCodeLoader : NSObject<AXImageMonitorObserver> {
  /* instance variables */
  NSObject<AXImageMonitor> *_imageMonitor;
  NSObject<OS_dispatch_queue> *_queue;
  NSObject<OS_dispatch_source> *_loadAccessibilityCodeItemsSource;
  NSObject<OS_dispatch_source> *_dyldImageActivityCoalesceTimer;
  long long _monitoredLoadTriggeringImageCountSinceLastLoad;
  NSMutableSet *_trackedCodeItems;
  NSMutableSet *_accessibilityCodeItems;
  NSMutableDictionary *_codeItemsByNameType;
  id /* block */ _beginTrackingCompletion;
  NSObject<OS_dispatch_queue> *_beginTrackingCompletionQueue;
  BOOL _initialLoadHasOccurred;
  BOOL _initialLoadHasFinished;
  NSString *_currentPlatformKey;
}

@property (nonatomic) long long trackingMode;
@property (readonly, nonatomic) BOOL isTrackingLoadedCodeItems;
@property (readonly, nonatomic) BOOL isInitialLoadFinished;
@property (nonatomic) BOOL shouldAutoloadAccessibilityCodeItems;
@property (copy, nonatomic) id /* block */ shouldLoadAccessibilityCodeItemBlock;
@property (copy, nonatomic) id /* block */ didLoadAccessibilityCodeItemBlock;
@property (copy, nonatomic) id /* block */ loadEventWillOccurBlock;
@property (copy, nonatomic) id /* block */ loadEventDidOccurBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)defaultLoader;

/* instance methods */
- (id)recomputedCodeItemsForAllFrameworks;
- (id)recomputedCodeItemsForLoadedAccessibilityBundles;
- (id)accessibilityCodeItemDefinitions;
- (id)_stateDescForItem:(id)item;
- (void)logLoaderState;
- (id)trackedCodeItems;
- (id)rogueAccessibilityCodeItems;
- (id)initWithImageMonitor:(id)monitor;
- (id)init;
- (id /* block */)_validShouldLoadAccessibilityCodeItemBlock;
- (id /* block */)_validDidLoadAccessibilityCodeItemBlock;
- (id /* block */)_validLoadEventWillOccurBlock;
- (id /* block */)_validLoadEventDidOccurBlock;
- (void)beginTrackingLoadedCodeItemsWithMode:(long long)mode completion:(id /* block */)completion targetQueue:(id)queue;
- (void)endTrackingLoadedCodeItemsWithCompletion:(id /* block */)completion targetQueue:(id)queue;
- (void)_addTrackedCodeItem:(id)item;
- (id)loadedCodeItemPathsUsingTrackedItemsIfAvailable:(BOOL)available;
- (id)_queue_loadedCodeItemsUsingTrackedItemsIfAvailable:(BOOL)available;
- (id)loadedCodeItemsUsingTrackedItemsIfAvailable:(BOOL)available;
- (id)codeItemForBundle:(id)bundle;
- (void)setAccessibilityCodeItemsNeedLoaded;
- (void)_scheduleDyldImageActivityTimerWithDelay:(double)delay;
- (void)_cancelDyldImageActivityTimer;
- (void)_consumeBeginTrackingCompletionHandlerIfNeeded;
- (void)prewarmAccessibilityCodeItemDefinitionsWithCompletion:(id /* block */)completion targetQueue:(id)queue;
- (void)_updateAccessibilityCodeItemDefinitionsIfNeeded;
- (void)_initializeCodeItemMappings;
- (void)_reconcileTrackedCodeItemsWithAccessibilityCodeItemDefinitions;
- (id)_platformKeyForPlatform:(unsigned int)platform;
- (id)_accessibilityCodeItemMatchingName:(id)name type:(long long)type path:(id)path;
- (void)_associateAccessibilityCodeItemWithLoadedCodeItem:(id)item;
- (void)_associateAccessibilityCodeItemsWithAllTrackedCodeItems;
- (id)_accessibilityBundleMapURLs;
- (id)_createAccessibilityCodeItemsFromBundleMapURLs:(id)urls;
- (void)_loadAccessibilityCodeItems;
- (void)queryAccessibilityBundleIsLoadedWithName:(id)name completion:(id /* block */)completion;
- (void)imageMonitor:(id)monitor didAddImage:(id)image;
- (void)iterateInitialImageListForImageMonitor:(id)monitor;
@end

#endif /* AXCodeLoader_h */
