//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3093.2.4.4.10
//
#ifndef AXSubsystemContextKit_h
#define AXSubsystemContextKit_h
@import Foundation;

#include "AXLoggingSubsystem.h"

@interface AXSubsystemContextKit : AXLoggingSubsystem
/* class methods */
+ (id)identifier;
@end

#endif /* AXSubsystemContextKit_h */
