//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2021.300.9.2.0
//
#ifndef NMUAlbumSongListCell_h
#define NMUAlbumSongListCell_h
@import Foundation;

#include "NMUListBodyPlatterCell.h"
#include "NMUCollectionConfiguring-Protocol.h"

@class NSString, UILabel;

@interface NMUAlbumSongListCell : NMUListBodyPlatterCell<NMUCollectionConfiguring>

@property (readonly, nonatomic) UILabel *trackNumberLabel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)configureWithObject:(id)object context:(id)context;
@end

#endif /* NMUAlbumSongListCell_h */
