//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3431.206.0.0.0
//
#ifndef TITypologyTimer_h
#define TITypologyTimer_h
@import Foundation;

@interface TITypologyTimer : NSObject

@property (nonatomic) double elapsedTime;
@property (nonatomic) double mostRecentTimestamp;
@property (nonatomic) double maxTimeIntervalBetweenInputs;
@property (nonatomic) BOOL foundFirstInput;

/* instance methods */
- (void)addInputEventWithTimestamp:(double)timestamp;
@end

#endif /* TITypologyTimer_h */
