//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 452.0.6.0.0
//
#ifndef AXSSKeyboardCommandCategory_h
#define AXSSKeyboardCommandCategory_h
@import Foundation;

@class NSArray, NSString;

@interface AXSSKeyboardCommandCategory : NSObject

@property (readonly, nonatomic) NSArray *commands;
@property (readonly, nonatomic) NSString *localizedName;

/* class methods */
+ (id)allCategoriesForAvailableCommands:(id)commands;
+ (id)_categoryWithCommandIdentifiers:(id)identifiers availableCommands:(id)commands localizedName:(id)name;
+ (id)_categoryWithCommands:(id)commands availableCommands:(id)commands localizedName:(id)name;
+ (id)_basicCommandsFromAvailableCommands:(id)commands;
+ (id)_movementCommandsFromAvailableCommands:(id)commands;
+ (id)_interactionCommandsFromAvailableCommands:(id)commands;
+ (id)_advancedCommandsFromAvailableCommands:(id)commands;
+ (id)_deviceCommandsFromAvailableCommands:(id)commands;
+ (id)_pointerCommandsFromAvailableCommands:(id)commands;
+ (id)_gesturesCommandsFromAvailableCommands:(id)commands;

/* instance methods */
- (id)initWithCommands:(id)commands localizedName:(id)name;
@end

#endif /* AXSSKeyboardCommandCategory_h */
