//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tools: [ld (607.2), ld (814.1), ld (902.8)]
//    - LC_SOURCE_VERSION: 7.2.10.0.0
//
#ifndef AMSDeviceMessengerFilter_h
#define AMSDeviceMessengerFilter_h
@import Foundation;

@class ACAccount;

@interface AMSDeviceMessengerFilter : NSObject

@property (nonatomic) long long messageType;
@property (retain, nonatomic) ACAccount *account;
@property (nonatomic) long long deviceType;

/* instance methods */
- (BOOL)matchesMessage:(id)message;
@end

#endif /* AMSDeviceMessengerFilter_h */
