//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 651.5.0.0.0
//
#ifndef BSUIVibrancyView_h
#define BSUIVibrancyView_h
@import Foundation;

#include "UIView.h"
#include "BSUIVibrancyConfiguration.h"

@interface BSUIVibrancyView : UIView {
  /* instance variables */
  struct { BOOL resolvedEffectType; BOOL effectFilterViews; } _needsUpdate;
}

@property (copy, nonatomic) BSUIVibrancyConfiguration *configuration;

/* class methods */
+ (BOOL)isDisabled;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)layoutSubviews;
- (void)_update;
- (void)invalidateSubviews;
- (void)_invalidateFilters;
- (void)_updateFilterViewsIfNeeded;
- (void)updateFilters;
@end

#endif /* BSUIVibrancyView_h */
