//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2220.14.1.0.0
//
#ifndef AVMutableVideoCompositionLayerInstruction_h
#define AVMutableVideoCompositionLayerInstruction_h
@import Foundation;

#include "AVVideoCompositionLayerInstruction.h"

@class AVMutableVideoCompositionLayerInstructionInternal;

@interface AVMutableVideoCompositionLayerInstruction : AVVideoCompositionLayerInstruction {
  /* instance variables */
  AVMutableVideoCompositionLayerInstructionInternal *_mutableLayerInstruction;
}

@property (nonatomic) int trackID;

/* class methods */
+ (id)videoCompositionLayerInstructionWithAssetTrack:(id)track;
+ (id)videoCompositionLayerInstruction;

/* instance methods */
- (void)setTransform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })transform atTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)setTransformRampFromStartTransform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })transform toEndTransform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })transform timeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range;
- (void)setOpacity:(float)opacity atTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)setOpacityRampFromStartOpacity:(float)opacity toEndOpacity:(float)opacity timeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range;
- (void)setCropRectangle:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rectangle atTime:(struct { long long x0; int x1; unsigned int x2; long long x3; })time;
- (void)setCropRectangleRampFromStartCropRectangle:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rectangle toEndCropRectangle:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })rectangle timeRange:(struct { struct { long long x0; int x1; unsigned int x2; long long x3; } x0; struct { long long x0; int x1; unsigned int x2; long long x3; } x1; })range;
@end

#endif /* AVMutableVideoCompositionLayerInstruction_h */
