//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 617.0.0.0.0
//
#ifndef NTSection_h
#define NTSection_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "NTSectionDisplayDescriptor-Protocol.h"

@class NSOrderedSet, NSString, NSURL, NTPBSectionDisplayDescriptor, SFRankingFeedback;

@interface NTSection : NSObject<NTSectionDisplayDescriptor, NSCopying, NSSecureCoding>

@property (copy, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *subidentifier;
@property (copy, nonatomic) NSString *actionTitle;
@property (copy, nonatomic) NSURL *actionURL;
@property (copy, nonatomic) NSOrderedSet *items;
@property (copy, nonatomic) SFRankingFeedback *rankingFeedback;
@property (copy, nonatomic) NTPBSectionDisplayDescriptor *displayDescriptor;
@property (copy, nonatomic) NSString *referralBarName;
@property (copy, nonatomic) NSString *backingTagID;
@property (readonly, copy, nonatomic) NSString *personalizationFeatureID;
@property (readonly, copy, nonatomic) NSString *name;
@property (readonly, copy, nonatomic) NSString *nameColorLight;
@property (readonly, copy, nonatomic) NSString *nameColorDark;
@property (readonly, copy, nonatomic) NSURL *nameActionURL;
@property (readonly, copy, nonatomic) NSString *backgroundColorLight;
@property (readonly, copy, nonatomic) NSString *backgroundColorDark;

/* class methods */
+ (id)_itemClassesByType;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)init;
- (id)initWithIdentifier:(id)identifier subidentifier:(id)subidentifier actionTitle:(id)title actionURL:(id)url personalizationFeatureID:(id)id items:(id)items rankingFeedback:(id)feedback displayDescriptor:(id)descriptor referralBarName:(id)name backingTagID:(id)id;
- (id)description;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* NTSection_h */
