//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 513.0.0.0.0
//
#ifndef _TtC13WeatherDaemon25NoCacheWeatherDataManager_h
#define _TtC13WeatherDaemon25NoCacheWeatherDataManager_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface WeatherDaemon.NoCacheWeatherDataManager : Swift._SwiftObject { // (Swift)
  /* instance variables */
   service;
   interpolator;
   lastFetched;
   lock;
}

@end

#endif /* _TtC13WeatherDaemon25NoCacheWeatherDataManager_h */
