//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1940.42.9.28.8
//
#ifndef GEOCategorySearchResultSection_h
#define GEOCategorySearchResultSection_h
@import Foundation;

#include "GEOStyleAttributes.h"

@class NSString;

@interface GEOCategorySearchResultSection : NSObject

@property (nonatomic) long long cellType;
@property (copy, nonatomic) NSString *headerDisplayName;
@property (copy, nonatomic) NSString *subHeaderDisplayName;
@property (readonly, nonatomic) GEOStyleAttributes *styleAttributes;

/* instance methods */
- (id)init;
- (id)initWithCategorySearchResultSection:(id)section;
@end

#endif /* GEOCategorySearchResultSection_h */
