//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1940.42.9.28.8
//
#ifndef GEODataURLSessionDownloadTask_h
#define GEODataURLSessionDownloadTask_h
@import Foundation;

#include "GEODataURLSessionTask.h"

@interface GEODataURLSessionDownloadTask : GEODataURLSessionTask
/* instance methods */
- (id)_createBackingTaskWithRequest:(id)request session:(id)session;
@end

#endif /* GEODataURLSessionDownloadTask_h */
