//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1940.42.9.28.8
//
#ifndef GEOGuidanceEventFeedback_h
#define GEOGuidanceEventFeedback_h
@import Foundation;

#include "PBCodable.h"
#include "GEOJunctionViewGuidanceFeedback.h"
#include "GEOSignGuidanceFeedback.h"
#include "GEOSpokenGuidanceFeedback.h"
#include "GEOTrafficCameraInformation.h"
#include "NSCopying-Protocol.h"

@class NSData, PBDataReader;

@interface GEOGuidanceEventFeedback : PBCodable<NSCopying> {
  /* instance variables */
  PBDataReader *_reader;
  unsigned int _readerMarkPos;
  unsigned int _readerMarkLength;
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _readerLock;
  struct { unsigned int x :1 has_distanceToManeuver; unsigned int x :1 has_duration; unsigned int x :1 has_enrouteNoticeIndex; unsigned int x :1 has_eventIndex; unsigned int x :1 has_stepID; unsigned int x :1 has_timeToManeuver; unsigned int x :1 has_trafficSpeed; unsigned int x :1 has_vehicleSpeed; unsigned int x :1 read_junctionViewGuidanceFeedback; unsigned int x :1 read_routeID; unsigned int x :1 read_signGuidanceFeedback; unsigned int x :1 read_spokenGuidanceFeedback; unsigned int x :1 read_trafficCameraGuidanceFeedback; unsigned int x :1 wrote_anyField; } _flags;
}

@property (readonly, nonatomic) BOOL hasRouteID;
@property (retain, nonatomic) NSData *routeID;
@property (nonatomic) BOOL hasStepID;
@property (nonatomic) unsigned int stepID;
@property (nonatomic) BOOL hasEnrouteNoticeIndex;
@property (nonatomic) unsigned int enrouteNoticeIndex;
@property (nonatomic) BOOL hasEventIndex;
@property (nonatomic) unsigned int eventIndex;
@property (nonatomic) BOOL hasDistanceToManeuver;
@property (nonatomic) float distanceToManeuver;
@property (nonatomic) BOOL hasTimeToManeuver;
@property (nonatomic) float timeToManeuver;
@property (nonatomic) BOOL hasVehicleSpeed;
@property (nonatomic) float vehicleSpeed;
@property (nonatomic) BOOL hasTrafficSpeed;
@property (nonatomic) int trafficSpeed;
@property (nonatomic) BOOL hasDuration;
@property (nonatomic) float duration;
@property (readonly, nonatomic) BOOL hasSignGuidanceFeedback;
@property (retain, nonatomic) GEOSignGuidanceFeedback *signGuidanceFeedback;
@property (readonly, nonatomic) BOOL hasSpokenGuidanceFeedback;
@property (retain, nonatomic) GEOSpokenGuidanceFeedback *spokenGuidanceFeedback;
@property (readonly, nonatomic) BOOL hasJunctionViewGuidanceFeedback;
@property (retain, nonatomic) GEOJunctionViewGuidanceFeedback *junctionViewGuidanceFeedback;
@property (readonly, nonatomic) BOOL hasTrafficCameraGuidanceFeedback;
@property (retain, nonatomic) GEOTrafficCameraInformation *trafficCameraGuidanceFeedback;

/* class methods */
+ (BOOL)isValid:(id)valid;

/* instance methods */
- (id)init;
- (id)initWithData:(id)data;
- (id)trafficSpeedAsString:(int)string;
- (int)StringAsTrafficSpeed:(id)speed;
- (id)description;
- (id)dictionaryRepresentation;
- (id)jsonRepresentation;
- (id)initWithDictionary:(id)dictionary;
- (id)initWithJSON:(id)json;
- (void)readAll:(BOOL)all;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* GEOGuidanceEventFeedback_h */
