//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1940.42.9.28.8
//
#ifndef GEOMobileAssetResource_h
#define GEOMobileAssetResource_h
@import Foundation;

@class NSURL;

@interface GEOMobileAssetResource : NSObject {
  /* instance variables */
  long long _sandboxExtension;
}

@property (readonly, nonatomic) NSURL *fileURL;

/* instance methods */
- (id)initWithURL:(id)url sandboxExtensionData:(id)data;
- (void)dealloc;
@end

#endif /* GEOMobileAssetResource_h */
