//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1940.42.9.28.8
//
#ifndef GEOPDResultRefinementMetadataSort_h
#define GEOPDResultRefinementMetadataSort_h
@import Foundation;

#include "PBCodable.h"
#include "NSCopying-Protocol.h"

@class NSString, PBUnknownFields;

@interface GEOPDResultRefinementMetadataSort : PBCodable<NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 has_selectionFromQuerySequenceNumber; unsigned int x :1 has_serverOverriddenPosition; unsigned int x :1 has_sortType; unsigned int x :1 has_enableServerOverriddenPositioning; unsigned int x :1 has_selectionFromQuery; } _flags;
}

@property (nonatomic) BOOL hasSortType;
@property (nonatomic) int sortType;
@property (readonly, nonatomic) BOOL hasCustomSortFunctionIdentifier;
@property (retain, nonatomic) NSString *customSortFunctionIdentifier;
@property (nonatomic) BOOL hasSelectionFromQuerySequenceNumber;
@property (nonatomic) unsigned int selectionFromQuerySequenceNumber;
@property (nonatomic) BOOL hasSelectionFromQuery;
@property (nonatomic) BOOL selectionFromQuery;
@property (nonatomic) BOOL hasServerOverriddenPosition;
@property (nonatomic) unsigned int serverOverriddenPosition;
@property (nonatomic) BOOL hasEnableServerOverriddenPositioning;
@property (nonatomic) BOOL enableServerOverriddenPositioning;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;

/* class methods */
+ (BOOL)isValid:(id)valid;

/* instance methods */
- (id)sortTypeAsString:(int)string;
- (int)StringAsSortType:(id)type;
- (id)description;
- (id)dictionaryRepresentation;
- (id)jsonRepresentation;
- (id)initWithDictionary:(id)dictionary;
- (id)initWithJSON:(id)json;
- (void)readAll:(BOOL)all;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
- (void)clearUnknownFields:(BOOL)fields;
@end

#endif /* GEOPDResultRefinementMetadataSort_h */
