//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1940.42.9.28.8
//
#ifndef GEOPBTransitLine_h
#define GEOPBTransitLine_h
@import Foundation;

#include "PBCodable.h"
#include "GEOPBTransitArtwork.h"
#include "GEOPBTransitLineDisplayHints.h"
#include "GEOStyleAttributes.h"
#include "GEOTransitNamedItem-Protocol.h"
#include "NSCopying-Protocol.h"

@class NSString, PBDataReader, PBUnknownFields;

@interface GEOPBTransitLine : PBCodable<GEOTransitNamedItem, NSCopying> {
  /* instance variables */
  PBDataReader *_reader;
  unsigned long long _operatingHoursSpace;
  unsigned int _readerMarkPos;
  unsigned int _readerMarkLength;
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _readerLock;
  struct { unsigned int x :1 has_muid; unsigned int x :1 has_guidanceSnappingType; unsigned int x :1 has_lineIndex; unsigned int x :1 has_placeDisplayStyle; unsigned int x :1 has_preferredDepartureTimeStyle; unsigned int x :1 has_systemIndex; unsigned int x :1 has_transitType; unsigned int x :1 read_unknownFields; unsigned int x :1 read_operatingHours; unsigned int x :1 read_alternateArtwork; unsigned int x :1 read_artwork; unsigned int x :1 read_displayHints; unsigned int x :1 read_headerArtwork; unsigned int x :1 read_lineColor; unsigned int x :1 read_modeArtwork; unsigned int x :1 read_nameDisplayString; unsigned int x :1 read_styleAttributes; unsigned int x :1 wrote_anyField; } _flags;
}

@property (nonatomic) BOOL hasMuid;
@property (nonatomic) unsigned long long muid;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL hasLineIndex;
@property (nonatomic) unsigned int lineIndex;
@property (readonly, nonatomic) BOOL hasArtwork;
@property (retain, nonatomic) GEOPBTransitArtwork *artwork;
@property (readonly, nonatomic) BOOL hasModeArtwork;
@property (retain, nonatomic) GEOPBTransitArtwork *modeArtwork;
@property (readonly, nonatomic) BOOL hasAlternateArtwork;
@property (retain, nonatomic) GEOPBTransitArtwork *alternateArtwork;
@property (readonly, nonatomic) BOOL hasHeaderArtwork;
@property (retain, nonatomic) GEOPBTransitArtwork *headerArtwork;
@property (nonatomic) BOOL hasMuid;
@property (nonatomic) unsigned long long muid;
@property (nonatomic) BOOL hasGuidanceSnappingType;
@property (nonatomic) int guidanceSnappingType;
@property (readonly, nonatomic) BOOL hasLineColor;
@property (retain, nonatomic) NSString *lineColor;
@property (nonatomic) BOOL hasSystemIndex;
@property (nonatomic) unsigned int systemIndex;
@property (nonatomic) BOOL hasTransitType;
@property (nonatomic) int transitType;
@property (nonatomic) BOOL hasPreferredDepartureTimeStyle;
@property (nonatomic) int preferredDepartureTimeStyle;
@property (readonly, nonatomic) BOOL hasStyleAttributes;
@property (retain, nonatomic) GEOStyleAttributes *styleAttributes;
@property (readonly, nonatomic) unsigned long long operatingHoursCount;
@property (readonly, nonatomic) struct GEOPBTransitTimeRange { unsigned int x0; unsigned int x1; struct { unsigned int x0 :1; unsigned int x1 :1; } x2; } * operatingHours;
@property (readonly, nonatomic) BOOL hasDisplayHints;
@property (retain, nonatomic) GEOPBTransitLineDisplayHints *displayHints;
@property (readonly, nonatomic) BOOL hasNameDisplayString;
@property (retain, nonatomic) NSString *nameDisplayString;
@property (nonatomic) BOOL hasPlaceDisplayStyle;
@property (nonatomic) int placeDisplayStyle;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;

/* class methods */
+ (BOOL)isValid:(id)valid;

/* instance methods */
- (id)bestName;
- (id)geoTransitLineWithSystem:(id)system locationHint:(struct { double x0; double x1; })hint;
- (id)identifierWithLocationHint:(struct { double x0; double x1; })hint;
- (id)init;
- (id)initWithData:(id)data;
- (void)dealloc;
- (id)guidanceSnappingTypeAsString:(int)string;
- (int)StringAsGuidanceSnappingType:(id)type;
- (id)preferredDepartureTimeStyleAsString:(int)string;
- (int)StringAsPreferredDepartureTimeStyle:(id)style;
- (void)clearOperatingHours;
- (void)addOperatingHours:(struct GEOPBTransitTimeRange { unsigned int x0; unsigned int x1; struct { unsigned int x0 :1; unsigned int x1 :1; } x2; })hours;
- (struct GEOPBTransitTimeRange { unsigned int x0; unsigned int x1; struct { unsigned int x0 :1; unsigned int x1 :1; } x2; })operatingHoursAtIndex:(unsigned long long)index;
- (void)setOperatingHours:(struct GEOPBTransitTimeRange { unsigned int x0; unsigned int x1; struct { unsigned int x0 :1; unsigned int x1 :1; } x2; } *)hours count:(unsigned long long)count;
- (id)placeDisplayStyleAsString:(int)string;
- (int)StringAsPlaceDisplayStyle:(id)style;
- (id)dictionaryRepresentation;
- (id)jsonRepresentation;
- (id)initWithDictionary:(id)dictionary;
- (id)initWithJSON:(id)json;
- (void)readAll:(BOOL)all;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (void)mergeFrom:(id)from;
- (void)clearUnknownFields:(BOOL)fields;
@end

#endif /* GEOPBTransitLine_h */
