//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1940.42.9.28.8
//
#ifndef NSSet_GEOFunctionalExtras_h
#define NSSet_GEOFunctionalExtras_h
@import Foundation;

@interface NSSet (GEOFunctionalExtras)
/* instance methods */
- (id)_geo_filtered:(id /* block */)_geo_filtered;
@end

#endif /* NSSet_GEOFunctionalExtras_h */
