//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 818.2.23.4.1
//
#ifndef GKAuthenticationMachine_h
#define GKAuthenticationMachine_h
@import Foundation;

#include "NSCoding-Protocol.h"

@class NSString;

@interface GKAuthenticationMachine : NSObject<NSCoding>

@property (retain, nonatomic) NSString *accountName;
@property (nonatomic) long long serverEnvironment;

/* class methods */
+ (BOOL)supportsSecureCoding;
+ (id)authMachineForEnvironment:(long long)environment;
+ (void)migratePreBlacktailAccountInformation;
+ (void)migratePreSundanceAccountInformation;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* GKAuthenticationMachine_h */
