//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2904.0.0.0.0
//
#ifndef _TtC15RemindersUICoreP33_3429E123C8593E70970E33EE2D5F176554TTRShowSearchResultDataModelSourceShowCompletedContext_h
#define _TtC15RemindersUICoreP33_3429E123C8593E70970E33EE2D5F176554TTRShowSearchResultDataModelSourceShowCompletedContext_h
@import Foundation;

#include "_TtCs12_SwiftObject.h"

@interface RemindersUICore.(TTRShowSearchResultDataModelSourceShowCompletedContext in _3429E123C8593E70970E33EE2D5F1765) : Swift._SwiftObject { // (Swift)
  /* instance variables */
   showCompletedParameter;
}

@end

#endif /* _TtC15RemindersUICoreP33_3429E123C8593E70970E33EE2D5F176554TTRShowSearchResultDataModelSourceShowCompletedContext_h */
