//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3774.300.42.0.0
//
#ifndef _EFSQLInt64Binding_h
#define _EFSQLInt64Binding_h
@import Foundation;

#include "EFSQLBinding.h"

@interface _EFSQLInt64Binding : EFSQLBinding

@property (readonly, nonatomic) long long integerValue;

/* instance methods */
- (id)initWithInt64:(long long)int64;
- (void)bindTo:(struct sqlite3_stmt *)to withSQLIndex:(int)sqlindex;
@end

#endif /* _EFSQLInt64Binding_h */
