//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3774.300.42.0.0
//
#ifndef NSOrderedSet_EmailFoundationAdditions_h
#define NSOrderedSet_EmailFoundationAdditions_h
@import Foundation;

@interface NSOrderedSet (EmailFoundationAdditions)
/* instance methods */
- (id)ef_flatten;
- (id)ef_compactMap:(id /* block */)map;
- (id)ef_flatMap:(id /* block */)map;
- (id)ef_filter:(id /* block */)ef_filter;
- (id)ef_prefix:(unsigned long long)ef_prefix;
- (id)ef_suffix:(unsigned long long)ef_suffix;
- (id)ef_subsetWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)ef_subarrayWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)ef_anyPassingTest:(id /* block */)test;
- (BOOL)ef_any:(id /* block */)ef_any;
- (BOOL)ef_all:(id /* block */)ef_all;
- (unsigned long long)ef_countObjectsPassingTest:(id /* block */)test;
- (id)ef_partition:(id /* block */)ef_partition;
- (id)ef_objectBeforeObject:(id)object;
- (id)ef_objectAfterObject:(id)object;
@end

#endif /* NSOrderedSet_EmailFoundationAdditions_h */
