//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3302.16.1.0.0
//
#ifndef MTSchemaMTBatchRequestFailed_h
#define MTSchemaMTBatchRequestFailed_h
@import Foundation;

#include "SISchemaInstrumentationMessage.h"
#include "MTSchemaMTError.h"

@class NSData;

@interface MTSchemaMTBatchRequestFailed : SISchemaInstrumentationMessage {
  /* instance variables */
  struct { unsigned int x :1 numParagraphFailures; } _has;
}

@property (nonatomic) unsigned int numParagraphFailures;
@property (nonatomic) BOOL hasNumParagraphFailures;
@property (retain, nonatomic) MTSchemaMTError *error;
@property (nonatomic) BOOL hasError;
@property (readonly, nonatomic) NSData *jsonData;

/* instance methods */
- (id)suppressMessageUnderConditions;
- (id)applySensitiveConditionsPolicy:(id)policy;
- (void)deleteNumParagraphFailures;
- (void)deleteError;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)dictionaryRepresentation;
- (id)initWithJSON:(id)json;
- (id)initWithDictionary:(id)dictionary;
@end

#endif /* MTSchemaMTBatchRequestFailed_h */
