//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2206.0.5.0.0
//
#ifndef WFVariableCell_h
#define WFVariableCell_h
@import Foundation;

#include "UICollectionViewCell.h"

@class WFVariable;

@interface WFVariableCell : UICollectionViewCell

@property (retain, nonatomic) WFVariable *variable;

/* class methods */
+ (double)widthWithVariable:(id)variable height:(double)height;

/* instance methods */
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })frame;
- (void)updateVariableImage;
- (void)setHighlighted:(BOOL)highlighted;
- (BOOL)isAccessibilityElement;
- (unsigned long long)accessibilityTraits;
@end

#endif /* WFVariableCell_h */
