//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1852.4.7.0.3
//
#ifndef ARPRoutingSession_h
#define ARPRoutingSession_h
@import Foundation;

#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"

@class NSDateInterval, NSDictionary, NSString;

@interface ARPRoutingSession : NSObject<NSCopying, NSSecureCoding>

@property (readonly, copy, nonatomic) NSString *outputDeviceID;
@property (readonly, nonatomic) NSDictionary *microLocationProbabilityVector;
@property (readonly, copy, nonatomic) NSDateInterval *interval;

/* class methods */
+ (double)routingSessionTimeout;
+ (double)minimumRoutingEventDuration;
+ (double)microLocationCorrelationGracePeriod;
+ (id)routingSessionsFromNowPlayingEvents:(id)events microLocationEvents:(id)events routingSessionTimeout:(double)timeout;
+ (BOOL)supportsSecureCoding;
+ (void)writeSessions:(id)sessions routingSessionTimeout:(double)timeout file:(id)file error:(id *)error;

/* instance methods */
- (id)initWithOutputDeviceID:(id)id interval:(id)interval microLocationProbabilityVector:(id)vector;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
@end

#endif /* ARPRoutingSession_h */
