//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1235.0.0.0.0
//
#ifndef NSScanner_ContactsFoundation_h
#define NSScanner_ContactsFoundation_h
@import Foundation;

@interface NSScanner (ContactsFoundation)
/* instance methods */
- (BOOL)_cn_scanHexChar:(char *)char;
@end

#endif /* NSScanner_ContactsFoundation_h */
