//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 554.3.2.0.0
//
#ifndef RUIPageElement_h
#define RUIPageElement_h
@import Foundation;

#include "RUIElement.h"
#include "RUIPage.h"

@class NSString;

@interface RUIPageElement : RUIElement

@property (weak, nonatomic) RUIPage *page;
@property (copy, nonatomic) NSString *title;
@property (nonatomic) BOOL loading;

/* instance methods */
- (id)staticValues;
- (BOOL)isLoading;
@end

#endif /* RUIPageElement_h */
