//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 10.0.0.0.0
//
#ifndef CATTransition_h
#define CATTransition_h
@import Foundation;

#include "CATState.h"

@interface CATTransition : NSObject

@property (readonly, weak, nonatomic) CATState *state;
@property (readonly, nonatomic) SEL action;

/* class methods */
+ (id)new;

/* instance methods */
- (id)init;
- (id)initWithState:(id)state action:(SEL)action;
- (id)description;
@end

#endif /* CATTransition_h */
