//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 10.0.0.0.0
//
#ifndef NSKeyedArchiver_CATSecureCoding_h
#define NSKeyedArchiver_CATSecureCoding_h
@import Foundation;

@interface NSKeyedArchiver (CATSecureCoding)
/* class methods */
+ (id)cat_archivedDataWithRootObject:(id)object;
+ (id)cat_archivedDataWithRootObject:(id)object error:(id *)error;
@end

#endif /* NSKeyedArchiver_CATSecureCoding_h */
