//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 472.0.0.0.0
//
#ifndef REElement_h
#define REElement_h
@import Foundation;

#include "NSCoding-Protocol.h"
#include "NSCopying-Protocol.h"
#include "REAutomaticExportedInterface-Protocol.h"
#include "REContent.h"
#include "REElementAction.h"

@class NSArray, NSString;

@interface REElement : NSObject<REAutomaticExportedInterface, NSCopying, NSCoding>

@property (retain) NSString *bundleIdentifier;
@property (retain, nonatomic) NSString *applicationBundleIdentifier;
@property (readonly, nonatomic) NSString *identifier;
@property (readonly, nonatomic) unsigned long long privacyBehavior;
@property (readonly, nonatomic) REContent *content;
@property (readonly, nonatomic) REContent *idealizedContent;
@property (readonly, nonatomic) NSArray *relevanceProviders;
@property (readonly, nonatomic) REElementAction *action;
@property (readonly, nonatomic) NSString *namespacedIdentifier;

/* class methods */
+ (id)_supportedDictionaryEncodingKeys;

/* instance methods */
- (id)initWithIdentifier:(id)identifier content:(id)content idealizedContent:(id)content action:(id)action relevanceProviders:(id)providers;
- (id)initWithIdentifier:(id)identifier content:(id)content action:(id)action relevanceProviders:(id)providers;
- (id)initWithIdentifier:(id)identifier content:(id)content action:(id)action relevanceProviders:(id)providers privacyBehavior:(unsigned long long)behavior;
- (id)initWithIdentifier:(id)identifier content:(id)content idealizedContent:(id)content action:(id)action relevanceProviders:(id)providers privacyBehavior:(unsigned long long)behavior;
- (id)initWithDictionary:(id)dictionary relevanceProviderGenerator:(id)generator;
- (id)dictionaryEncodingWithRelevanceProviderGenerator:(id)generator;
- (void)finalizeContent;
- (id)copyElementWithUpdatedRelevanceProviders:(id)providers;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)shallowCopy;
- (BOOL)isNoContentElement;
- (void)_updateIdentifier:(id)identifier;
- (void)_updateNamespacedIdentifier:(id)identifier;
- (id)description;
- (unsigned long long)hash;
- (BOOL)_relevanceProvidersEqualToElement:(id)element;
- (BOOL)isEqual:(id)equal;
@end

#endif /* REElement_h */
