//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 472.0.0.0.0
//
#ifndef REMLModelManagerDataStore_Protocol_h
#define REMLModelManagerDataStore_Protocol_h
@import Foundation;

@protocol REMLModelManagerDataStore <NSObject>
/* instance methods */
- (id)dataStoreKey;
- (BOOL)modelManager:(id)manager saveDataStoreToURL:(id)url error:(id *)error;
- (BOOL)modelManager:(id)manager loadDataStoreFromURL:(id)url error:(id *)error;
@end

#endif /* REMLModelManagerDataStore_Protocol_h */
