//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 472.0.0.0.0
//
#ifndef RERelevanceEngineSubsystem_h
#define RERelevanceEngineSubsystem_h
@import Foundation;

#include "REActivityTracker.h"
#include "REActivityTrackerDelegate-Protocol.h"
#include "RERelevanceEngine.h"
#include "RERelevanceEngineSubsystemProperties-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface RERelevanceEngineSubsystem : NSObject<RERelevanceEngineSubsystemProperties, REActivityTrackerDelegate> {
  /* instance variables */
  NSObject<OS_dispatch_queue> *_relevanceEngineQueue;
  REActivityTracker *_activityTracker;
  struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (readonly, weak, nonatomic) RERelevanceEngine *relevanceEngine;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (readonly, nonatomic) BOOL running;
@property (readonly, nonatomic) NSString *name;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithRelevanceEngine:(id)engine;
- (void)dealloc;
- (BOOL)isRunning;
- (void)pause;
- (void)resume;
- (void)trackObject:(id)object;
- (void)withdrawObject:(id)object;
- (void)beginActivity:(id)activity forObject:(id)object;
- (void)endActivity:(id)activity forObject:(id)object;
- (void)activityTracker:(id)tracker didBeginActivity:(id)activity;
- (void)activityTracker:(id)tracker didEndActivity:(id)activity;
@end

#endif /* RERelevanceEngineSubsystem_h */
