//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 472.0.0.0.0
//
#ifndef RERemoteTrainingClientListener_h
#define RERemoteTrainingClientListener_h
@import Foundation;

#include "NSXPCListenerDelegate-Protocol.h"
#include "RERemoteTrainingClientListenerDelegate-Protocol.h"

@class NSMutableSet, NSString, NSXPCListener;
@protocol OS_dispatch_queue;

@interface RERemoteTrainingClientListener : NSObject<NSXPCListenerDelegate> {
  /* instance variables */
  NSMutableSet *_clients;
  NSXPCListener *_listener;
  NSObject<OS_dispatch_queue> *_queue;
}

@property (weak, nonatomic) NSObject<RERemoteTrainingClientListenerDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedTrainingClientListener;

/* instance methods */
- (id)init;
- (void)dealloc;
- (BOOL)listener:(id)listener shouldAcceptNewConnection:(id)connection;
@end

#endif /* RERemoteTrainingClientListener_h */
