//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3774.300.42.0.0
//
#ifndef MFMailMessage_h
#define MFMailMessage_h
@import Foundation;

#include "MFMessage.h"
#include "EDBaseMessage-Protocol.h"
#include "MFMailboxUid.h"
#include "MailAccount.h"

@class BOOL *, ECAngleBracketIDHash, ECMessageFlags, ECSubject, EMFollowUp, EMMessageObjectID, EMReadLater, MFMessageHeaders, NSArray, NSData, NSDate, NSDictionary, NSSet, NSString, NSURL, NSUUID;
@protocol ECMimeBody, MFMessageStore<MFMailMessageStore;

@interface MFMailMessage : MFMessage<EDBaseMessage> {
  /* instance variables */
  NSURL *_globalMessageURL;
  BOOL _useInternalSourceIsManaged;
}

@property (nonatomic) long long globalMessageID;
@property (readonly, nonatomic) EMMessageObjectID *objectID;
@property (readonly, nonatomic) MFMailboxUid *mailbox;
@property unsigned long long modSequenceNumber;
@property (nonatomic) BOOL shouldUseMailDrop;
@property (nonatomic) unsigned long long messageFlags;
@property (readonly, @dynamic, nonatomic) MFMessageHeaders *headers;
@property (readonly, nonatomic) MailAccount *account;
@property (readonly, nonatomic) BOOL read;
@property (readonly, nonatomic) BOOL deleted;
@property (retain, @dynamic, nonatomic) MFMessageStore<MFMailMessageStore> *messageStore;
@property (nonatomic) BOOL sourceIsManaged;
@property (retain, @dynamic, nonatomic) NSString *summary;
@property (readonly, copy, nonatomic) ECSubject *subjectIfAvailable;
@property (readonly, nonatomic) unsigned long long fileSize;
@property (readonly) NSDate *displayDate;
@property (readonly) NSDate *date;
@property (readonly) EMReadLater *readLater;
@property (readonly, nonatomic) EMFollowUp *followUp;
@property (readonly) NSDate *sendLaterDate;
@property (readonly, nonatomic) NSURL *brandIndicatorLocation;
@property (readonly, nonatomic) NSData *brandIndicator;
@property (readonly, copy, nonatomic) NSDictionary *dataDetectionAttributes;
@property (readonly, copy) NSArray *bccIfAvailable;
@property (readonly, copy, nonatomic) NSString *persistentID;
@property (readonly, copy, nonatomic) ECSubject *subject;
@property (readonly, copy, nonatomic) NSArray *from;
@property (readonly, copy, nonatomic) NSArray *to;
@property (readonly, copy, nonatomic) NSArray *cc;
@property (readonly, copy, nonatomic) NSArray *bcc;
@property (readonly, copy, nonatomic) NSArray *senders;
@property (readonly, nonatomic) NSDate *dateReceived;
@property (readonly, nonatomic) NSDate *dateSent;
@property (readonly, copy, nonatomic) NSArray *listUnsubscribe;
@property (readonly, copy, nonatomic) NSString *remoteID;
@property (readonly, nonatomic) long long conversationID;
@property (readonly, nonatomic) BOOL isServerSearchResult;
@property (readonly, nonatomic) ECMessageFlags *flags;
@property (readonly, nonatomic) BOOL partOfExistingThread;
@property (readonly, nonatomic) NSObject<ECMimeBody> *mimeBody;
@property (readonly, copy, nonatomic) NSDictionary *headersDictionary;
@property (readonly, copy, nonatomic) NSString *messageIDHeader;
@property (readonly, nonatomic) ECAngleBracketIDHash *messageIDHeaderHash;
@property (readonly) NSSet *labels;
@property (readonly, copy, nonatomic) NSArray *references;
@property (readonly, copy, @dynamic, nonatomic) NSUUID *documentID;
@property (readonly, nonatomic) unsigned long long numberOfAttachments;
@property (readonly, nonatomic) ECAngleBracketIDHash *listIDHash;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)forwardedMessagePrefixWithSpacer:(BOOL)spacer;
+ (Class)dataMessageStoreToUse;
+ (unsigned int)validatePriority:(int)priority;
+ (unsigned int)displayablePriorityForPriority:(int)priority;

/* instance methods */
- (id)mailMessageStore;
- (void)setMessageFlagsWithoutCommitting:(unsigned long long)committing;
- (void)setPriorityFromHeaders:(id)headers;
- (int)priority;
- (void)loadCachedHeaderValuesFromHeaders:(id)headers;
- (void)markAsViewed;
- (void)markAsNotViewed;
- (void)markAsReplied;
- (void)markAsForwarded;
- (void)markAsFlagged;
- (void)markAsNotFlagged;
- (id)preferredAccountToUseForReplying;
- (id)preferredEmailAddressToReplyWith;
- (id)loadMeetingExternalID;
- (id)loadMeetingData;
- (id)loadMeetingMetadata;
- (id)remoteMailboxURL;
- (unsigned long long)conversationFlags;
- (void)setConversationFlags:(unsigned long long)flags;
- (id)originalMailboxURL;
- (id)URL;
- (id)globalMessageURL;
- (void)setMutableInfoFromMessage:(id)message;
- (void)setSubject:(id)subject to:(id)to cc:(id)cc bcc:(id)bcc sender:(id)sender dateReceived:(double)received dateSent:(double)sent summary:(id)summary withOptions:(unsigned int)options;
- (BOOL)shouldSetSummary;
- (id)externalConversationID;
- (id)bestAlternativePart;
- (id)bestAlternativePart:(BOOL *)part;
- (id)_bestAlternativePartContent:(BOOL *)content;
- (id)bestAlternativePartAsData:(BOOL *)data usingEncoding:(unsigned long long)encoding;
- (BOOL)isSearchResultWithBogusRemoteId;
- (id)storageLocationForAttachment:(id)attachment;
- (BOOL)flagged;
- (BOOL)answered;
- (BOOL)junk;
- (BOOL)conversationVIP;
- (BOOL)conversationMuted;
- (BOOL)isPartOfExistingThread;
- (long long)conversationHash;
- (long long)libraryID;
@end

#endif /* MFMailMessage_h */
