//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 252.9.0.0.0
//
#ifndef _LTOfflineAssetManager_h
#define _LTOfflineAssetManager_h
@import Foundation;

#include "_LTHotfixManager.h"

@interface _LTOfflineAssetManager : NSObject {
  /* instance variables */
  _LTHotfixManager *_hotfixMgr;
}

/* class methods */
+ (void)initialize;
+ (id)assetDirectory;
+ (id)fallBackAssetResourcePath;

/* instance methods */
- (id)init;
- (void)_refreshAllAssets:(id /* block */)assets;
- (void)refreshAllIfNeededWithCompletion:(id /* block */)completion;
- (void)removeObsoleteAssets;
- (void)_queryLanguagePairStatusWithCompletion:(id /* block */)completion;
- (void)deleteAsset:(id)asset completion:(id /* block */)completion;
- (void)offlineLanguageStatus:(id /* block */)status;
- (void)_removeOldAssetDirectory;
- (id)_assetIdentifiersForLanguagePairDirectory:(id)directory;
- (id)assetIdentifierReferenceCountDictionary;
- (void)purgeAssetForLanguagePair:(id)pair userInitiated:(BOOL)initiated completion:(id /* block */)completion;
- (void)purgeAllAssetsExcludingConfig:(BOOL)config completion:(id /* block */)completion;
- (void)debugDumpAssets:(id)assets;
- (void)_updateAsset:(id)asset catalogAssets:(id)assets downloadGroup:(id)group completion:(id /* block */)completion;
- (void)updateAllAssets:(id /* block */)assets;
- (void)updateSpeechTranslationAssetSymLinks:(id)links;
- (void)_downloadPassthroughAssetForLocale:(id)locale userInitiated:(BOOL)initiated completion:(id /* block */)completion;
- (void)downloadAssetsForLanguagePair:(id)pair userInitiated:(BOOL)initiated completion:(id /* block */)completion;
- (id)modelURLsForLanguagePair:(id)pair;
- (id)speechTranslationAssetInfoForLocalePair:(id)pair error:(id *)error;
- (id)_speechTranslationAssetInfoForLocalePair:(id)pair error:(id *)error;
- (id)_speechTranslationAssetInfoForLocalePair:(id)pair installedAssets:(id)assets catalogAssets:(id)assets offlineConfig:(id)config error:(id *)error;
- (id)getEndpointerAssetWithType:(unsigned long long)type error:(id *)error;
- (id)endpointAssetInfoWithContext:(id)context error:(id *)error;
- (id)languageDetectorAssetWithError:(id *)error;
- (void)assetSize:(id /* block */)size;
@end

#endif /* _LTOfflineAssetManager_h */
