//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 252.9.0.0.0
//
#ifndef FTAsrService_h
#define FTAsrService_h
@import Foundation;

#include "OspreyChannel.h"

@interface FTAsrService : OspreyChannel
/* instance methods */
- (id)performRecognitionWithDelegate:(id)delegate requestBuilder:(id /* block */)builder completion:(id /* block */)completion;
- (void)performErrorBlamer:(id)blamer requestBuilder:(id /* block */)builder completion:(id /* block */)completion;
- (void)performItn:(id)itn requestBuilder:(id /* block */)builder completion:(id /* block */)completion;
- (void)performTextNormalization:(id)normalization requestBuilder:(id /* block */)builder completion:(id /* block */)completion;
- (void)performPostItnHammer:(id)hammer requestBuilder:(id /* block */)builder completion:(id /* block */)completion;
- (void)performKeywordFinder:(id)finder requestBuilder:(id /* block */)builder completion:(id /* block */)completion;
- (void)performCorrectionsValidator:(id)validator requestBuilder:(id /* block */)builder completion:(id /* block */)completion;
- (void)performGraphemeToPhoneme:(id)phoneme requestBuilder:(id /* block */)builder completion:(id /* block */)completion;
@end

#endif /* FTAsrService_h */
