//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 252.9.0.0.0
//
#ifndef FTMutableTextToSpeechSpeechFeatureInputPhonemeSequence_h
#define FTMutableTextToSpeechSpeechFeatureInputPhonemeSequence_h
@import Foundation;

#include "FTTextToSpeechSpeechFeatureInputPhonemeSequence.h"

@class NSArray;

@interface FTMutableTextToSpeechSpeechFeatureInputPhonemeSequence : FTTextToSpeechSpeechFeatureInputPhonemeSequence

@property (copy, nonatomic) NSArray *phonemeseq;

/* instance methods */
- (id)init;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* FTMutableTextToSpeechSpeechFeatureInputPhonemeSequence_h */
