//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 123.2.7.0.1
//
#ifndef BPSDirectAssocationCorrelateHandler_h
#define BPSDirectAssocationCorrelateHandler_h
@import Foundation;

#include "BPSCorrelateHandler.h"

@interface BPSDirectAssocationCorrelateHandler : BPSCorrelateHandler {
  /* instance variables */
  id /* block */ _correlating;
}

/* instance methods */
- (id)initWithCorrelating:(id /* block */)correlating;
- (void)receivePriorEvent:(id)event;
- (void)receiveCurrentEvent:(id)event;
- (id)correlateWithCurrentEvent:(id)event;
@end

#endif /* BPSDirectAssocationCorrelateHandler_h */
