//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 730.8.0.0.0
//
#ifndef CUMFiReadRequest_h
#define CUMFiReadRequest_h
@import Foundation;

#include "CUMFiReadRequest.h"

@interface CUMFiReadRequest : NSObject {
  /* instance variables */
  unsigned long long minLen;
  unsigned long long maxLen;
  CUMFiReadRequest *next;
}

@property (copy, nonatomic) id /* block */ completion;

/* instance methods */
@end

#endif /* CUMFiReadRequest_h */
