//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.5.0.0
//
#ifndef ICDelegationConsumerNetService_h
#define ICDelegationConsumerNetService_h
@import Foundation;

#include "ICDelegationConsumerNetServiceDelegate-Protocol.h"
#include "ICDelegationServiceSecuritySettings.h"
#include "NSNetServiceDelegate-Protocol.h"

@class NSDictionary, NSNetService, NSString;
@protocol OS_dispatch_queue;

@interface ICDelegationConsumerNetService : NSObject<NSNetServiceDelegate> {
  /* instance variables */
  NSObject<OS_dispatch_queue> *_accessQueue;
  NSObject<OS_dispatch_queue> *_calloutQueue;
  BOOL _didPublish;
  BOOL _isPublished;
  NSNetService *_netService;
  NSObject<OS_dispatch_queue> *_netServiceQueue;
}

@property (weak, nonatomic) NSObject<ICDelegationConsumerNetServiceDelegate> *delegate;
@property (readonly, copy, nonatomic) NSDictionary *userIdentityDelegationAccountUUIDs;
@property (readonly, nonatomic) ICDelegationServiceSecuritySettings *securitySettings;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithUserIdentityDelegationAccountUUIDs:(id)uuids;
- (void)dealloc;
- (void)netService:(id)service didAcceptConnectionWithInputStream:(id)stream outputStream:(id)stream;
- (void)netServiceDidPublish:(id)publish;
- (void)netService:(id)service didNotPublish:(id)publish;
- (void)publish;
- (void)stop;
- (void)_updateNetServiceStatus;
@end

#endif /* ICDelegationConsumerNetService_h */
