//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.5.0.0
//
#ifndef ICDelegationPlayInfoRequestOperation_h
#define ICDelegationPlayInfoRequestOperation_h
@import Foundation;

#include "ICAsyncOperation.h"
#include "ICDelegationPlayInfoRequest.h"
#include "ICDelegationPlayInfoRequestOperation.h"
#include "ICStoreRequestContext.h"

@interface ICDelegationPlayInfoRequestOperation : ICAsyncOperation {
  /* instance variables */
  ICDelegationPlayInfoRequestOperation *_strongSelf;
}

@property (copy, nonatomic) ICDelegationPlayInfoRequest *playInfoRequest;
@property (retain, nonatomic) ICStoreRequestContext *storeRequestContext;
@property (copy, nonatomic) id /* block */ responseHandler;

/* instance methods */
- (void)finishWithResponse:(id)response requestDate:(id)date error:(id)error;
- (void)execute;
- (void)finishWithError:(id)error;
- (void)_finishWithResult:(BOOL)result tokens:(id)tokens error:(id)error;
@end

#endif /* ICDelegationPlayInfoRequestOperation_h */
