//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4023.330.5.0.0
//
#ifndef ICLiveLinkEvent_h
#define ICLiveLinkEvent_h
@import Foundation;

#include "ICLiveLinkCustomEvent.h"
#include "ICLiveLinkIdentity.h"
#include "ICLiveLinkPlaybackEvent.h"
#include "ICLiveLinkQueueEvent.h"
#include "ICLiveLinkReactionEvent.h"
#include "ICLiveLinkSessionEvent.h"

@class NSString;

@interface ICLiveLinkEvent : NSObject

@property (readonly, nonatomic) ICLiveLinkIdentity *participant;
@property (readonly, nonatomic) long long type;
@property (readonly, nonatomic) ICLiveLinkSessionEvent *sessionEvent;
@property (readonly, nonatomic) ICLiveLinkPlaybackEvent *playbackEvent;
@property (readonly, nonatomic) ICLiveLinkQueueEvent *queueEvent;
@property (readonly, nonatomic) ICLiveLinkReactionEvent *reactionEvent;
@property (readonly, nonatomic) ICLiveLinkCustomEvent *customEvent;
@property (readonly, copy, nonatomic) NSString *primaryReferencedIdentifier;

/* class methods */
+ (id)eventWithSessionEvent:(id)event participant:(id)participant;
+ (id)eventWithPlaybackEvent:(id)event participant:(id)participant;
+ (id)eventWithQueueEvent:(id)event participant:(id)participant;
+ (id)eventWithReactionEvent:(id)event participant:(id)participant;
+ (id)eventWithCustomEvent:(id)event participant:(id)participant;

/* instance methods */
- (id)_initWithType:(long long)type participant:(id)participant;
- (id)description;
@end

#endif /* ICLiveLinkEvent_h */
