//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3774.300.42.0.0
//
#ifndef EDExistingMessageWithMessageIDHeader_h
#define EDExistingMessageWithMessageIDHeader_h
@import Foundation;

@class ECAngleBracketIDHash, ECServerMessage;

@interface EDExistingMessageWithMessageIDHeader : NSObject

@property (readonly, nonatomic) ECAngleBracketIDHash *messageIDHash;
@property (readonly, nonatomic) ECServerMessage *serverMessage;
@property (readonly, nonatomic) long long messagePersistentID;

/* instance methods */
- (id)initWithMessageIDHash:(id)idhash serverMessage:(id)message messagePersistentID:(long long)id;
@end

#endif /* EDExistingMessageWithMessageIDHeader_h */
