//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3774.300.42.0.0
//
#ifndef EDServer_h
#define EDServer_h
@import Foundation;

#include "EDDaemonInterfaceFactory.h"
#include "EDReconciliationQueryProvider-Protocol.h"
#include "EDServerRemoteClientsProvider-Protocol.h"
#include "EFLoggable-Protocol.h"
#include "NSXPCListenerDelegate-Protocol.h"

@class EFLocked, NSArray, NSString, NSXPCListener, NSXPCListenerEndpoint;

@interface EDServer : NSObject<NSXPCListenerDelegate, EDServerRemoteClientsProvider, EFLoggable, EDReconciliationQueryProvider>

@property (retain, nonatomic) NSXPCListener *listener;
@property (readonly, nonatomic) EFLocked *connectedClients;
@property (retain, nonatomic) EDDaemonInterfaceFactory *daemonInterfaceFactory;
@property (readonly, nonatomic) NSXPCListenerEndpoint *serverXPCEndpoint;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy, nonatomic) NSArray *remoteClients;

/* class methods */
+ (id)log;

/* instance methods */
- (id)initWithDaemonInterfaceFactory:(id)factory;
- (id)initWithDaemonInterfaceFactory:(id)factory listener:(id)listener;
- (void)test_tearDown;
- (void)start;
- (BOOL)listener:(id)listener shouldAcceptNewConnection:(id)connection;
- (void)addRemoteClient:(id)client;
- (void)removeRemoteClient:(id)client;
- (id)messageReconciliationQueries;
- (id)threadReconciliationQueries;
@end

#endif /* EDServer_h */
