//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HKMCViewModelProvider_h
#define HKMCViewModelProvider_h
@import Foundation;

#include "HKMCAnalysis.h"
#include "HKMCAnalysisProvider.h"
#include "HKMCAnalysisProviderObserver-Protocol.h"
#include "HKMCViewModelProviderDataSource-Protocol.h"
#include "HKMCViewModelProviderDataSourceDelegate-Protocol.h"

@class HKCalendarCache, NSArray, NSHashTable, NSMutableDictionary, NSMutableIndexSet, NSNumber, NSString, _HKDelayedOperation;
@protocol OS_dispatch_queue;

@interface HKMCViewModelProvider : NSObject<HKMCViewModelProviderDataSourceDelegate, HKMCAnalysisProviderObserver> {
  /* instance variables */
  NSObject<HKMCViewModelProviderDataSource> *_dataSource;
  HKMCAnalysisProvider *_analysisProvider;
  NSHashTable *_observers;
  NSObject<OS_dispatch_queue> *_queue;
  BOOL _shouldFetchCycleFactors;
  long long _prefetchDuration;
  struct { long long start; long long duration; } _managedDayRange;
  NSMutableIndexSet *_fetchStartedDayIndexes;
  NSMutableIndexSet *_fetchCompletedDayIndexes;
  NSMutableDictionary *_daySummariesByDayIndex;
  NSArray *_cycleFactors;
  NSNumber *_minimumAnalysisAnchor;
  HKMCAnalysis *_analysis;
  _HKDelayedOperation *_notifyObserversOperation;
}

@property (nonatomic) long long maximumActiveDuration;
@property (readonly, nonatomic) HKCalendarCache *calendarCache;
@property (nonatomic) struct { long long x0; long long x1; } activeDayRange;
@property (readonly, nonatomic) long long minimumBufferDuration;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)setActiveCycles:(id)cycles;
- (id)initWithHealthStore:(id)store analysisProvider:(id)provider maximumActiveDuration:(long long)duration minimumBufferDuration:(long long)duration shouldFetchCycleFactors:(BOOL)factors calendarCache:(id)cache;
- (id)initWithHealthStore:(id)store analysisProvider:(id)provider maximumActiveDuration:(long long)duration minimumBufferDuration:(long long)duration shouldFetchCycleFactors:(BOOL)factors calendarCache:(id)cache queue:(id)queue;
- (id)_initWithDataSource:(id)source analysisProvider:(id)provider maximumActiveDuration:(long long)duration minimumBufferDuration:(long long)duration prefetchDuration:(long long)duration shouldFetchCycleFactors:(BOOL)factors calendarCache:(id)cache queue:(id)queue;
- (id)copyWithMinimumBufferDuration:(long long)duration;
- (id)_copyWithDataSource:(id)source minimumBufferDuration:(long long)duration;
- (id)dayViewModelAtIndex:(long long)index;
- (id)_viewModelWithDayIndex:(long long)index fetchedDaySummary:(id)summary;
- (unsigned long long)_menstruationLevelWithDayIndex:(long long)index menstrualFlow:(long long)flow partiallyLoggedPeriod:(BOOL *)period;
- (unsigned long long)_fertileWindowLevelWithDayIndex:(long long)index;
- (void)_updateManagedDayRangeIfNeeded;
- (long long)_fetchStateForDayIndex:(long long)index;
- (void)_setFetchState:(long long)state forDayIndexRange:(struct { long long x0; long long x1; })range;
- (BOOL)_didFetchInitialAnalysis;
- (BOOL)_didFetchMinimumAnalysis;
- (void)viewModelProviderDataSource:(id)source didFetchDaySummaries:(id)summaries forDayIndexRange:(struct { long long x0; long long x1; })range daySummaryAnchor:(id)anchor;
- (void)viewModelProviderDataSource:(id)source didFetchCycleFactors:(id)factors forDayIndexRange:(struct { long long x0; long long x1; })range;
- (void)viewModelProviderDataSourceDidUpdateDaySummaries:(id)summaries;
- (void)viewModelProviderDataSourceDidUpdateCycleFactors:(id)factors;
- (void)analysisProvider:(id)provider didUpdateAnalysis:(id)analysis;
- (void)registerObserver:(id)observer;
- (void)removeObserver:(id)observer;
- (void)_queue_notifyObserversDidUpdate;
- (void)_queue_runNotifyObserversOperationNow;
- (struct { long long x0; long long x1; })_test_managedDayRange;
- (BOOL)_ppt_didFetchAnalysis;
- (BOOL)_ppt_didFetchDaySummaries;
@end

#endif /* HKMCViewModelProvider_h */
