//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 2298.42.9.28.5
//
#ifndef MNTrace_h
#define MNTrace_h
@import Foundation;

@class NSArray, NSDate, NSDictionary, NSMutableArray, NSString;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface MNTrace : NSObject {
  /* instance variables */
  NSMutableArray *_preparedStatements;
}

@property (readonly, nonatomic) struct sqlite3 * db;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *writeQueue;
@property (readonly, nonatomic) NSObject<OS_dispatch_group> *writeGroup;
@property (nonatomic) unsigned long long version;
@property (nonatomic) unsigned long long originalVersion;
@property (nonatomic) BOOL isSimulation;
@property (retain, nonatomic) NSDate *recordingStartDate;
@property (retain, nonatomic) NSDate *directionsStartDate;
@property (retain, nonatomic) NSDate *navigationStartDate;
@property (retain, nonatomic) NSDate *navigationEndDate;
@property (retain, nonatomic) NSArray *locations;
@property (retain, nonatomic) NSArray *directions;
@property (retain, nonatomic) NSArray *etaUpdates;
@property (retain, nonatomic) NSArray *headingData;
@property (retain, nonatomic) NSArray *motionData;
@property (retain, nonatomic) NSArray *vehicleHeadingData;
@property (retain, nonatomic) NSArray *vehicleSpeedData;
@property (retain, nonatomic) NSArray *evData;
@property (retain, nonatomic) NSArray *navigationEvents;
@property (retain, nonatomic) NSArray *annotatedUserBehavior;
@property (retain, nonatomic) NSArray *annotatedUserEnvironments;
@property (retain, nonatomic) NSArray *navigationUpdates;
@property (retain, nonatomic) NSArray *networkEvents;
@property (retain, nonatomic) NSArray *bookmarks;
@property (retain, nonatomic) NSArray *bookmarkImages;
@property (retain, nonatomic) NSDictionary *miscInfo;
@property (readonly, nonatomic) NSString *tracePath;
@property (readonly, nonatomic) int mainTransportType;

/* instance methods */
- (id)serializableBookmarks;
- (id)init;
- (void)dealloc;
- (BOOL)openTrace:(id)trace outError:(id *)error;
- (BOOL)startWritingTraceToPath:(id)path;
- (BOOL)closeTrace;
- (id)dateFromTimestamp:(double)timestamp;
- (id)_handleOpenErrorWithPath:(id)path;
- (id)prepareStatement:(id)statement outError:(out id *)error;
@end

#endif /* MNTrace_h */
