//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 707.0.47.0.0
//
#ifndef SRSensorKitServiceServerPruning_Protocol_h
#define SRSensorKitServiceServerPruning_Protocol_h
@import Foundation;

@protocol SRSensorKitServiceServerPruning 
/* instance methods */
- (void)startPruningForSensor:(id)sensor deviceId:(id)id;
- (void)requestFileHandleForPruningSample:(double)sample reply:(id /* block */)reply;
- (void)requestFileHandleForPruningAfterSegment:(id)segment reply:(id /* block */)reply;
- (void)removeAllSamplesForCurrentSensorWithReply:(id /* block */)reply;
- (void)removeAllSamplesForAllSensorsWithReply:(id /* block */)reply;
@end

#endif /* SRSensorKitServiceServerPruning_Protocol_h */
