//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 573.2.0.0.0
//
#ifndef ACHBackCompatMonthlyChallengeListener_h
#define ACHBackCompatMonthlyChallengeListener_h
@import Foundation;

#include "ACHTemplateStore.h"
#include "HDDatabaseProtectedDataObserver-Protocol.h"
#include "HDHealthDaemonReadyObserver-Protocol.h"

@class HDProfile, NSDictionary, NSString;

@interface ACHBackCompatMonthlyChallengeListener : NSObject<HDHealthDaemonReadyObserver, HDDatabaseProtectedDataObserver>

@property (weak, nonatomic) HDProfile *profile;
@property (weak, nonatomic) ACHTemplateStore *templateStore;
@property (copy, nonatomic) id /* block */ readTemplatesBlock;
@property (retain, nonatomic) NSDictionary *injectedKeyValuePairs;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithProfile:(id)profile templateStore:(id)store;
- (void)daemonReady:(id)ready;
- (void)database:(id)database protectedDataDidBecomeAvailable:(BOOL)available;
- (void)_protectedNanoUserDefaultsDidSyncWithNotification:(id)notification;
- (BOOL)_readAndSaveBackCompatDefinitions;
- (id)_definitionsFromKeyValuePairs:(id)pairs;
@end

#endif /* ACHBackCompatMonthlyChallengeListener_h */
