//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 171.0.0.0.0
//
#ifndef CEMDeviceInformationCommand_StatusQueryResponsesAutoSetupAdminAccountsItem_h
#define CEMDeviceInformationCommand_StatusQueryResponsesAutoSetupAdminAccountsItem_h
@import Foundation;

#include "CEMPayloadBase.h"

@class NSString;

@interface CEMDeviceInformationCommand_StatusQueryResponsesAutoSetupAdminAccountsItem : CEMPayloadBase

@property (copy, nonatomic) NSString *statusGUID;
@property (copy, nonatomic) NSString *statusShortName;

/* class methods */
+ (id)allowedStatusKeys;
+ (id)buildWithGUID:(id)guid withShortName:(id)name;
+ (id)buildRequiredOnly;

/* instance methods */
- (BOOL)loadPayload:(id)payload error:(id *)error;
- (id)serializePayload;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* CEMDeviceInformationCommand_StatusQueryResponsesAutoSetupAdminAccountsItem_h */
