//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 171.0.0.0.0
//
#ifndef CEMPasscodeSettingsDeclaration_h
#define CEMPasscodeSettingsDeclaration_h
@import Foundation;

#include "CEMConfigurationBase.h"
#include "CEMRegisteredTypeProtocol-Protocol.h"

@class NSNumber, NSString;

@interface CEMPasscodeSettingsDeclaration : CEMConfigurationBase<CEMRegisteredTypeProtocol>

@property (copy, nonatomic) NSNumber *payloadAllowSimple;
@property (copy, nonatomic) NSNumber *payloadForcePIN;
@property (copy, nonatomic) NSNumber *payloadMaxFailedAttempts;
@property (copy, nonatomic) NSNumber *payloadMaxInactivity;
@property (copy, nonatomic) NSNumber *payloadMaxPINAgeInDays;
@property (copy, nonatomic) NSNumber *payloadMinComplexChars;
@property (copy, nonatomic) NSNumber *payloadMinLength;
@property (copy, nonatomic) NSNumber *payloadRequireAlphanumeric;
@property (copy, nonatomic) NSNumber *payloadPinHistory;
@property (copy, nonatomic) NSNumber *payloadMaxGracePeriod;
@property (copy, nonatomic) NSNumber *payloadMinutesUntilFailedLoginReset;
@property (copy, nonatomic) NSNumber *payloadChangeAtNextAuth;
@property (copy, nonatomic) NSNumber *payloadManualFetchingWhenRoaming;
@property (copy, nonatomic) NSNumber *payloadAllowFingerprintForUnlock;
@property (copy, nonatomic) NSNumber *payloadAllowFingerprintModification;
@property (copy, nonatomic) NSNumber *payloadAllowPasscodeModification;
@property (copy, nonatomic) NSNumber *payloadAllowAutoUnlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)registeredClassName;
+ (id)registeredIdentifier;
+ (id)profileType;
+ (id)allowedPayloadKeys;
+ (id)restrictionPayloadKeys;
+ (id)buildWithIdentifier:(id)identifier withAllowSimple:(id)simple withForcePIN:(id)pin withMaxFailedAttempts:(id)attempts withMaxInactivity:(id)inactivity withMaxPINAgeInDays:(id)days withMinComplexChars:(id)chars withMinLength:(id)length withRequireAlphanumeric:(id)alphanumeric withPinHistory:(id)history withMaxGracePeriod:(id)period withMinutesUntilFailedLoginReset:(id)reset withChangeAtNextAuth:(id)auth withManualFetchingWhenRoaming:(id)roaming withAllowFingerprintForUnlock:(id)unlock withAllowFingerprintModification:(id)modification withAllowPasscodeModification:(id)modification withAllowAutoUnlock:(id)unlock;
+ (id)buildRequiredOnlyWithIdentifier:(id)identifier;

/* instance methods */
- (BOOL)multipleAllowed;
- (BOOL)mustBeSupervised;
- (int)activationLevel;
- (id)assetReferences;
- (BOOL)loadPayload:(id)payload error:(id *)error;
- (id)serializePayloadWithAssetProviders:(id)providers;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* CEMPasscodeSettingsDeclaration_h */
