//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3302.18.2.0.0
//
#ifndef SFTableRowCardSection_Protocol_h
#define SFTableRowCardSection_Protocol_h
@import Foundation;

#include "SFCardSection.h"
#include "NSCopying-Protocol.h"
#include "NSSecureCoding-Protocol.h"
#include "SFCard.h"
#include "SFColor.h"
#include "SFCommand.h"
#include "SFTableAlignmentSchema.h"
#include "SFTableRowCardSection-Protocol.h"
#include "SFUserReportRequest.h"

@class NSArray, NSData, NSDictionary, NSString;

@protocol SFTableRowCardSection <SFCardSection>

@property (copy, nonatomic) NSString *type;
@property (copy, nonatomic) NSArray *richData;
@property (copy, nonatomic) NSString *tableIdentifier;
@property (retain, nonatomic) SFTableAlignmentSchema *alignmentSchema;
@property (copy, nonatomic) NSArray *data;
@property (nonatomic) BOOL isSubHeader;
@property (copy, nonatomic) NSString *tabGroupIdentifier;
@property (nonatomic) BOOL reducedRowHeight;
@property (nonatomic) int verticalAlign;
@property (nonatomic) BOOL alignRowsToHeader;
@property (readonly, nonatomic) NSDictionary *dictionaryRepresentation;
@property (readonly, nonatomic) NSData *jsonData;

@end

#endif /* SFTableRowCardSection_Protocol_h */
