//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1481.40.16.0.0
//
#ifndef OSLogEventBacktrace_h
#define OSLogEventBacktrace_h
@import Foundation;

@class NSArray;

@interface OSLogEventBacktrace : NSObject

@property (readonly, nonatomic) NSArray *frames;

/* instance methods */
- (id)initWithBacktrace:(struct os_log_backtrace_s { struct os_log_backtrace_frame_s * x0; int x1; } *)backtrace;
- (id)initWithSingleFrame:(id)frame;
- (id)initWithFrames:(id)frames;
- (void)dealloc;
@end

#endif /* OSLogEventBacktrace_h */
