//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3093.2.4.4.10
//
#ifndef AXSettingsPrimaryResourceDownloadController_h
#define AXSettingsPrimaryResourceDownloadController_h
@import Foundation;

#include "AXSettingsResourceDownloadController.h"

@class AXLangMap, NSLock, NSMutableArray, NSString, UIActivityIndicatorView, UISlider, UIView;
@protocol OS_dispatch_queue;

@interface AXSettingsPrimaryResourceDownloadController : AXSettingsResourceDownloadController {
  /* instance variables */
  BOOL _receivedCompactAnswer;
  long long _storageSize;
  BOOL _isDownloading;
  BOOL _wantsDownload;
  BOOL _wantsDelete;
  BOOL _receivedIsDownloading;
  NSString *_languageBeingDownloaded;
  NSObject<OS_dispatch_queue> *_loadVoiceFootprintsQueue;
  NSLock *_voiceFootprintLock;
  BOOL _loadingVoiceFootprints;
  UISlider *_speechRateSlider;
}

@property (retain, nonatomic) AXLangMap *languageMap;
@property (retain, nonatomic) NSMutableArray *voiceFootprints;
@property (retain, nonatomic) UIActivityIndicatorView *progressIndicator;
@property (retain, nonatomic) UIView *loadingView;
@property (retain, nonatomic) NSString *language;
@property (@dynamic, nonatomic) BOOL showSpeakingRate;
@property (nonatomic) float speakingRate;
@property (retain, nonatomic) Class speakingRateSliderCell;
@property (nonatomic) BOOL showDialectPicker;
@property (nonatomic) BOOL showDialectInTitle;
@property (nonatomic) BOOL showNeural;
@property (nonatomic) BOOL showNeuralAX;
@property (nonatomic) BOOL showPersonalVoices;
@property (nonatomic) BOOL hideLanguageInDialect;
@property (copy, nonatomic) id /* block */ setSpeakingRateCallback;
@property (copy, nonatomic) id /* block */ getSpeakingRateCallback;

/* instance methods */
- (id)init;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)appear;
- (void)dealloc;
- (void)_updateSpeakingRate;
- (id)_getSelectedVariation:(id)variation;
- (void)createVoiceFootprints;
- (void)addVoiceFootprintsToArray:(id)array forDialect:(id)dialect;
- (void)_setSpeakingRate:(id)rate specifier:(id)specifier;
- (id)_speakingRate:(id)rate;
- (void)setSpeakingRateCallbackBlock:(id /* block */)block;
- (void)_prepareVoiceFootprints;
- (void)setConfigurationSpecifier:(id)specifier;
- (void)setSpecifierSet:(id)set;
- (id)specifiers;
- (id)collectionView:(id)view cellForItemAtIndexPath:(id)path;
- (id)_internalSpecifiers;
@end

#endif /* AXSettingsPrimaryResourceDownloadController_h */
