//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3093.2.4.4.10
//
#ifndef AXUIVoiceOverBluetoothDeviceTableCell_h
#define AXUIVoiceOverBluetoothDeviceTableCell_h
@import Foundation;

#include "PSTableCell.h"

@class UIActivityIndicatorView;

@interface AXUIVoiceOverBluetoothDeviceTableCell : PSTableCell {
  /* instance variables */
  UIActivityIndicatorView *_spinner;
  int _state;
}

/* class methods */
+ (id)spacerImage;
+ (id)checkedImage;
+ (id)selectedCheckedImage;
+ (id)textForBTPairedState:(int)state;

/* instance methods */
- (id)initWithStyle:(long long)style reuseIdentifier:(id)identifier specifier:(id)specifier;
- (void)dealloc;
- (void)setChecked:(BOOL)checked;
- (void)setDeviceState:(int)state;
- (void)setDeviceStatePaired:(BOOL)paired andConnected:(BOOL)connected;
- (void)layoutSubviews;
- (void)refreshCellContentsWithSpecifier:(id)specifier;
- (void)_updateCheckMarkIcon;
@end

#endif /* AXUIVoiceOverBluetoothDeviceTableCell_h */
