//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 205.6.1.0.0
//
#ifndef VCPCoreMLFeatureProviderGesture_h
#define VCPCoreMLFeatureProviderGesture_h
@import Foundation;

#include "MLFeatureProvider-Protocol.h"
#include "VCPHandObservation.h"

@class NSSet;

@interface VCPCoreMLFeatureProviderGesture : NSObject<MLFeatureProvider> {
  /* instance variables */
  VCPHandObservation *_observation;
}

@property int rotationInDegrees;
@property (readonly, nonatomic) NSSet *featureNames;

/* instance methods */
- (id)initWith:(id)with rotationInDegrees:(int)degrees;
- (id)featureValueForName:(id)name;
@end

#endif /* VCPCoreMLFeatureProviderGesture_h */
