//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 4146.2.12.2.2
//
#ifndef HDSPTimeChangeListener_h
#define HDSPTimeChangeListener_h
@import Foundation;

#include "HDSPEnvironment.h"
#include "HDSPEnvironmentAware-Protocol.h"
#include "HDSPNotificationObserver-Protocol.h"
#include "HDSPSource-Protocol.h"

@class HKSPObserverSet, NSString;

@interface HDSPTimeChangeListener : NSObject<HDSPNotificationObserver, HDSPEnvironmentAware, HDSPSource>

@property (readonly, nonatomic) HKSPObserverSet *observers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, weak, nonatomic) HDSPEnvironment *environment;
@property (readonly, nonatomic) NSString *sourceIdentifier;
@property (readonly, nonatomic) BOOL dontNotify;
@property (readonly, nonatomic) BOOL dontSync;

/* instance methods */
- (id)initWithEnvironment:(id)environment;
- (void)addObserver:(id)observer;
- (void)removeObserver:(id)observer;
- (void)environmentWillBecomeReady:(id)ready;
- (void)environmentDidBecomeReady:(id)ready;
- (id)notificationListener:(id)listener didReceiveNotificationWithName:(id)name;
- (void)handleSignificantTimeChange;
- (void)handleTimeZoneChange;
@end

#endif /* HDSPTimeChangeListener_h */
