//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef AWDHomeKitMessageHomeLocationReport_h
#define AWDHomeKitMessageHomeLocationReport_h
@import Foundation;

#include "PBCodable.h"
#include "AWDHomeKitMessageLocation.h"
#include "NSCopying-Protocol.h"

@class NSMutableArray;

@interface AWDHomeKitMessageHomeLocationReport : PBCodable<NSCopying> {
  /* instance variables */
  struct { unsigned int x :1 timestamp; unsigned int x :1 numIterationToConverge; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (retain, nonatomic) NSMutableArray *rawLocations;
@property (readonly, nonatomic) BOOL hasSelectedHomeLocation;
@property (retain, nonatomic) AWDHomeKitMessageLocation *selectedHomeLocation;
@property (nonatomic) BOOL hasNumIterationToConverge;
@property (nonatomic) unsigned int numIterationToConverge;
@property (readonly, nonatomic) BOOL hasNearestLOI;
@property (retain, nonatomic) AWDHomeKitMessageLocation *nearestLOI;

/* class methods */
+ (Class)rawLocationsType;

/* instance methods */
- (void)clearRawLocations;
- (void)addRawLocations:(id)locations;
- (unsigned long long)rawLocationsCount;
- (id)rawLocationsAtIndex:(unsigned long long)index;
- (id)description;
- (id)dictionaryRepresentation;
- (BOOL)readFrom:(id)from;
- (void)writeTo:(id)to;
- (void)copyTo:(id)to;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (void)mergeFrom:(id)from;
@end

#endif /* AWDHomeKitMessageHomeLocationReport_h */
