//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMDCloudSyncLogEventsAnalyzer_h
#define HMDCloudSyncLogEventsAnalyzer_h
@import Foundation;

#include "HMDLogEventAnalyzer.h"
#include "HMDAggregationAnalysisEventContributing-Protocol.h"
#include "HMDEventCountersManager.h"
#include "HMDMetricsDeviceStateProvider-Protocol.h"
#include "HMMLogEventSubmitting-Protocol.h"

@interface HMDCloudSyncLogEventsAnalyzer : HMDLogEventAnalyzer<HMDAggregationAnalysisEventContributing>

@property (readonly, nonatomic) NSObject<HMDMetricsDeviceStateProvider> *deviceStateProvider;
@property (retain, nonatomic) HMDEventCountersManager *eventCountersManager;
@property (readonly, nonatomic) NSObject<HMMLogEventSubmitting> *logEventSubmitter;
@property unsigned long long dataSyncState;

/* class methods */
+ (id)managedEventCounterRequestGroups;

/* instance methods */
- (id)initWithEventCountersManager:(id)manager logEventSubmitter:(id)submitter deviceStateProvider:(id)provider;
- (void)didReceiveEventFromDispatcher:(id)dispatcher;
- (void)handleIncomingCloudPushLogEvent:(id)event;
- (void)handleFetchLogEvent:(id)event;
- (void)handleUploadLogEvent:(id)event;
- (void)handleUploadReasonLogEvent:(id)event;
- (void)handleMaximumDelayLogEvent:(id)event;
- (void)handleDecryptionCompletedEvent:(id)event;
- (void)handleRecordOperationLogEvent:(id)event;
- (id)cloudSyncAnalysisResult;
- (void)resetDataSource;
- (void)populateAggregationAnalysisLogEvent:(id)event;
- (void)resetAggregationAnalysisContext;
@end

#endif /* HMDCloudSyncLogEventsAnalyzer_h */
