//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMDCameraClipSignificantEventBulletin_h
#define HMDCameraClipSignificantEventBulletin_h
@import Foundation;

#include "HMDAccessory.h"
#include "HMDCameraProfile.h"
#include "HMDHome.h"
#include "HMDService.h"

@class NSDate, NSDictionary, NSSet, NSString, NSURL, NSUUID;

@interface HMDCameraClipSignificantEventBulletin : NSObject

@property (readonly, copy) NSSet *significantEvents;
@property (readonly, copy) NSUUID *previewImageNotificationUUID;
@property (readonly) NSURL *previewImageFilePathURL;
@property (readonly, copy) NSDate *dateOfOccurrence;
@property (readonly) HMDCameraProfile *camera;
@property (readonly) HMDHome *home;
@property (readonly) HMDAccessory *accessory;
@property (readonly) HMDService *service;
@property (readonly, copy) NSUUID *clipUUID;
@property (readonly) BOOL shouldShowProvideFeedbackButton;
@property (readonly, copy) NSDictionary *userInfo;
@property (readonly, copy) NSString *title;
@property (readonly, copy) NSString *body;
@property (readonly, copy) NSString *threadIdentifier;
@property (readonly, copy) NSString *requestIdentifier;

/* class methods */
+ (unsigned long long)effectiveReasonForSignificantEvent:(id)event;
+ (id)localizedMessageForSignificantEvents:(id)events cameraAccessory:(id)accessory;
+ (id)actionURLForHomeUUID:(id)uuid cameraUUID:(id)uuid;

/* instance methods */
- (id)initWithSignificantEvents:(id)events previewImageNotificationUUID:(id)uuid previewImageFilePathURL:(id)url dateOfOccurrence:(id)occurrence camera:(id)camera home:(id)home accessory:(id)accessory recordingService:(id)service requestIdentifier:(id)identifier clipUUID:(id)uuid shouldShowProvideFeedbackButton:(BOOL)button;
- (id)initWithSignificantEvents:(id)events previewImageNotificationUUID:(id)uuid previewImageFilePathURL:(id)url dateOfOccurrence:(id)occurrence camera:(id)camera home:(id)home accessory:(id)accessory recordingService:(id)service clipUUID:(id)uuid shouldShowProvideFeedbackButton:(BOOL)button;
- (id)initWithSignificantEvent:(id)event previewImageFilePathURL:(id)url dateOfOccurrence:(id)occurrence camera:(id)camera home:(id)home accessory:(id)accessory recordingService:(id)service shouldShowProvideFeedbackButton:(BOOL)button;
- (id)createUserInfoWithWithSignificantEvents:(id)events previewImageNotificationUUID:(id)uuid camera:(id)camera home:(id)home accessory:(id)accessory recordingService:(id)service clipUUID:(id)uuid;
@end

#endif /* HMDCameraClipSignificantEventBulletin_h */
