//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMDNotificationRegistryCoreDataCharacteristicsRequestResult_h
#define HMDNotificationRegistryCoreDataCharacteristicsRequestResult_h
@import Foundation;

#include "HMFObject.h"
#include "HMDNotificationRegistryCoreDataCharacteristicsRequest.h"

@class NSArray;

@interface HMDNotificationRegistryCoreDataCharacteristicsRequestResult : HMFObject

@property (readonly) HMDNotificationRegistryCoreDataCharacteristicsRequest *coreDataRequest;
@property (readonly) BOOL didSucceed;
@property (readonly) BOOL didModify;
@property (readonly) NSArray *modifiedCharacteristics;

/* instance methods */
- (id)initWithCoreDataRequest:(id)request didSucceed:(BOOL)succeed didModify:(BOOL)modify modifiedCharacteristics:(id)characteristics;
- (BOOL)isEqual:(id)equal;
@end

#endif /* HMDNotificationRegistryCoreDataCharacteristicsRequestResult_h */
