//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMDNetworkActivityWrapperFactory_h
#define HMDNetworkActivityWrapperFactory_h
@import Foundation;

#include "HMDNetworkActivityWrapperFactory-Protocol.h"

@class NSString;

@interface HMDNetworkActivityWrapperFactory : NSObject<HMDNetworkActivityWrapperFactory>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)networkActivityWrapperWithLabel:(unsigned long long)label;
@end

#endif /* HMDNetworkActivityWrapperFactory_h */
