//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1092.3.10.0.0
//
#ifndef HMDSettingModelProtocol_Protocol_h
#define HMDSettingModelProtocol_Protocol_h
@import Foundation;

@protocol HMDSettingModelProtocol <HMDSettingModelBaseProtocol>

@property (copy, nonatomic) NSNumber *type;
@property (copy, nonatomic) NSNumber *properties;
@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSNumber *numberValue;
@property (copy, nonatomic) NSString *stringValue;
@property (copy, nonatomic) NSData *dataValue;
@property (copy, nonatomic) NSUUID *selectionIdentifier;
@property (copy, nonatomic) NSString *selectionValue;

/* instance methods */
- (BOOL)setSettingValue:(id)value;
@end

#endif /* HMDSettingModelProtocol_Protocol_h */
