//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1161.4.0.0.0
//
#ifndef NPKPeerPaymentConversationManager_h
#define NPKPeerPaymentConversationManager_h
@import Foundation;

@class MSConversation, NPKPeerPaymentConversationContext, NSString, PKPeerPaymentController, PKPeerPaymentRecipient, PKPeerPaymentService;
@protocol NPKPeerPaymentConversationManagerDelegate, OS_dispatch_queue;

@interface NPKPeerPaymentConversationManager : NSObject {
  /* instance variables */
  NSObject<OS_dispatch_queue> *_internalQueue;
}

@property (retain, nonatomic) NSString *currentRecipientAddressLookup;
@property (weak, nonatomic) PKPeerPaymentController *currentPeerPaymentController;
@property (retain, nonatomic) PKPeerPaymentService *peerPaymentService;
@property (weak, nonatomic) NSObject<NPKPeerPaymentConversationManagerDelegate> *delegate;
@property (retain) MSConversation *activeConversation;
@property (readonly, nonatomic) NSString *senderPhoneOrEmail;
@property (readonly, nonatomic) NSString *recipientPhoneOrEmail;
@property (readonly, copy, nonatomic) NSString *recipientDisplayName;
@property (readonly, nonatomic) BOOL recipientFoundInContacts;
@property (readonly) PKPeerPaymentRecipient *recipient;
@property (retain, nonatomic) NPKPeerPaymentConversationContext *conversationContext;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)init;
- (void)lookupRecipientInformationIfNecessary;
- (void)performPaymentWithAmount:(id)amount requestToken:(id)token completion:(id /* block */)completion;
- (void)_internalQueue_performPaymentWithAmount:(id)amount requestToken:(id)token completion:(id /* block */)completion;
- (void)lookupRecipientInformationWithAddress:(id)address senderAddress:(id)address;
- (void)_internalQueue_lookupRecipientInformationWithAddress:(id)address senderAddress:(id)address;
- (void)_internalQueue_forceLookupRecipientInformation;
- (void)performRequestWithAmount:(id)amount completion:(id /* block */)completion;
- (void)_internalQueue_performRequestWithAmount:(id)amount completion:(id /* block */)completion;
- (void)_accountDidChange;
- (id)_displayableErrorWithError:(id)error;
- (id)_negativeBalanceErrorWithUnderlyingError:(id)error;
- (id)_ambiguousSenderAddressErrorWithUnderlyingError:(id)error;
- (id)_lockedOrRestrictedAccountErrorWithUnderlyingError:(id)error;
- (id)_unknownPaymentErrorWithUnderlyingError:(id)error;
- (id)_skeletonPeerPaymentQuoteWithPeerPaymentController:(id)controller selectedAmount:(id)amount recipient:(id)recipient;
- (void)_postNotificationWithRecipient:(id)recipient error:(id)error;
- (id)_sharedPeerPaymentWebService;
- (id)_newPeerPaymentController;
- (id)_newPeerPaymentControllerWithQueue:(id)queue;
@end

#endif /* NPKPeerPaymentConversationManager_h */
