//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 1161.4.0.0.0
//
#ifndef PKPaymentLocalPassCredential_NanoPassKit_h
#define PKPaymentLocalPassCredential_NanoPassKit_h
@import Foundation;

@interface PKPaymentLocalPassCredential (NanoPassKit)
/* instance methods */
- (id)_initWithPassTypeIdentifier:(id)identifier serialNumber:(id)number credentialType:(long long)type sanitizedPrimaryAccountNumber:(id)number longDescription:(id)description cardType:(long long)type;
@end

#endif /* PKPaymentLocalPassCredential_NanoPassKit_h */
