//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3431.206.0.0.0
//
#ifndef TISKTap_h
#define TISKTap_h
@import Foundation;

@class NSMutableArray, TIKeyboardLayout, TIKeyboardTouchEvent;

@interface TISKTap : NSObject

@property (retain, nonatomic) NSMutableArray *dragTouches;
@property (retain, nonatomic) TIKeyboardTouchEvent *firstTouch;
@property (retain, nonatomic) TIKeyboardTouchEvent *lastTouch;
@property (readonly, nonatomic) unsigned long long numberOfDrags;
@property (nonatomic) long long pathIndex;
@property (retain, nonatomic) TIKeyboardLayout *layout;
@property (readonly, nonatomic) BOOL downup;

/* instance methods */
- (id)init:(id)init layout:(id)layout;
- (void)addDragTouch:(id)touch;
- (BOOL)isDownUpTap;
- (double)downErrorDistance:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })distance;
- (double)upErrorDistance:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })distance;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })getFrameForKey:(id)key;
- (long long)_forcedKeyCode;
- (id)stringForIntendedKey;
- (double)distance:(id)distance withTouch:(id)touch;
- (double)totalTapDistance;
@end

#endif /* TISKTap_h */
