//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 3774.300.42.0.0
//
#ifndef MFMutableData_h
#define MFMutableData_h
@import Foundation;

#include "NSMutableData.h"
#include "NSCopying-Protocol.h"
#include "NSMutableCopying-Protocol.h"

@interface MFMutableData : NSMutableData<NSCopying, NSMutableCopying> {
  /* instance variables */
  void * _bytes;
  unsigned long long _length;
  unsigned long long _mappedLength;
  unsigned long long _capacity;
  unsigned long long _threshold;
  char * _path;
  int _fd;
  unsigned long long _flushFrom;
  BOOL _flush;
  BOOL _immutable;
  BOOL _vm;
}

/* instance methods */
- (id)init;
- (id)initWithBytes:(const void *)bytes length:(unsigned long long)length;
- (id)_initWithFd:(int)fd path:(id)path mutable:(BOOL)mutable;
- (id)initWithBytesNoCopy:(void *)copy length:(unsigned long long)length;
- (id)initWithBytesNoCopy:(void *)copy length:(unsigned long long)length freeWhenDone:(BOOL)done;
- (id)initWithContentsOfURL:(id)url options:(unsigned long long)options error:(id *)error;
- (id)initWithContentsOfURL:(id)url;
- (id)initWithContentsOfFile:(id)file options:(unsigned long long)options error:(id *)error;
- (id)initWithContentsOfFile:(id)file;
- (id)initWithData:(id)data;
- (id)initWithCapacity:(unsigned long long)capacity;
- (id)initWithLength:(unsigned long long)length;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (void)dealloc;
- (unsigned long long)length;
- (const void *)bytes;
- (void *)mutableBytes;
- (void)appendBytes:(const void *)bytes length:(unsigned long long)length;
- (void)appendData:(id)data;
- (id)subdataWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setLength:(unsigned long long)length;
- (void)setMappingThreshold:(unsigned int)threshold;
- (void)mf_makeImmutable;
- (BOOL)writeToFile:(id)file atomically:(BOOL)atomically;
- (BOOL)writeToURL:(id)url atomically:(BOOL)atomically;
- (BOOL)writeToFile:(id)file options:(unsigned long long)options error:(id *)error;
- (BOOL)writeToURL:(id)url options:(unsigned long long)options error:(id *)error;
- (void)_flushToDisk:(unsigned long long)disk capacity:(unsigned long long)capacity;
- (void)_mapMutableData:(BOOL)data;
- (BOOL)mf_immutable;
@end

#endif /* MFMutableData_h */
