name: Meowbili iDevice Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Archive App
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Archive DarockBili App
        run: |
          xcodebuild -scheme 'DarockBili Watch App' -configuration Debug -archivePath DarockBili_Debug.xcarchive clean archive CODE_SIGN_IDENTITY=""
          xcodebuild -scheme 'DarockBili Watch App' -configuration Release -archivePath DarockBili_Release.xcarchive clean archive CODE_SIGN_IDENTITY=""
          
      - name: Export IPA
        run: |
          mkdir ./Export_Debug
          mkdir ./Export_Release
          xcodebuild -exportArchive -archivePath DarockBili_Debug.xcarchive -exportPath ./Export_Debug -exportOptionsPlist ExportOptions.plist
          xcodebuild -exportArchive -archivePath DarockBili_Release.xcarchive -exportPath ./Export_Release -exportOptionsPlist ExportOptions.plist
          
      - name: Upload Debug IPA
        uses: actions/upload-artifact@v3
        with:
          name: Debug.ipa
          path: ./Export_Debug/DarockBili.ipa

      - name: Upload Release IPA
        uses: actions/upload-artifact@v3
        with:
          name: Release.ipa
          path: ./Export_Release/DarockBili.ipa
  
  build_for_testing:
    runs-on: macos-13
    name: Test App
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -scheme 'DarockBili Watch App' -configuration Release

      - name: Prepare Cache Folder
        run: mkdir Caches
      
      - name: Build and Test
        run: xcodebuild test -project ./DarockBili.xcodeproj -scheme 'DarockBili Watch App' -configuration Release -destination 'platform=watchOS Simulator,name=Apple Watch Series 7 (41mm),OS=10.0' -destination 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm),OS=10.0' -testPlan WatchAppUITestPlan -testProductsPath ./Caches/TestProducts.xctestproducts -derivedDataPath ./Caches/DerivedData | tee TestBuilding.log

      - name: Upload Building Log
        uses: actions/upload-artifact@v3
        with:
          name: Watch Testing Log
          path: ./TestBuilding.log

      - name: Rename Test Attachments
        run: for file in ./Caches/DerivedData/Logs/Test/Test-*.xcresult/Data/*; do if [ ! -f "$file" ]; then continue; fi; file_type=$(file -b --mime-type "$file"); extension=""; case "$file_type" in "image/jpeg" | "image/jpg") extension=".jpg";; "image/png") extension=".png";; "text/plain") extension=".txt";; *) extension=".dat";; esac; mv "$file" "$file$extension"; done

      - name: Upload Test Attachments
        uses: actions/upload-artifact@v3
        with:
          name: Test Attachments
          path: ./Caches/DerivedData/Logs/Test

  
