name: SSH Debugger

on: workflow_dispatch

jobs:
  Debug:
    runs-on: macos-13
    env:
      ASCAPI_ISSUER_ID: ${{ secrets.ASCAPI_ISSUER_ID }}
      ASCAPI_KEY: ${{ secrets.ASCAPI_KEY }}
      ASCAPI_KEY_ID: ${{ secrets.ASCAPI_KEY_ID }}
      BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
        
