name: Status Check Workflow

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Check Build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Cache Build Caches
        uses: actions/cache@v3
        with:
          key: check-build-cache
          path: |
            ~/Library/Developer/Xcode/DerivedData

      - name: Build DarockBili App
        run: |
          xcodebuild -scheme 'DarockBili Watch App' -configuration Release build CODE_SIGN_IDENTITY=""
          
