//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 598.10.0.0.0
//
#ifndef BKHIDEventClient_h
#define BKHIDEventClient_h
@import Foundation;

#include "BKHIDEventClientDelegate-Protocol.h"
#include "BSDescriptionProviding-Protocol.h"

@class BSMachPortSendRight, BSPortDeathSentinel, BSProcessDeathWatcher, NSString;
@protocol OS_dispatch_queue;

@interface BKHIDEventClient : NSObject<BSDescriptionProviding> {
  /* instance variables */
  NSObject<OS_dispatch_queue> *_queue;
  NSObject<BKHIDEventClientDelegate> *_queue_delegate;
  BSMachPortSendRight *_queue_sendRight;
  BSProcessDeathWatcher *_queue_pidWatcher;
  BSPortDeathSentinel *_queue_portSentinel;
  NSString *_queue_procName;
  int _queue_pid;
  BOOL _queue_invalidated;
}

@property (weak, nonatomic) NSObject<BKHIDEventClientDelegate> *delegate;
@property (readonly, nonatomic) int pid;
@property (readonly, nonatomic) BSMachPortSendRight *sendRight;
@property (nonatomic) BOOL terminating;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)initWithPid:(int)pid sendRight:(id)right;
- (id)initWithPid:(int)pid sendRight:(id)right queue:(id)queue;
- (id)initWithPid:(int)pid sendRight:(id)right queue:(id)queue processName:(id)name;
- (void)dealloc;
- (void)invalidate;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (BOOL)_deathByPid;
- (BOOL)_deathBySendRight;
- (void)_queue_invalidate;
- (void)_queue_performDelegateCallout:(id /* block */)callout;
- (BOOL)isTerminating;
@end

#endif /* BKHIDEventClient_h */
