//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 384.60.3.0.0
//
#ifndef UMUserPersonaContext_h
#define UMUserPersonaContext_h
@import Foundation;

#include "NSCopying-Protocol.h"

@protocol OS_voucher;

@interface UMUserPersonaContext : NSObject<NSCopying> {
  /* instance variables */
  NSObject<OS_voucher> *_voucher;
}

/* class methods */
+ (id)currentPersonaContext;

/* instance methods */
- (id)init;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)contextAdopt;
- (id)copyPersonaContext:(id *)context;
@end

#endif /* UMUserPersonaContext_h */
