//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 64562.3.1.1.0
//
#ifndef _XREngineeringTypeDef_h
#define _XREngineeringTypeDef_h
@import Foundation;

#include "XRXMLElementParser.h"
#include "XREngineeringTypeDef-Protocol.h"
#include "XREngineeringTypeEncodingConvention.h"

@class NSString;

@interface _XREngineeringTypeDef : XRXMLElementParser<XREngineeringTypeDef> {
  /* instance variables */
  BOOL _handledEncodingElement;
}

@property (retain, nonatomic) NSString *mnemonic;
@property (retain, nonatomic) NSString *title;
@property (retain, nonatomic) NSString *enumString;
@property (retain, nonatomic) NSString *usage;
@property (nonatomic) unsigned char impl;
@property (nonatomic) unsigned long long attributes;
@property (nonatomic) BOOL experimental;
@property (nonatomic) BOOL deprecated;
@property (retain, nonatomic) XREngineeringTypeEncodingConvention *encodingConvention;

/* class methods */
+ (id)_elementNameToClassMap;
+ (id)_elementNameToKVCMap;

/* instance methods */
- (void)addString:(id)string elementType:(id)type;
- (void)addAttribute:(unsigned long long)attribute;
- (void)didHandleEncodingElement;
- (void)_handleCompletion;
- (id)errorStringHeader;
- (long long)conventionalBitWidth;
@end

#endif /* _XREngineeringTypeDef_h */
