//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.454, BuildTime: 2024-02-08T22:07:34Z)
//
//    - LC_BUILD_VERSION:  Platform: watchOSSimulator, MinOS: 10.2, SDK: 10.2, Tool: ld (902.8)
//    - LC_SOURCE_VERSION: 64562.3.1.1.0
//
#ifndef XRSchemaElementsRecursiveParser_h
#define XRSchemaElementsRecursiveParser_h
@import Foundation;

#include "XRXMLElementParser.h"
#include "XRSchemaAnnotationPropertyReportingDelegate-Protocol.h"

@class NSMutableDictionary;

@interface XRSchemaElementsRecursiveParser : XRXMLElementParser<XRSchemaAnnotationPropertyReportingDelegate> {
  /* instance variables */
  NSMutableDictionary *_errorReplacementsByKey;
}

/* instance methods */
- (void)_handleStart;
- (void)elementWithName:(id)name parser:(id)parser key:(id)key finishedWithErrorReplacement:(id)replacement;
- (id)errorMessagesReplacements;
- (id)startElementWithName:(id)name attributes:(id)attributes line:(long long)line col:(long long)col;
@end

#endif /* XRSchemaElementsRecursiveParser_h */
